### ISSUE TITLE
[opencl] No device available

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#1006]
A guy was doing that
```
alignPlan = sift.LinearAlign(img1, devicetype='CPU')
```
And thre output was:
```
Traceback (most recent call last):
  File "align.py", line 9, in <module>
    alignPlan = sift.LinearAlign(img1, devicetype='CPU')
  File "/usr/local/lib/python2.7/dist-packages/silx/opencl/sift/alignment.py", line 130, in __init__
    self.ctx = pyopencl.Context(devices=[pyopencl.get_platforms()[self.device[0]].get_devices()[self.device[1]]])
TypeError: 'NoneType' object has no attribute '__getitem__'
```

In fact `silx.opencl.ocl.select_device()` returns `None` if the requested constrain is too high.

In his case he ask for a CPU, but only have a GPU device. It would be nice to raise an exception from `select_device` to avoid this kind of problem. `select_device` have enough information do display something very useful.

**Comment by t20100** [comment]
@vallsv can this be closed?

**Comment by vallsv** [comment]
No it was not fixed.

If PyOpenCL is not available, the error message is not explicit.

It have to be checked.
