### ISSUE TITLE
[sift] unsupported format character '<' (0x3c) at index 26

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#1074]
Found on this log: https://travis-ci.org/silx-kit/silx/jobs/270820350

- Travis, Mac OS X

```
test_max_min_rnd (silx.opencl.sift.test.test_reductions.TestReduction) ... INFO:silx.opencl.sift.test.test_reductions:values: -723 -> 501
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.12_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/2.7.12_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/local/Cellar/python/2.7.12_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/local/Cellar/python/2.7.12_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
ValueError: unsupported format character '<' (0x3c) at index 26
Logged from file test_reductions.py, line 117
ok
test_max_min (silx.opencl.sift.test.test_reductions.TestReduction) ... INFO:silx.opencl.sift.test.test_reductions:values: 0.0 -> 1.0
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.12_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/2.7.12_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/local/Cellar/python/2.7.12_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/local/Cellar/python/2.7.12_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
ValueError: unsupported format character '<' (0x3c) at index 26
```

**Comment by t20100** [comment]
Closing as issue occuring with python2.7.
