### ISSUE TITLE
Issue with PySide/matplotlib 2.1.0rc1

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#1083]
When matplotlib 2.1.0rc1 is used, tests are not passing with PySide (at least on Windows).
I reproduced locally and started looking at it but without success so far...

**Comment by vallsv** [comment]
Here is my small test:
```
import logging
logging.basicConfig()
from PySide import QtGui

logger = logging.getLogger("test")


app = QtGui.QApplication([])


class Foo_super(QtGui.QWidget):

    def __init__(self, parent=None):
        super(Foo_super, self).__init__(parent)

class Foo_oldschool(QtGui.QWidget):

    def __init__(self, parent=None):
        QtGui.QWidget.__init__(self, parent)


import matplotlib
matplotlib.use('Qt4Agg')
from matplotlib.backends.backend_qt4agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure

fig = Figure(figsize=(600,600), dpi=72, facecolor=(1,1,1), edgecolor=(0,0,0))
ax = fig.add_subplot(111)
ax.plot([0,1])

try:
    a = Foo_super()
except Exception as e:
    logger.error("Backtrace 1", exc_info=True)

try:
    a = Foo_oldschool()
except Exception as e:
    logger.error("Backtrace 2", exc_info=True)


canvas = FigureCanvas(fig)



try:
    a = Foo_super()
except Exception as e:
    logger.error("Backtrace 3", exc_info=True)

try:
    a = Foo_oldschool()
except Exception as e:
    logger.error("Backtrace 4", exc_info=True)
```


Here is the result:
```
ERROR:test:Backtrace 3
Traceback (most recent call last):
  File "test_matplotlib_vs_pyside.py", line 47, in <module>
    a = Foo_super()
  File "test_matplotlib_vs_pyside.py", line 14, in __init__
    super(Foo_super, self).__init__(parent)
TypeError: PySide.QtCore.QObject isn't a direct base class of Foo_super
ERROR:test:Backtrace 4
Traceback (most recent call last):
  File "test_matplotlib_vs_pyside.py", line 52, in <module>
    a = Foo_oldschool()
  File "test_matplotlib_vs_pyside.py", line 19, in __init__
    QtGui.QWidget.__init__(self, parent)
TypeError: PySide.QtCore.QObject isn't a direct base class of Foo_oldschool
```

**Comment by vallsv** [comment]
Then I created that issue on matplotlib: https://github.com/matplotlib/matplotlib/issues/9162

**Comment by vasole** [comment]
@t20100 

I think this can be closed with the acceptance of your patch and the release of matplotlib 2.1.0

**Comment by t20100** [comment]
Yes
