### ISSUE TITLE
[0.5.0] Problem when trying to open and hdf5 file

### ISSUE THREAD

**Issue by picca** [silx-kit/silx#1088]
Hello, while trying to open an hdf5 file, I got this error

```
picca@diffabs6:~$ ls -l /nfs/ruche-diffabs/diffabs-users/20151386/published-data/xrd/Louis\ Le\ Pieux/XRD18keV_35/XRD18keV_35.h5 
-rw-r--r-- 1 picca instrumentation 42562144 Jun 30 16:37 /nfs/ruche-diffabs/diffabs-users/20151386/published-data/xrd/Louis Le Pieux/XRD18keV_35/XRD18keV_35.h5
picca@diffabs6:~$ silx view /nfs/ruche-diffabs/diffabs-users/20151386/published-data/xrd/Louis\ Le\ Pieux/XRD18keV_35/XRD18keV_35.h5
WARNING:silx.app.view:Module 'hdf5plugin' is not installed. It supports some hdf5 compressions. You can install it using "pip install hdf5plugin".
Gtk-Message: Failed to load module "canberra-gtk-module"
WARNING:silx.gui.data.DataViews:Plot3dView is not available
WARNING:silx.gui.data.DataViewer:_Plot3dView instantiation failed. View is ignored
ERROR:silx.gui.qt._qt:<class 'OSError'> Unable to create file (Unable to open file: name = '/nfs/ruche-diffabs/diffabs-users/20151386/published-data/xrd/louis le pieux/xrd18kev_35/xrd18kev_35.h5', errno = 17, error message = 'file exists', flags = 15, o_flags = c2)   File "/usr/bin/silx", line 11, in <module>
    load_entry_point('silx==0.5.0', 'console_scripts', 'silx')()
  File "/usr/lib/python3/dist-packages/silx/__main__.py", line 59, in main
    status = launcher.execute(sys.argv)
  File "/usr/lib/python3/dist-packages/silx/utils/launcher.py", line 303, in execute
    return command.execute(command_argv)
  File "/usr/lib/python3/dist-packages/silx/utils/launcher.py", line 137, in execute
    status = func(argv)
  File "/usr/lib/python3/dist-packages/silx/app/view.py", line 320, in main
    window.appendFile(filename)
  File "/usr/lib/python3/dist-packages/silx/app/view.py", line 227, in appendFile
    self.__treeview.findHdf5TreeModel().appendFile(filename)
  File "/usr/lib/python3/dist-packages/silx/gui/hdf5/Hdf5TreeModel.py", line 581, in appendFile
    self.insertFile(filename, -1)
  File "/usr/lib/python3/dist-packages/silx/gui/hdf5/Hdf5TreeModel.py", line 574, in insertFile
    h5file = silx_io.open(filename)
  File "/usr/lib/python3/dist-packages/silx/io/utils.py", line 398, in open
    return h5py.File(filename)
  File "/usr/lib/python3/dist-packages/h5py/_hl/files.py", line 271, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/usr/lib/python3/dist-packages/h5py/_hl/files.py", line 126, in make_fid
    fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/build/h5py-b1xqNM/h5py-2.7.0/h5py/_objects.c:2842)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/build/h5py-b1xqNM/h5py-2.7.0/h5py/_objects.c:2800)
  File "h5py/h5f.pyx", line 98, in h5py.h5f.create (/build/h5py-b1xqNM/h5py-2.7.0/h5py/h5f.c:2294)
```

**Comment by vallsv** [comment]
Hi. Which version do you use?

**Comment by vallsv** [comment]
On old version there was a type, argv[0] has used as an input file.

**Comment by vallsv** [comment]
Nice. We already have the version on your log: 0.5.0. Thanks setuptools.

**Comment by vallsv** [comment]
Well. I am not able to reproduce the problem with the flagged version 0.5.0.
Can you send me the file by mail? The log is still strange.

**Comment by vallsv** [comment]
You are right. @PiRK fixed this issue few weeks ago. `h5py.File` was not used properly. See https://github.com/silx-kit/silx/commit/b73683282b5b373da12d58f2206db41b89dddd16

**Comment by picca** [comment]
It seems that I am not only affected by this problem.

I tryed from ipython to open the hdf5 file

```
In [8]: f = h5py.File('/nfs/ruche-diffabs/diffabs-users/20151386/published-data/xrd/Louis Le Pieux/XRD18keV_35/XRD18keV_35.h5', "r")
---------------------------------------------------------------------------
IOError                                   Traceback (most recent call last)
<ipython-input-8-3db606d9a37d> in <module>()
----> 1 f = h5py.File('/nfs/ruche-diffabs/diffabs-users/20151386/published-data/xrd/Louis Le Pieux/XRD18keV_35/XRD18keV_35.h5', "r")

/usr/lib/python2.7/dist-packages/h5py/_hl/files.pyc in __init__(self, name, mode, driver, libver, userblock_size, swmr, **kwds)
    269 
    270                 fapl = make_fapl(driver, libver, **kwds)
--> 271                 fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
    272 
    273                 if swmr_support:

/usr/lib/python2.7/dist-packages/h5py/_hl/files.pyc in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
     99         if swmr and swmr_support:
    100             flags |= h5f.ACC_SWMR_READ
--> 101         fid = h5f.open(name, flags, fapl=fapl)
    102     elif mode == 'r+':
    103         fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/build/h5py-b1xqNM/h5py-2.7.0/h5py/_objects.c:2842)()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/build/h5py-b1xqNM/h5py-2.7.0/h5py/_objects.c:2800)()

h5py/h5f.pyx in h5py.h5f.open (/build/h5py-b1xqNM/h5py-2.7.0/h5py/h5f.c:2127)()

IOError: Unable to open file (Unable to flock file, errno = 13, error message = 'permission denied')
```

**Comment by vallsv** [comment]
I still can't reproduce the problem, but maybe it also depends on the version of hdf5 or h5py.
```
valls@linkdick:/workspace/valls/silx.git$ ls -al foo.h5 
-r--r--r-- 1 valls valls 17494251 Sep  5 17:37 foo.h5
valls@linkdick:/workspace/valls/silx.git$ /home/valls/.local/bin/silx view foo.h5 
valls@linkdick:/workspace/valls/silx.git$ /home/valls/.local/bin/silx --version
silx version 0.5.0
```

**Comment by picca** [comment]
After copying the file on my local system, I can open it...

```
In [1]: import h5py

In [2]: f = h5py.File('/tmp/XRD18keV_35.h5', "r")

In [3]: 
```

So it seems that there is a problem with our nfs ruche system.

**Comment by vallsv** [comment]
From our application, you should have this log if you dont have permission on the file. It is checked earlier by argparse before trying using h5py.
```
valls@linkdick:/workspace/valls/silx.git$ /home/valls/.local/bin/silx view foo.h5 
usage: silx view [-h] [files [files ...]]
silx view: error: argument files: can't open 'foo.h5': [Errno 13] Permission denied: 'foo.h5'
```

**Comment by picca** [comment]
I discoverd, thaht I need to mount my nfs moun tpoin twith the local_lock=flock in order to make it work.
It was not the case with jessie.
