### ISSUE TITLE
[histo] Histogram action can create nbin in floating point

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#1090]
Here is a bug report from @picca 
https://github.com/silx-kit/pyFAI/issues/679

```
ERROR:pyFAI-calib2.UNCAUGHT:'numpy.float64' object cannot be interpreted as an index
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/silx/gui/plot/PlotActions.py", line 1199, in _triggered
    self.computeIntensityDistribution()
  File "/usr/lib/python2.7/dist-packages/silx/gui/plot/PlotActions.py", line 1243, in computeIntensityDistribution
    histogram = Histogramnd(data, n_bins=nbins, histo_range=data_range)
  File "/usr/lib/python2.7/dist-packages/silx/math/histogram.py", line 251, in __init__
    wh_dtype=self.__wh_dtype)
  File "silx/math/histogramnd/chistogramnd.pyx", line 286, in chistogramnd.chistogramnd (silx/math/histogramnd/chistogramnd.c:4784)
TypeError: 'numpy.float64' object cannot be interpreted as an index
```

**Comment by vallsv** [comment]
Should be fixed. the plotaction and the cython code was protected. Let see if the issue will be reopened.
