### ISSUE TITLE
[test] CI fails for TestSpecH5

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#1107]
Expected logs are not produced/catched propely:
```
======================================================================
ERROR: testVisit (silx.io.test.test_spech5.TestSpecH5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\silx\venv_test\lib\site-packages\silx\test\utils.py", line 219, in wrapper
    result = func(*args, **kwargs)
  File "C:\projects\silx\venv_test\lib\site-packages\silx\test\utils.py", line 175, in __exit__
    expected_count, logging.getLevelName(level), count))
RuntimeError: Expected 2 WARNING logging messages, got 0
======================================================================
ERROR: testVisitItems (silx.io.test.test_spech5.TestSpecH5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\silx\venv_test\lib\site-packages\silx\test\utils.py", line 219, in wrapper
    result = func(*args, **kwargs)
  File "C:\projects\silx\venv_test\lib\site-packages\silx\test\utils.py", line 175, in __exit__
    expected_count, logging.getLevelName(level), count))
RuntimeError: Expected 2 WARNING logging messages, got 0
======================================================================
```

**Comment by PiRK** [comment]
This seems to affect Mac OS only. 

If I remove the `@test_logging(warning=2)` decorator for the failing tests on my machine, the expected warnings are logged:
```
testVisit (silx.io.test.test_spech5.TestSpecH5) ... WARNING:silx.io.spech5:No #D line in scan 1000.1 header. Using file header for start_time.
WARNING:silx.io.spech5:No #D line in scan 1001.1 header. Using file header for start_time.
ok
testVisitItems (silx.io.test.test_spech5.TestSpecH5) ... WARNING:silx.io.spech5:No #D line in scan 1000.1 header. Using file header for start_time.
WARNING:silx.io.spech5:No #D line in scan 1001.1 header. Using file header for start_time.
ok
```

I need to investigate why the warnings are not logged on Mac OS. They should not be platform specific.

**Comment by PiRK** [comment]
Nevermind, now it fails on my Debian 8 too. I forgot to merge the master.

**Comment by PiRK** [comment]
With the new commonh5 module, the entire SpecH5 tree is build when a SPEC file is opened. So the warnings are now logged in setUp and no longer while the visit() method is executed.
