### ISSUE TITLE
[plotwidget] Fail to display float128 setImage

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#1288]
I tried to display a float128 image into a `PlotWidget` using `setImage`.

- The plot fail at the repaint
- The repaint is not synchronous with the `setImage` then we can't catch the exception
- After that, the plot is locked: can't use anymore `setImage` with a working data (that's the blocking point for me)

Any idea?

```
Traceback (most recent call last):
  File "/home/valls/.local/lib/python2.7/site-packages/silx/gui/plot/backends/BackendBase.py", line 317, in postRedisplay
    plot.replot()
  File "/home/valls/.local/lib/python2.7/site-packages/silx/gui/plot/PlotWidget.py", line 2612, in replot
    item._update(self._backend)
  File "/home/valls/.local/lib/python2.7/site-packages/silx/gui/plot/items/core.py", line 291, in _update
    self._backendRenderer = self._addBackendRenderer(backend)
  File "/home/valls/.local/lib/python2.7/site-packages/silx/gui/plot/items/image.py", line 281, in _addBackendRenderer
    alpha=self.getAlpha())
  File "/home/valls/.local/lib/python2.7/site-packages/silx/gui/plot/backends/BackendMatplotlib.py", line 309, in addImage
    image.set_data(data)
  File "/usr/lib/python2.7/dist-packages/matplotlib/image.py", line 434, in set_data
    raise TypeError("Image data can not convert to float")
TypeError: Image data can not convert to float
```

Trying with silx view, the result is the same
```
valls@linkdick /workspace/valls $ python -m silx view
ERROR:silx.gui.qt._qt:<type 'exceptions.TypeError'> No matching signature found   File "/home/valls/.local/lib/python2.7/site-packages/silx/gui/plot/ColorBar.py", line 213, in _activeImageChanged
    data=image)
  File "/home/valls/.local/lib/python2.7/site-packages/silx/gui/plot/ColorBar.py", line 159, in setColormap
    data=data)
  File "/home/valls/.local/lib/python2.7/site-packages/silx/gui/plot/ColorBar.py", line 389, in setColormap
    self.colorScale.setColormap(colormap, data)
  File "/home/valls/.local/lib/python2.7/site-packages/silx/gui/plot/ColorBar.py", line 518, in setColormap
    self.vmin, self.vmax = self._colormap.getColormapRange(data=data)
  File "/home/valls/.local/lib/python2.7/site-packages/silx/gui/plot/Colormap.py", line 251, in getColormapRange
    min_, max_ = min_max(data, min_positive=False, finite=True)
  File "silx/math/combo.pyx", line 320, in silx.math.combo.min_max (silx/math/combo.c:17719)
  File "silx/math/combo.pyx", line 210, in silx.math.combo.__pyx_fused_cpdef (silx/math/combo.c:15832)

ERROR:silx.gui.qt._qt:<type 'exceptions.TypeError'> Image data can not convert to float   File "/home/valls/.local/lib/python2.7/site-packages/silx/gui/plot/backends/BackendBase.py", line 317, in postRedisplay
    plot.replot()
  File "/home/valls/.local/lib/python2.7/site-packages/silx/gui/plot/PlotWidget.py", line 2612, in replot
    item._update(self._backend)
  File "/home/valls/.local/lib/python2.7/site-packages/silx/gui/plot/items/core.py", line 291, in _update
    self._backendRenderer = self._addBackendRenderer(backend)
  File "/home/valls/.local/lib/python2.7/site-packages/silx/gui/plot/items/image.py", line 281, in _addBackendRenderer
    alpha=self.getAlpha())
  File "/home/valls/.local/lib/python2.7/site-packages/silx/gui/plot/backends/BackendMatplotlib.py", line 309, in addImage
    image.set_data(data)
  File "/usr/lib/python2.7/dist-packages/matplotlib/image.py", line 434, in set_data
    raise TypeError("Image data can not convert to float")
```

**Comment by vallsv** [comment]
pip list, just in case
```
appdirs (1.4.3)
argcomplete (0.8.1)
argh (0.25.0)
argparse (1.2.1)
args (0.1.0)
backports-abc (0.4)
backports.shutil-get-terminal-size (1.0.0)
bleach (1.4.3)
bottle (0.12.8)
certifi (2016.9.26)
cffi (0.8.6)
chardet (2.3.0)
cliapp (1.20140719)
clint (0.5.1)
cmdtest (0.12)
colorama (0.3.7)
configparser (3.5.0)
contextlib2 (0.5.5)
cool (0.1)
coverage (3.7.1)
cryptography (0.6.1)
cudarray (0.1.dev0)
cycler (0.10.0)
Cython (0.25.2)
decorator (4.0.10)
deeppy (0.1.dev0)
defusedxml (0.4.1)
dispcalGUI (2.5.0.0)
docutils (0.12)
entrypoints (0.2.2)
enum34 (1.1.6)
fabio (0.5.0)
functools32 (3.2.3.post2)
future (0.16.0)
gevent (1.0.1)
Glymur (0.8.10)
greenlet (0.4.10)
h5py (2.7.1)
h5pyd (0.2.3)
hdf5plugin (1.4.0)
html5lib (0.9999999)
ipykernel (4.5.0)
ipython (5.1.0)
ipython-genutils (0.1.0)
ipywidgets (5.2.2)
Jinja2 (2.8)
joblib (0.8.3)
jsonschema (2.5.1)
jupyter (1.0.0)
jupyter-client (4.4.0)
jupyter-console (5.0.0)
jupyter-core (4.2.0)
landslide (1.1.3)
libtiff (0.4.1.dev0)
Louie (1.1)
lxml (3.4.0)
Mako (1.0.0)
Markdown (2.6.7)
MarkupSafe (0.23)
matplotlib (1.4.2)
mistune (0.7.3)
mock (1.0.1)
MySQL-python (1.2.3)
nbconvert (5.0.0b1)
nbformat (4.1.0)
ndg-httpsclient (0.3.2)
nose (1.3.4)
notebook (4.2.3)
numexpr (2.6.2)
numpy (1.13.1)
packaging (16.8)
pathlib2 (2.1.0)
pathtools (0.1.2)
pexpect (4.2.1)
pickleshare (0.7.4)
Pillow (2.6.1)
pimpmypillow (0.1.2)
Pint (0.7.2)
pip (1.5.6)
pkginfo (1.4.1)
ply (3.4)
pp (1.6.4)
progressbar (2.3)
prompt-toolkit (1.0.8)
protobuf (3.0.0)
ptyprocess (0.5.1)
pyasn1 (0.1.7)
PyCifRW (4.2.1)
pycparser (2.10)
pycups (1.9.63)
pycurl (7.19.5)
pyFAI (0.15.0a1)
PyFFTW3 (0.2.2)
Pygments (2.1.3)
pygobject (3.14.0)
PyMca (4.7.4)
pynput (1.3.7)
pyopencl (2014.1)
PyOpenGL (3.0.2)
pyOpenSSL (0.14)
pyparsing (2.2.0)
pyqtgraph (0.10.0)
pysmbc (1.0.15.3)
Pyste (0.9.10)
python-apt (0.9.3.12)
python-dateutil (2.6.1)
python-debian (0.1.27)
python-debianbts (1.11)
python-xlib (0.19)
pytools (2014.3)
pytz (2017.2)
pyxdg (0.25)
PyYAML (3.11)
pyzmq (16.0.0)
qtconsole (4.2.1)
QtPy (1.2.1)
reportbug (6.6.3)
reportlab (3.1.8)
requests (2.12.3)
requests-toolbelt (0.7.0)
rfoo (1.3.0)
roman (2.0.0)
RunSnakeRun (2.0.4)
scikit-image (0.10.1)
scikit-learn (0.14.1)
scipy (0.19.0)
setuptools (36.4.0)
silx (0.7.0a0)
simplegeneric (0.8.1)
simplejson (3.6.5)
singledispatch (3.4.0.3)
six (1.10.0)
SOAPpy (0.12.22)
SpecClient (1.0)
Sphinx (1.2.3)
Sphinx-PyPI-upload (0.2.1)
sphinxcontrib-programoutput (0.8.dev20140629)
sps (0.6.0)
SquareMap (1.0.4)
subprocess32 (3.2.7)
tables (3.1.1)
terminado (0.6)
tornado (4.4.2)
traitlets (4.3.1)
ttystatus (0.23)
twine (1.8.1)
urllib3 (1.9.1)
watchdog (0.7.0)
wcwidth (0.1.7)
wheel (0.24.0)
widgetsnbextension (1.2.6)
wsgiref (0.1.2)
wstools (0.4.3)
wxPython (3.0.1.1)
wxPython-common (3.0.1.1)
xvfbwrapper (0.2.4)
```

**Comment by jcesardasilva** [comment]
Hi Valentin,

It seems you have a very old version of matplotlib. The most recent one is
2.1, and you have 1.4.2.
There is a dependence on matplotlib, and I saw that the handling of
float128 by matplotlib was implement this year.


Le vendredi 13 octobre 2017, Valentin Valls <notifications@github.com> a
écrit :

**Comment by vallsv** [comment]
Thanks for the feedback.
Anyway if we have a change to avoid the lock of the plot it would be nice. This matplotlib version is the default version of Debian 8.

**Comment by t20100** [comment]
We can convert to float64 in the matplotlib backend (and log a warning) if the version of matplotlib does not support it.
