### ISSUE TITLE
Test of the GUI failed on OSX python2.7

### ISSUE THREAD

**Issue by kif** [silx-kit/silx#133]
Jeromes-MacBook-Pro:silx kieffer$ python setup.py build test build_doc
missing cimport in module 'specfile': silx/io/specfile/specfile.pyx
missing cimport in module 'histogramnd_c': silx/math/histogramnd/chistogramnd.pyx
running build
running build_py
running build_ext
running test
WARNING:run_tests:Building silx to /Users/kieffer/workspace/silx/build/lib.macosx-10.11-intel-2.7
missing cimport in module 'specfile': silx/io/specfile/specfile.pyx
missing cimport in module 'histogramnd_c': silx/math/histogramnd/chistogramnd.pyx
running build
running build_py
running build_ext
WARNING:run_tests:Patched sys.path, added: '/Users/kieffer/workspace/silx/build/lib.macosx-10.11-intel-2.7'
WARNING:run_tests:Test silx 0.2.0-dev0 from /Users/kieffer/workspace/silx/build/lib.macosx-10.11-intel-2.7/silx
..........2016-07-04 11:25:57.695 Python[891:6816] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
...F......EFF.............................................................s.............................................................................................................................................................................................................................................................................................................................................................................................................WARNING:silx.math.fit.leastsq:Supplied function does not return a 1D array of floats.
Function should be rewritten.
Trying to reshape output.
WARNING:silx.math.fit.leastsq:Supplied function does not return a 1D array of floats.
Function should be rewritten.
Trying to reshape output.
.WARNING:silx.math.fit.leastsq:Recommended to set full_output to True when using constraints
WARNING:silx.math.fit.leastsq:Recommended to set full_output to True when using constraints
WARNING:silx.math.fit.leastsq:Recommended to set full_output to True when using constraints
WARNING:silx.math.fit.leastsq:Recommended to set full_output to True when using constraints
WARNING:silx.math.fit.leastsq:Recommended to set full_output to True when using constraints
WARNING:silx.math.fit.leastsq:Recommended to set full_output to True when using constraints
WARNING:silx.math.fit.leastsq:Recommended to set full_output to True when using constraints
WARNING:silx.math.fit.leastsq:Recommended to set full_output to True when using constraints
WARNING:silx.math.fit.leastsq:Recommended to set full_output to True when using constraints
WARNING:silx.math.fit.leastsq:Recommended to set full_output to True when using constraints
WARNING:silx.math.fit.leastsq:Recommended to set full_output to True when using constraints
WARNING:silx.math.fit.leastsq:Recommended to set full_output to True when using constraints
./Users/kieffer/workspace/silx/build/lib.macosx-10.11-intel-2.7/silx/math/test/test_fit.py:51: RuntimeWarning: invalid value encountered in multiply
  return numpy.exp(x*numpy.less(abs(x), 250)) - \
WARNING:silx.math.fit.leastsq:Supplied function does not return a proper array of floats.
Function should be rewritten to return a 1D array of floats.
Trying to reshape output.
WARNING:silx.math.fit.leastsq:Supplied function unable to handle non-finite x data
Attempting to filter out those x data values.
WARNING:silx.math.fit.leastsq:Need to reshape input xdata.
...........
======================================================================
ERROR: testFailingConverters (silx.gui.plot.test.testPlotTools.TestPositionInfo)
Test PositionInfo with failing custom converters
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/kieffer/workspace/silx/build/lib.macosx-10.11-intel-2.7/silx/testutils.py", line 205, in wrapper
    result = func(*args, **kwargs)
  File "/Users/kieffer/workspace/silx/build/lib.macosx-10.11-intel-2.7/silx/testutils.py", line 161, in __exit__
    expected_count, logging.getLevelName(level), count))
RuntimeError: Expected 2 ERROR logging messages, got 0

======================================================================
FAIL: testWithAnImage (silx.gui.plot.test.testMaskToolsWidget.TestMaskToolsWidget)
Plot with an image: test MaskToolsWidget interactions
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/kieffer/workspace/silx/build/lib.macosx-10.11-intel-2.7/silx/gui/plot/test/testMaskToolsWidget.py", line 161, in testWithAnImage
    self.assertFalse(numpy.all(numpy.equal(self.maskWidget.getMask(), 0)))
AssertionError: True is not false

======================================================================
FAIL: testAlignedProfile (silx.gui.plot.test.testPlotTools.TestProfileToolBar)
Test horizontal and vertical profile, without and with image [] (mode=Vertical Profile Mode)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/kieffer/workspace/silx/build/lib.macosx-10.11-intel-2.7/silx/gui/plot/test/testPlotTools.py", line 171, in testAlignedProfile
    self.assertIsNot(toolButton, None)
AssertionError: unexpectedly identical: None

======================================================================
FAIL: testDiagonalProfile (silx.gui.plot.test.testPlotTools.TestProfileToolBar)
Test diagonal profile, without and with image
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/kieffer/workspace/silx/build/lib.macosx-10.11-intel-2.7/silx/gui/plot/test/testPlotTools.py", line 199, in testDiagonalProfile
    self.assertIsNot(toolButton, None)
AssertionError: unexpectedly identical: None

----------------------------------------------------------------------
Ran 495 tests in 31.323s

FAILED (failures=3, errors=1, skipped=1)
WARNING:run_tests:Test suite failed

**Comment by kif** [comment]
apparently this is related to test-window-clicked not in foreplan
