### ISSUE TITLE
issue on python3 OSX ...

### ISSUE THREAD

**Issue by kif** [silx-kit/silx#134]
Jeromes-MacBook-Pro:silx kieffer$ python3 setup.py build test build_doc
Traceback (most recent call last):
  File "setup.py", line 296, in <module>
    config = configuration()
  File "setup.py", line 292, in configuration
    config.add_subpackage(PROJECT)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/numpy/distutils/misc_util.py", line 1003, in add_subpackage
    caller_level = 2)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/numpy/distutils/misc_util.py", line 972, in get_subpackage
    caller_level = caller_level + 1)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/numpy/distutils/misc_util.py", line 909, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "silx/setup.py", line 36, in configuration
    config.add_subpackage('io')
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/numpy/distutils/misc_util.py", line 1003, in add_subpackage
    caller_level = 2)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/numpy/distutils/misc_util.py", line 972, in get_subpackage
    caller_level = caller_level + 1)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/numpy/distutils/misc_util.py", line 884, in _get_configuration_from_setup_py
    ('.py', 'U', 1))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 658, in exec_module
  File "<frozen importlib._bootstrap_external>", line 763, in get_code
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/imp.py", line 156, in get_data
    return file.read()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1335: ordinal not in range(128)

**Comment by kif** [comment]
FIX: set the full languages ...
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

**Comment by kif** [comment]
TODO: update doc accordingly

**Comment by vallsv** [comment]
The issue is also generated by the integration  of ipython qtconsole

**Comment by vallsv** [comment]
Looks to be fixed.
