### ISSUE TITLE
[convert] converting HDF5 files is currently not supported, and error message is cryptic

### ISSUE THREAD

**Issue by PiRK** [silx-kit/silx#1378]
We should either support it (could be useful for merging files) or print a better error message.
```
 silx convert ../../data/CuZnO_2.spec.h5 -o ../../data/CuZnO_2.spec.h5_2

Traceback (most recent call last):
  File "bootstrap.py", line 218, in <module>
    run_entry_point(target, argv)
  File "bootstrap.py", line 143, in run_entry_point
    func()
  File "/users/knobel/git/silx/build/lib.linux-x86_64-2.7/silx/__main__.py", line 65, in main
    status = launcher.execute(sys.argv)
  File "/users/knobel/git/silx/build/lib.linux-x86_64-2.7/silx/utils/launcher.py", line 303, in execute
    return command.execute(command_argv)
  File "/users/knobel/git/silx/build/lib.linux-x86_64-2.7/silx/utils/launcher.py", line 137, in execute
    status = func(argv)
  File "/users/knobel/git/silx/build/lib.linux-x86_64-2.7/silx/app/convert.py", line 272, in main
    min_size=options.min_size)
  File "/users/knobel/git/silx/build/lib.linux-x86_64-2.7/silx/io/convert.py", line 271, in write_to_h5
    writer.write(h5pylike, h5file)
  File "/users/knobel/git/silx/build/lib.linux-x86_64-2.7/silx/io/convert.py", line 164, in write
    infile.visititems(self.append_member_to_h5, visit_links=True)
TypeError: visititems() got an unexpected keyword argument 'visit_links'
```

**Comment by vasole** [comment]
I would take one of these:

- Take an easy solution and provide a gentle message refusing to do it and suggesting to use links
- Create a file consisting on links.

I am for the first solution.
