### ISSUE TITLE
Random test fail with travis macOS python3 environment

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#1398]
```
======================================================================

ERROR: testLoadSaveFit2D (silx.gui.plot.test.testMaskToolsWidget.TestMaskToolsWidget)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/Users/travis/build/silx-kit/silx/venv/lib/python3.6/site-packages/silx/gui/plot/test/testMaskToolsWidget.py", line 254, in testLoadSaveFit2D

    self.__loadSave("msk")

  File "/Users/travis/build/silx-kit/silx/venv/lib/python3.6/site-packages/silx/gui/plot/test/testMaskToolsWidget.py", line 231, in __loadSave

    self._drawPolygon()

  File "/Users/travis/build/silx-kit/silx/venv/lib/python3.6/site-packages/silx/gui/plot/test/testMaskToolsWidget.py", line 105, in _drawPolygon

    self.mouseMove(plot, pos=(0, 0))

  File "/Users/travis/build/silx-kit/silx/venv/lib/python3.6/site-packages/silx/gui/plot/test/utils.py", line 164, in mouseMove

    TestCaseQt.mouseMove(self, widget, pos=pos, delay=delay)

  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 88, in __exit__

    next(self.gen)

  File "/Users/travis/build/silx-kit/silx/venv/lib/python3.6/site-packages/silx/gui/plot/test/utils.py", line 115, in _waitForMplEvent

    raise RuntimeError("MPL event %s expected but nothing received" % mplEventType)

RuntimeError: MPL event motion_notify_event expected but nothing received

======================================================================

ERROR: testLoadSaveNpy (silx.gui.plot.test.testMaskToolsWidget.TestMaskToolsWidget)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/Users/travis/build/silx-kit/silx/venv/lib/python3.6/site-packages/silx/gui/plot/test/testMaskToolsWidget.py", line 249, in testLoadSaveNpy

    self.__loadSave("npy")

  File "/Users/travis/build/silx-kit/silx/venv/lib/python3.6/site-packages/silx/gui/plot/test/testMaskToolsWidget.py", line 231, in __loadSave

    self._drawPolygon()

  File "/Users/travis/build/silx-kit/silx/venv/lib/python3.6/site-packages/silx/gui/plot/test/testMaskToolsWidget.py", line 105, in _drawPolygon

    self.mouseMove(plot, pos=(0, 0))

  File "/Users/travis/build/silx-kit/silx/venv/lib/python3.6/site-packages/silx/gui/plot/test/utils.py", line 164, in mouseMove

    TestCaseQt.mouseMove(self, widget, pos=pos, delay=delay)

  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 88, in __exit__

    next(self.gen)

  File "/Users/travis/build/silx-kit/silx/venv/lib/python3.6/site-packages/silx/gui/plot/test/utils.py", line 115, in _waitForMplEvent

    raise RuntimeError("MPL event %s expected but nothing received" % mplEventType)

RuntimeError: MPL event motion_notify_event expected but nothing received

======================================================================

ERROR: test (silx.gui.plot.test.testPlotInteraction.TestSelectPolygon)

Test draw polygons + events

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/Users/travis/build/silx-kit/silx/venv/lib/python3.6/site-packages/silx/gui/plot/test/testPlotInteraction.py", line 104, in test

    events = self._draw(star)

  File "/Users/travis/build/silx-kit/silx/venv/lib/python3.6/site-packages/silx/gui/plot/test/testPlotInteraction.py", line 70, in _draw

    self.mouseMove(plot, pos=pos)

  File "/Users/travis/build/silx-kit/silx/venv/lib/python3.6/site-packages/silx/gui/plot/test/utils.py", line 164, in mouseMove

    TestCaseQt.mouseMove(self, widget, pos=pos, delay=delay)

  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 88, in __exit__

    next(self.gen)

  File "/Users/travis/build/silx-kit/silx/venv/lib/python3.6/site-packages/silx/gui/plot/test/utils.py", line 115, in _waitForMplEvent

    raise RuntimeError("MPL event %s expected but nothing received" % mplEventType)

RuntimeError: MPL event motion_notify_event expected but nothing received
```

e.g., https://travis-ci.org/silx-kit/silx/jobs/311875687

**Comment by t20100** [comment]
Doesn't seems to be random...

**Comment by vallsv** [comment]
Yes, that's the network popup. Unfortunatly it is shown after the use of the close_popup application. A work around is to add a sleep of few minutes, but it is kind of ridiculous.

**Comment by t20100** [comment]
Yes that would not be great... I try to use previous macOS image (as for python2) as a quick fix.

**Comment by t20100** [comment]
Now it is OK
