### ISSUE TITLE
[silx view] in looking at dataset from cbflib

### ISSUE THREAD

**Issue by kif** [silx-kit/silx#1453]
```
ERROR:silx.gui.hdf5.Hdf5TreeView:Error while calling callback
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/silx/gui/hdf5/Hdf5TreeView.py", line 114, in _createContextMenu
    callback(event)
  File "/usr/lib/python3/dist-packages/silx/app/view.py", line 211, in closeAndSyncCustomContextMenu
    if obj.ntype is h5py.File:
  File "/usr/lib/python3/dist-packages/silx/gui/hdf5/_utils.py", line 141, in __getattr__
    raise AttributeError("H5Node has no attribute %s" % name)
AttributeError: H5Node has no attribute ntype
```

**Comment by kif** [comment]
check before accessing object.

**Comment by kif** [comment]
fixed recently
