### ISSUE TITLE
[plot] Click fail with the last matplotlib

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#1514]
In CI we can think it is a problem with system popups, but it is not.

Reproduced here with a virtualenv, Debian 8, Python 3.5

```
Package         Version
--------------- -------
cycler          0.10.0 
Cython          0.27.3 
fabio           0.5.0  
h5py            2.7.1  
matplotlib      2.1.2  
numexpr         2.6.4  
numpy           1.14.0 
pip             9.0.1  
pynput          1.3.9  
pyparsing       2.2.0  
PyQt5           5.10   
python-dateutil 2.6.1  
python-xlib     0.21   
pytz            2017.3 
scipy           1.0.0  
setuptools      37.0.0 
silx            0.6.0a0
sip             4.19.7 
six             1.11.0 
wheel           0.30.0 
```

Here is the full log
```
(py35-pyqt5)valls@linkdick /workspace/valls/silx.git (pr/1505) $ py35-pyqt5 ./run_tests.py 
WARNING:py.warnings:/workspace/valls/env/py35-pyqt5/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters

INFO:silx.setup:Use setuptools
INFO:silx.setup:Use setuptools.setup
WARNING:run_tests:Building silx to /workspace/valls/silx.git/build/lib.linux-x86_64-3.5
INFO:silx.setup:Use setuptools
silx.io.specfile WARNING:
A cleaner locale independent implementation
may be achieved setting SPECFILE_USE_GNU_SOURCE to 1
For instance running this script as:
SPECFILE_USE_GNU_SOURCE=1 python setup.py build
running build
running build_py
running build_ext
silx/third_party/_local/scipy_spatial/qhull.pyx: cannot find cimported module 'silx.third_party._local.scipy_spatial'
building 'silx.math.combo' extension
C compiler: gcc -pthread -Wno-unused-result -Wsign-compare -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -g -DNDEBUG

compile options: '-Isilx/math/include -I/usr/local/include/python3.5m -c'
building 'silx.image.bilinear' extension
C compiler: gcc -pthread -Wno-unused-result -Wsign-compare -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -g -DNDEBUG

compile options: '-I/usr/local/include/python3.5m -c'
building 'silx.image.shapes' extension
C compiler: gcc -pthread -Wno-unused-result -Wsign-compare -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -g -DNDEBUG

compile options: '-I/usr/local/include/python3.5m -c'
WARNING:run_tests:Patched sys.path, added: '/workspace/valls/silx.git/build/lib.linux-x86_64-3.5'
WARNING:run_tests:Test silx 0.7.0-dev0 from /workspace/valls/silx.git/build/lib.linux-x86_64-3.5/silx
WARNING:silx.opencl.common:Unable to import pyOpenCl. Please install it from: http://pypi.python.org/pypi/pyopencl
WARNING:silx.opencl.codec.byte_offset:No PyOpenCL, no byte-offset, please see fabio
WARNING:silx.gui.test:silx.gui.plot3d tests disabled (PyOpenGL or QtOpenGL not installed)
WARNING:silx.opencl.sift.match:No PyOpenCL, no sift
WARNING:silx.opencl.sift.alignment:No PyOpenCL, no sift
WARNING:silx.opencl.sift.test.test_matching:feature module is not available to compare results with C++ implementation. Matching cannot be tested.
...................................................E.E
Stderr:
ERROR:silx.gui.test.utils:Screenshot saved at /workspace/valls/silx.git/build/test-debug/Screenshot_silx.gui.plot.test.testMaskToolsWidget.TestMaskToolsWidget.testSigMaskChangedEmitted.png

Stderr:
ERROR:silx.gui.test.utils:Screenshot saved at /workspace/valls/silx.git/build/test-debug/Screenshot_silx.gui.plot.test.testMaskToolsWidget.TestMaskToolsWidget.testWithAnImage.png
ERROR:silx.gui.test.utils:Screenshot saved at /workspace/valls/silx.git/build/test-debug/Screenshot_silx.gui.plot.test.testMaskToolsWidget.TestMaskToolsWidget.testWithAnImage.png
ERROR:silx.gui.test.utils:Screenshot saved at /workspace/valls/silx.git/build/test-debug/Screenshot_silx.gui.plot.test.testMaskToolsWidget.TestMaskToolsWidget.testWithAnImage.png
ERROR:silx.gui.test.utils:Screenshot saved at /workspace/valls/silx.git/build/test-debug/Screenshot_silx.gui.plot.test.testMaskToolsWidget.TestMaskToolsWidget.testWithAnImage.png
...E
Stderr:
ERROR:silx.gui.test.utils:Screenshot saved at /workspace/valls/silx.git/build/test-debug/Screenshot_silx.gui.plot.test.testScatterMaskToolsWidget.TestScatterMaskToolsWidget.testSigMaskChangedEmitted.png
E
Stderr:
ERROR:silx.gui.test.utils:Screenshot saved at /workspace/valls/silx.git/build/test-debug/Screenshot_silx.gui.plot.test.testScatterMaskToolsWidget.TestScatterMaskToolsWidget.testWithAScatter.png
..........................................................................................................................................................................................................................................s...............................................................s.........................s................................................................................................................................................................................................................................s.....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................s..........ssssssssssssssssssssssssssssssssssssssssssssss..........
======================================================================
ERROR: testLoadSaveFit2D (silx.gui.plot.test.testMaskToolsWidget.TestMaskToolsWidget)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/valls/silx.git/build/lib.linux-x86_64-3.5/silx/gui/plot/test/testMaskToolsWidget.py", line 69, in tearDown
    super(TestMaskToolsWidget, self).tearDown()
  File "/workspace/valls/silx.git/build/lib.linux-x86_64-3.5/silx/gui/plot/test/utils.py", line 84, in tearDown
    super(PlotWidgetTestCase, self).tearDown()
  File "/workspace/valls/silx.git/build/lib.linux-x86_64-3.5/silx/gui/test/utils.py", line 201, in tearDown
    self._checkForUnreleasedWidgets()
  File "/workspace/valls/silx.git/build/lib.linux-x86_64-3.5/silx/gui/test/utils.py", line 193, in _checkForUnreleasedWidgets
    "Test ended with widgets alive: %s" % str(widgets))
RuntimeError: Test ended with widgets alive: [<PyQt5.QtWidgets.QWidget object at 0x7fe4f85dd828>, <PyQt5.QtWidgets.QDesktopWidget object at 0x7fe4f85ddee8>]

======================================================================
ERROR: testSigMaskChangedEmitted (silx.gui.plot.test.testMaskToolsWidget.TestMaskToolsWidget)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/valls/silx.git/build/lib.linux-x86_64-3.5/silx/gui/plot/test/testMaskToolsWidget.py", line 276, in testSigMaskChangedEmitted
    self._drag()
  File "/workspace/valls/silx.git/build/lib.linux-x86_64-3.5/silx/gui/plot/test/testMaskToolsWidget.py", line 90, in _drag
    self.mouseMove(plot, pos=pos1)
  File "/workspace/valls/silx.git/build/lib.linux-x86_64-3.5/silx/gui/plot/test/utils.py", line 164, in mouseMove
    TestCaseQt.mouseMove(self, widget, pos=pos, delay=delay)
  File "/usr/local/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/workspace/valls/silx.git/build/lib.linux-x86_64-3.5/silx/gui/plot/test/utils.py", line 115, in _waitForMplEvent
    raise RuntimeError("MPL event %s expected but nothing received" % mplEventType)
RuntimeError: MPL event motion_notify_event expected but nothing received

Stderr:
ERROR:silx.gui.test.utils:Screenshot saved at /workspace/valls/silx.git/build/test-debug/Screenshot_silx.gui.plot.test.testMaskToolsWidget.TestMaskToolsWidget.testSigMaskChangedEmitted.png

======================================================================
ERROR: testWithAnImage (silx.gui.plot.test.testMaskToolsWidget.TestMaskToolsWidget) (origin=(0, 0), scale=(1, 1))
Plot with an image: test MaskToolsWidget interactions
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/valls/silx.git/build/lib.linux-x86_64-3.5/silx/gui/plot/test/testMaskToolsWidget.py", line 163, in testWithAnImage
    self._drag()
  File "/workspace/valls/silx.git/build/lib.linux-x86_64-3.5/silx/gui/plot/test/testMaskToolsWidget.py", line 90, in _drag
    self.mouseMove(plot, pos=pos1)
  File "/workspace/valls/silx.git/build/lib.linux-x86_64-3.5/silx/gui/plot/test/utils.py", line 164, in mouseMove
    TestCaseQt.mouseMove(self, widget, pos=pos, delay=delay)
  File "/usr/local/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/workspace/valls/silx.git/build/lib.linux-x86_64-3.5/silx/gui/plot/test/utils.py", line 115, in _waitForMplEvent
    raise RuntimeError("MPL event %s expected but nothing received" % mplEventType)
RuntimeError: MPL event motion_notify_event expected but nothing received

Stderr:
ERROR:silx.gui.test.utils:Screenshot saved at /workspace/valls/silx.git/build/test-debug/Screenshot_silx.gui.plot.test.testMaskToolsWidget.TestMaskToolsWidget.testWithAnImage.png
ERROR:silx.gui.test.utils:Screenshot saved at /workspace/valls/silx.git/build/test-debug/Screenshot_silx.gui.plot.test.testMaskToolsWidget.TestMaskToolsWidget.testWithAnImage.png
ERROR:silx.gui.test.utils:Screenshot saved at /workspace/valls/silx.git/build/test-debug/Screenshot_silx.gui.plot.test.testMaskToolsWidget.TestMaskToolsWidget.testWithAnImage.png
ERROR:silx.gui.test.utils:Screenshot saved at /workspace/valls/silx.git/build/test-debug/Screenshot_silx.gui.plot.test.testMaskToolsWidget.TestMaskToolsWidget.testWithAnImage.png

======================================================================
ERROR: testWithAnImage (silx.gui.plot.test.testMaskToolsWidget.TestMaskToolsWidget) (origin=(1000, 1000), scale=(1, 1))
Plot with an image: test MaskToolsWidget interactions
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/valls/silx.git/build/lib.linux-x86_64-3.5/silx/gui/plot/test/testMaskToolsWidget.py", line 163, in testWithAnImage
    self._drag()
  File "/workspace/valls/silx.git/build/lib.linux-x86_64-3.5/silx/gui/plot/test/testMaskToolsWidget.py", line 90, in _drag
    self.mouseMove(plot, pos=pos1)
  File "/workspace/valls/silx.git/build/lib.linux-x86_64-3.5/silx/gui/plot/test/utils.py", line 164, in mouseMove
    TestCaseQt.mouseMove(self, widget, pos=pos, delay=delay)
  File "/usr/local/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/workspace/valls/silx.git/build/lib.linux-x86_64-3.5/silx/gui/plot/test/utils.py", line 115, in _waitForMplEvent
    raise RuntimeError("MPL event %s expected but nothing received" % mplEventType)
RuntimeError: MPL event motion_notify_event expected but nothing received

Stderr:
ERROR:silx.gui.test.utils:Screenshot saved at /workspace/valls/silx.git/build/test-debug/Screenshot_silx.gui.plot.test.testMaskToolsWidget.TestMaskToolsWidget.testWithAnImage.png
ERROR:silx.gui.test.utils:Screenshot saved at /workspace/valls/silx.git/build/test-debug/Screenshot_silx.gui.plot.test.testMaskToolsWidget.TestMaskToolsWidget.testWithAnImage.png
ERROR:silx.gui.test.utils:Screenshot saved at /workspace/valls/silx.git/build/test-debug/Screenshot_silx.gui.plot.test.testMaskToolsWidget.TestMaskToolsWidget.testWithAnImage.png
ERROR:silx.gui.test.utils:Screenshot saved at /workspace/valls/silx.git/build/test-debug/Screenshot_silx.gui.plot.test.testMaskToolsWidget.TestMaskToolsWidget.testWithAnImage.png

======================================================================
ERROR: testWithAnImage (silx.gui.plot.test.testMaskToolsWidget.TestMaskToolsWidget) (origin=(0, 0), scale=(-1, -1))
Plot with an image: test MaskToolsWidget interactions
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/valls/silx.git/build/lib.linux-x86_64-3.5/silx/gui/plot/test/testMaskToolsWidget.py", line 163, in testWithAnImage
    self._drag()
  File "/workspace/valls/silx.git/build/lib.linux-x86_64-3.5/silx/gui/plot/test/testMaskToolsWidget.py", line 90, in _drag
    self.mouseMove(plot, pos=pos1)
  File "/workspace/valls/silx.git/build/lib.linux-x86_64-3.5/silx/gui/plot/test/utils.py", line 164, in mouseMove
    TestCaseQt.mouseMove(self, widget, pos=pos, delay=delay)
  File "/usr/local/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/workspace/valls/silx.git/build/lib.linux-x86_64-3.5/silx/gui/plot/test/utils.py", line 115, in _waitForMplEvent
    raise RuntimeError("MPL event %s expected but nothing received" % mplEventType)
RuntimeError: MPL event motion_notify_event expected but nothing received

Stderr:
ERROR:silx.gui.test.utils:Screenshot saved at /workspace/valls/silx.git/build/test-debug/Screenshot_silx.gui.plot.test.testMaskToolsWidget.TestMaskToolsWidget.testWithAnImage.png
ERROR:silx.gui.test.utils:Screenshot saved at /workspace/valls/silx.git/build/test-debug/Screenshot_silx.gui.plot.test.testMaskToolsWidget.TestMaskToolsWidget.testWithAnImage.png
ERROR:silx.gui.test.utils:Screenshot saved at /workspace/valls/silx.git/build/test-debug/Screenshot_silx.gui.plot.test.testMaskToolsWidget.TestMaskToolsWidget.testWithAnImage.png
ERROR:silx.gui.test.utils:Screenshot saved at /workspace/valls/silx.git/build/test-debug/Screenshot_silx.gui.plot.test.testMaskToolsWidget.TestMaskToolsWidget.testWithAnImage.png

======================================================================
ERROR: testWithAnImage (silx.gui.plot.test.testMaskToolsWidget.TestMaskToolsWidget) (origin=(1000, 1000), scale=(-1, -1))
Plot with an image: test MaskToolsWidget interactions
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/valls/silx.git/build/lib.linux-x86_64-3.5/silx/gui/plot/test/testMaskToolsWidget.py", line 163, in testWithAnImage
    self._drag()
  File "/workspace/valls/silx.git/build/lib.linux-x86_64-3.5/silx/gui/plot/test/testMaskToolsWidget.py", line 90, in _drag
    self.mouseMove(plot, pos=pos1)
  File "/workspace/valls/silx.git/build/lib.linux-x86_64-3.5/silx/gui/plot/test/utils.py", line 164, in mouseMove
    TestCaseQt.mouseMove(self, widget, pos=pos, delay=delay)
  File "/usr/local/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/workspace/valls/silx.git/build/lib.linux-x86_64-3.5/silx/gui/plot/test/utils.py", line 115, in _waitForMplEvent
    raise RuntimeError("MPL event %s expected but nothing received" % mplEventType)
RuntimeError: MPL event motion_notify_event expected but nothing received

Stderr:
ERROR:silx.gui.test.utils:Screenshot saved at /workspace/valls/silx.git/build/test-debug/Screenshot_silx.gui.plot.test.testMaskToolsWidget.TestMaskToolsWidget.testWithAnImage.png
ERROR:silx.gui.test.utils:Screenshot saved at /workspace/valls/silx.git/build/test-debug/Screenshot_silx.gui.plot.test.testMaskToolsWidget.TestMaskToolsWidget.testWithAnImage.png
ERROR:silx.gui.test.utils:Screenshot saved at /workspace/valls/silx.git/build/test-debug/Screenshot_silx.gui.plot.test.testMaskToolsWidget.TestMaskToolsWidget.testWithAnImage.png
ERROR:silx.gui.test.utils:Screenshot saved at /workspace/valls/silx.git/build/test-debug/Screenshot_silx.gui.plot.test.testMaskToolsWidget.TestMaskToolsWidget.testWithAnImage.png

======================================================================
ERROR: testSigMaskChangedEmitted (silx.gui.plot.test.testScatterMaskToolsWidget.TestScatterMaskToolsWidget)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/valls/silx.git/build/lib.linux-x86_64-3.5/silx/gui/plot/test/testScatterMaskToolsWidget.py", line 295, in testSigMaskChangedEmitted
    self._drag()
  File "/workspace/valls/silx.git/build/lib.linux-x86_64-3.5/silx/gui/plot/test/testScatterMaskToolsWidget.py", line 92, in _drag
    self.mouseMove(plot, pos=pos1)
  File "/workspace/valls/silx.git/build/lib.linux-x86_64-3.5/silx/gui/plot/test/utils.py", line 164, in mouseMove
    TestCaseQt.mouseMove(self, widget, pos=pos, delay=delay)
  File "/usr/local/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/workspace/valls/silx.git/build/lib.linux-x86_64-3.5/silx/gui/plot/test/utils.py", line 115, in _waitForMplEvent
    raise RuntimeError("MPL event %s expected but nothing received" % mplEventType)
RuntimeError: MPL event motion_notify_event expected but nothing received

Stderr:
ERROR:silx.gui.test.utils:Screenshot saved at /workspace/valls/silx.git/build/test-debug/Screenshot_silx.gui.plot.test.testScatterMaskToolsWidget.TestScatterMaskToolsWidget.testSigMaskChangedEmitted.png

======================================================================
ERROR: testWithAScatter (silx.gui.plot.test.testScatterMaskToolsWidget.TestScatterMaskToolsWidget)
Plot with a Scatter: test MaskToolsWidget interactions
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/valls/silx.git/build/lib.linux-x86_64-3.5/silx/gui/plot/test/testScatterMaskToolsWidget.py", line 165, in testWithAScatter
    self._drag()
  File "/workspace/valls/silx.git/build/lib.linux-x86_64-3.5/silx/gui/plot/test/testScatterMaskToolsWidget.py", line 92, in _drag
    self.mouseMove(plot, pos=pos1)
  File "/workspace/valls/silx.git/build/lib.linux-x86_64-3.5/silx/gui/plot/test/utils.py", line 164, in mouseMove
    TestCaseQt.mouseMove(self, widget, pos=pos, delay=delay)
  File "/usr/local/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/workspace/valls/silx.git/build/lib.linux-x86_64-3.5/silx/gui/plot/test/utils.py", line 115, in _waitForMplEvent
    raise RuntimeError("MPL event %s expected but nothing received" % mplEventType)
RuntimeError: MPL event motion_notify_event expected but nothing received

Stderr:
ERROR:silx.gui.test.utils:Screenshot saved at /workspace/valls/silx.git/build/test-debug/Screenshot_silx.gui.plot.test.testScatterMaskToolsWidget.TestScatterMaskToolsWidget.testWithAScatter.png

======================================================================
SKIPPED: testMovieIconExists (silx.gui.test.test_icons.TestAnimatedIcons)
----------------------------------------------------------------------
MNG not supported
======================================================================
SKIPPED: testCubeWithComplex (silx.gui.data.test.test_dataviewer.TestDataView)
----------------------------------------------------------------------
OpenGL widget not yet tested
======================================================================
SKIPPED: runTest (silx.gui.test.suite.<locals>.SkipPlot3DTest)
----------------------------------------------------------------------
silx.gui.plot3d tests disabled (PyOpenGL or QtOpenGL not installed)
======================================================================
SKIPPED: test_locale_de_DE (silx.io.test.test_specfile.TestSFLocale)
----------------------------------------------------------------------
de_DE.utf8 locale not installed
======================================================================
SKIPPED: testOpenCLMedFilt2d (silx.image.test.test_medianfilter.TestMedianFilterEngines)
test cpp engine for medfilt2d
----------------------------------------------------------------------
PyOpenCl is missing
======================================================================
SKIPPED: test_add (silx.opencl.test.test_addition.TestAddition)
----------------------------------------------------------------------
PyOpenCl is missing
======================================================================
SKIPPED: test_measurement (silx.opencl.test.test_addition.TestAddition)
----------------------------------------------------------------------
PyOpenCl is missing
======================================================================
SKIPPED: test_medfilt (silx.opencl.test.test_medfilt.TestMedianFilter)
----------------------------------------------------------------------
PyOpenCl is missing
======================================================================
SKIPPED: test_fbp (silx.opencl.test.test_backprojection.TestFBP)
----------------------------------------------------------------------
PyOpenCl is missing
======================================================================
SKIPPED: test_proj (silx.opencl.test.test_projection.TestProj)
----------------------------------------------------------------------
PyOpenCl is missing
======================================================================
SKIPPED: test_gradient (silx.opencl.test.test_linalg.TestLinAlg)
----------------------------------------------------------------------
PyOpenCl is missing
======================================================================
SKIPPED: test_divergence (silx.opencl.test.test_linalg.TestLinAlg)
----------------------------------------------------------------------
PyOpenCl is missing
======================================================================
SKIPPED: test_laplacian (silx.opencl.test.test_linalg.TestLinAlg)
----------------------------------------------------------------------
PyOpenCl is missing
======================================================================
SKIPPED: test_cpy2d (silx.opencl.test.test_array_utils.TestCpy2d)
----------------------------------------------------------------------
PyOpenCl is missing
======================================================================
SKIPPED: test_decompress (silx.opencl.codec.test.test_byte_offset.TestByteOffset)
----------------------------------------------------------------------
PyOpenCl or fabio is missing
======================================================================
SKIPPED: test_many_decompress (silx.opencl.codec.test.test_byte_offset.TestByteOffset)
----------------------------------------------------------------------
PyOpenCl or fabio is missing
======================================================================
SKIPPED: test_encode (silx.opencl.codec.test.test_byte_offset.TestByteOffset)
Test byte offset compression
----------------------------------------------------------------------
PyOpenCl or fabio is missing
======================================================================
SKIPPED: test_encode_to_array (silx.opencl.codec.test.test_byte_offset.TestByteOffset)
Test byte offset compression while providing an out array
----------------------------------------------------------------------
PyOpenCl or fabio is missing
======================================================================
SKIPPED: test_encode_to_bytes (silx.opencl.codec.test.test_byte_offset.TestByteOffset)
Test byte offset compression to bytes
----------------------------------------------------------------------
PyOpenCl or fabio is missing
======================================================================
SKIPPED: test_encode_to_bytes_from_array (silx.opencl.codec.test.test_byte_offset.TestByteOffset)
Test byte offset compression to bytes from a pyopencl array.
----------------------------------------------------------------------
PyOpenCl or fabio is missing
======================================================================
SKIPPED: test_many_encode (silx.opencl.codec.test.test_byte_offset.TestByteOffset)
Test byte offset compression with many image
----------------------------------------------------------------------
PyOpenCl or fabio is missing
======================================================================
SKIPPED: test_combine (silx.opencl.sift.test.test_algebra.TestAlgebra)
----------------------------------------------------------------------
PyOpenCl is missing
======================================================================
SKIPPED: test_compact (silx.opencl.sift.test.test_algebra.TestAlgebra)
----------------------------------------------------------------------
PyOpenCl is missing
======================================================================
SKIPPED: test_v1_odd (silx.opencl.sift.test.test_gaussian.TestGaussian)
----------------------------------------------------------------------
ocl or scipy is missing
======================================================================
SKIPPED: test_v1_even (silx.opencl.sift.test.test_gaussian.TestGaussian)
----------------------------------------------------------------------
ocl or scipy is missing
======================================================================
SKIPPED: test_v2_odd (silx.opencl.sift.test.test_gaussian.TestGaussian)
----------------------------------------------------------------------
ocl or scipy is missing
======================================================================
SKIPPED: test_v2_even (silx.opencl.sift.test.test_gaussian.TestGaussian)
----------------------------------------------------------------------
ocl or scipy is missing
======================================================================
SKIPPED: test_uint8 (silx.opencl.sift.test.test_preproc.TestPreproc)
----------------------------------------------------------------------
no scipy or ocl
======================================================================
SKIPPED: test_uint16 (silx.opencl.sift.test.test_preproc.TestPreproc)
----------------------------------------------------------------------
no scipy or ocl
======================================================================
SKIPPED: test_uint32 (silx.opencl.sift.test.test_preproc.TestPreproc)
----------------------------------------------------------------------
no scipy or ocl
======================================================================
SKIPPED: test_uint64 (silx.opencl.sift.test.test_preproc.TestPreproc)
----------------------------------------------------------------------
no scipy or ocl
======================================================================
SKIPPED: test_int32 (silx.opencl.sift.test.test_preproc.TestPreproc)
----------------------------------------------------------------------
no scipy or ocl
======================================================================
SKIPPED: test_int64 (silx.opencl.sift.test.test_preproc.TestPreproc)
----------------------------------------------------------------------
no scipy or ocl
======================================================================
SKIPPED: test_rgb (silx.opencl.sift.test.test_preproc.TestPreproc)
----------------------------------------------------------------------
no scipy or ocl
======================================================================
SKIPPED: test_shrink (silx.opencl.sift.test.test_preproc.TestPreproc)
----------------------------------------------------------------------
no scipy or ocl
======================================================================
SKIPPED: test_bin (silx.opencl.sift.test.test_preproc.TestPreproc)
----------------------------------------------------------------------
no scipy or ocl
======================================================================
SKIPPED: test_convol (silx.opencl.sift.test.test_convol.TestConvol)
----------------------------------------------------------------------
scipy or opencl not available
======================================================================
SKIPPED: test_convol_hor (silx.opencl.sift.test.test_convol.TestConvol)
----------------------------------------------------------------------
scipy or opencl not available
======================================================================
SKIPPED: test_convol_vert (silx.opencl.sift.test.test_convol.TestConvol)
----------------------------------------------------------------------
scipy or opencl not available
======================================================================
SKIPPED: test_gradient (silx.opencl.sift.test.test_image.TestImage)
----------------------------------------------------------------------
OpenCL missing
======================================================================
SKIPPED: test_local_maxmin (silx.opencl.sift.test.test_image.TestImage)
----------------------------------------------------------------------
OpenCL missing
======================================================================
SKIPPED: test_interpolation (silx.opencl.sift.test.test_image.TestImage)
----------------------------------------------------------------------
OpenCL missing
======================================================================
SKIPPED: test_descriptor (silx.opencl.sift.test.test_keypoints.test_keypoints)
----------------------------------------------------------------------
opencl or scipy missing
======================================================================
SKIPPED: test_orientation (silx.opencl.sift.test.test_keypoints.test_keypoints)
----------------------------------------------------------------------
opencl or scipy missing
======================================================================
SKIPPED: test_descriptor (silx.opencl.sift.test.test_keypoints.test_keypoints)
----------------------------------------------------------------------
opencl or scipy missing
======================================================================
SKIPPED: test_orientation (silx.opencl.sift.test.test_keypoints.test_keypoints)
----------------------------------------------------------------------
opencl or scipy missing
======================================================================
SKIPPED: test_descriptor (silx.opencl.sift.test.test_keypoints.test_keypoints)
----------------------------------------------------------------------
opencl or scipy missing
======================================================================
SKIPPED: test_orientation (silx.opencl.sift.test.test_keypoints.test_keypoints)
----------------------------------------------------------------------
opencl or scipy missing
======================================================================
SKIPPED: test_matching (silx.opencl.sift.test.test_matching.TestMatching)
----------------------------------------------------------------------
no scipy or ocl
======================================================================
SKIPPED: test_align (silx.opencl.sift.test.test_align.TestLinalign)
----------------------------------------------------------------------
scipy or pyopencl are missing
======================================================================
SKIPPED: test_transform (silx.opencl.sift.test.test_transform.TestTransform)
----------------------------------------------------------------------
scipy or ocl missing
----------------------------------------------------------------------
Ran 1322 tests in 95.202s

FAILED (errors=8, skipped=51)

```

**Comment by vallsv** [comment]
I test the mask tool manually without any problem.

**Comment by t20100** [comment]
Part of the issues (those due to `RuntimeError: MPL event motion_notify_event expected but nothing received`) looks to come from PyQt5.10 (It's OK with PyQt5.9.2)
