### ISSUE TITLE
[plot] syncaxis.py example raises an error when closing

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#1590]
On macOS with python 3.5 and PyQt5.10, I get the following error with `syncaxis.py` example:

```
QObject::disconnect: No such signal QObject::sigLimitsChanged(double,double)
Exception ignored in: <bound method SyncAxes.__del__ of <silx.gui.plot.utils.axis.SyncAxes object at 0x110e75048>>
Traceback (most recent call last):
  File "silx/gui/plot/utils/axis.py", line 131, in __del__
  File "silx/gui/plot/utils/axis.py", line 124, in stop
TypeError: disconnect() failed between 'sigLimitsChanged' and 'unislot'
```

Is `SyncAxis.__del__` needed?

**Comment by vallsv** [comment]
```
Test synchronization when sync object is destroyed ... Traceback (most recent call last):
  File "C:\projects\silx\venv_test\lib\site-packages\silx\utils\weakref.py", line 177, in __call__
    raise ReferenceError("weakly-referenced object no longer exists")
ReferenceError: weakly-referenced object no longer exists
```
It looks to be a yes.

**Comment by vallsv** [comment]
On Python 3.5 PyQt 5.10
```
./run_tests.py silx.gui.plot.test.testUtilsAxis
Unhandled Python exception
```

**Comment by vallsv** [comment]
Became more and more ugly, but it works

**Comment by t20100** [comment]
Reopening as I still get an error on macOS, python 3.5, PyQt5.10 when closing `syncaxis.py` sample code:


```
Exception ignored in: <bound method SyncAxes.__del__ of <silx.gui.plot.utils.axis.SyncAxes object at 0x110ef4400>>
Traceback (most recent call last):
  File "/Users/tvincent/src/silx/build/lib.macosx-10.6-intel-3.5/silx/gui/plot/utils/axis.py", line 155, in __del__
  File "/Users/tvincent/src/silx/build/lib.macosx-10.6-intel-3.5/silx/gui/plot/utils/axis.py", line 147, in stop
AttributeError: 'NoneType' object has no attribute 'sigLimitsChanged'

```
