### ISSUE TITLE
ROI button crashes a simple app

### ISSUE THREAD

**Issue by mretegan** [silx-kit/silx#1591]
The application created using the code below crashes when the ROI button is pressed. The traceback is at the end.

```python
#!/usr/bin/env python3

import numpy as np

from PyQt5.QtWidgets import QApplication, QMainWindow

from silx.gui.plot import PlotWindow

def main():
    app = QApplication([])

    window = QMainWindow()
    window.show()
    window.setGeometry(100, 100, 1000, 700)

    plot = PlotWindow()
    plot.getDefaultColormap().setName('viridis')
    window.setCentralWidget(plot)

    x = np.outer(
        np.linspace(-10, 10, 200), np.linspace(-10, 5, 150))
    image = np.sin(x) / x
    plot.addImage(image)

    app.exec_()


if __name__ == '__main__':
    main()
```

```shell
Traceback (most recent call last):
  File "/Users/marius/Library/Python/3.6/lib/python/site-packages/silx/gui/plot/backends/BackendBase.py", line 317, in postRedisplay
    plot.replot()
  File "/Users/marius/Library/Python/3.6/lib/python/site-packages/silx/gui/plot/PlotWidget.py", line 2477, in replot
    item._update(self._backend)
  File "/Users/marius/Library/Python/3.6/lib/python/site-packages/silx/gui/plot/items/core.py", line 294, in _update
    self._backendRenderer = self._addBackendRenderer(backend)
  File "/Users/marius/Library/Python/3.6/lib/python/site-packages/silx/gui/plot/items/marker.py", line 73, in _addBackendRenderer
    overlay=self.isOverlay())
TypeError: addMarker() got an unexpected keyword argument 'overlay'
[1]    23412 abort      python3 embed.py
```

**Comment by vasole** [comment]
The ROI button only works on 1D data and you have an image. It must be due to that. In any case, the application should not crash.

**Comment by vasole** [comment]
Cannot reproduce it with current master.
