### ISSUE TITLE
error when running the plot3d example

### ISSUE THREAD

**Issue by PiRK** [silx-kit/silx#1630]
```
C:\Users\opdau\pirk\silx>pip install .
Processing c:\users\opdau\pirk\silx
Requirement already satisfied: numpy in c:\python35\lib\site-packages (from silx==0.7.0a0)
Requirement already satisfied: setuptools in c:\python35\lib\site-packages (from silx==0.7.0a0)
Installing collected packages: silx
  Found existing installation: silx 0.6.0a0
    Uninstalling silx-0.6.0a0:
      Successfully uninstalled silx-0.6.0a0
  Running setup.py install for silx ... done
Successfully installed silx-0.7.0a0

C:\Users\opdau\pirk\silx>
C:\Users\opdau\pirk\silx>
C:\Users\opdau\pirk\silx>python silx\examples\plot3dSceneWindow.py
python: can't open file 'silx\examples\plot3dSceneWindow.py': [Errno 2] No such file or directory

C:\Users\opdau\pirk\silx>cd ..

C:\Users\opdau\pirk>python silx\examples\plot3dSceneWindow.py
Traceback (most recent call last):
  File "silx\examples\plot3dSceneWindow.py", line 59, in <module>
    window = SceneWindow()
  File "c:\Python35\lib\site-packages\silx\gui\plot3d\SceneWindow.py", line 74, in __init__
    self._paramTreeView.setModel(self._sceneWidget.model())
  File "c:\Python35\lib\site-packages\silx\gui\plot3d\ParamTreeView.py", line 521, in setModel
    self._openEditors()
  File "c:\Python35\lib\site-packages\silx\gui\plot3d\ParamTreeView.py", line 513, in _openEditors
    self._openEditorForIndex(index)
  File "c:\Python35\lib\site-packages\silx\gui\plot3d\ParamTreeView.py", line 497, in _openEditorForIndex
    data = index.data(qt.Qt.EditRole)
TypeError: unable to convert a C++ 'QVector3D' instance to a Python object
```

**Comment by PiRK** [comment]
Not sure if it is related, but on Debian 8 I get a long log of errors when starting the example0, but it eventually works. Traceback (most recent call last):
```
  File "/users/knobel/git/silx/build/lib.linux-x86_64-2.7/silx/gui/plot3d/ParamTreeView.py", line 515, in dataChanged
    super(ParamTreeView, self).dataChanged(topLeft, bottomRight, roles)
TypeError: QTreeView.dataChanged(QModelIndex, QModelIndex): too many arguments
```

**Comment by t20100** [comment]
The second issue is an API change between Qt4 and Qt5, I'll make a PR for that.

The first issue as far as I have tested only occurs with PyQt5.7.1.
It works fine with PyQt v5.6, v5.7, v5.8, v5.9 and v5.10... but not with v5.7.1...
To me, it is a won't fix.

**Comment by vasole** [comment]
We had said that for windows we "officially" support the latest versions
