### ISSUE TITLE
[silx view] Message when closing silx view

### ISSUE THREAD

**Issue by vasole** [silx-kit/silx#1638]
Under windows 3.6, Qt5 I get this error when closing the application:

```
C:\Users\sole\Documents\ownCloud\SYNCHRONIZED\DATA\SARDANA>silx view ..\MULTIELE
MENT\xanes2.h5
Exception ignored in: <bound method Hdf5TreeModel.__del__ of <silx.gui.hdf5.Hdf5
TreeModel.Hdf5TreeModel object at 0x00000000049D1948>>
Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\silx\gui\hdf5\Hdf5TreeModel.
py", line 242, in __del__
  File "c:\program files\python36\lib\site-packages\silx\gui\hdf5\Hdf5TreeModel.
py", line 256, in _closeOpened
  File "c:\program files\python36\lib\site-packages\h5py\_hl\files.py", line 330
, in close
TypeError: bad operand type for unary ~: 'NoneType'
```

**Comment by vallsv** [comment]
Result with an EDF file
```
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\silx\gui\hdf5\Hdf5TreeModel.py", line 243, in __del__
TypeError: super() argument 1 must be type, not None
```
