### ISSUE TITLE
[opencl] Tests fail on Windows codec and image

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#1641]
Occurred on our Windows laptop (room 270)

```
======================================================================
FAIL: test_decompress (silx.opencl.codec.test.test_byte_offset.TestByteOffset)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\opdau\Documents\valls\silx.git\build\lib.win-amd64-3.6\silx\opencl\codec\test\test_byte_offset.py", line 103, in test_decompress
    self.assertEqual(delta_cl, 0, "Checks opencl works")
AssertionError: 4400107 != 0 : Checks opencl works

======================================================================
FAIL: test_many_decompress (silx.opencl.codec.test.test_byte_offset.TestByteOffset)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\opdau\Documents\valls\silx.git\build\lib.win-amd64-3.6\silx\opencl\codec\test\test_byte_offset.py", line 135, in test_many_decompress
    self.assertEqual(delta_cl, 0, "Checks opencl works")
AssertionError: 552851 != 0 : Checks opencl works

======================================================================
FAIL: test_histogram (silx.opencl.test.test_image.TestImage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\opdau\Documents\valls\silx.git\build\lib.win-amd64-3.6\silx\opencl\test\test_image.py", line 125, in test_histogram
    self.assertLessEqual(abs(deltap).max(), 2e-5, "errors on position are small: %s" % (abs(deltap).max()))
AssertionError: 2.1003274355280155e-05 not less than or equal to 2e-05 : errors on position are small: 2.1003274355280155e-05
```
Here is the context used
```
<pyopencl.Context at 0x1e335bd40b0 on <pyopencl.Device 'Iceland' on 'AMD Accelerated Parallel Processing' at 0x1e336611930>>
```

**Comment by kif** [comment]
After much debugging ...
There is actually a discrete AMD GPU on this computer, it has 6 cores of 256 work items in a WG.
The bug is apparently in in scan kernel as everything looks fine just before. 


@inducer Did you here about such problems with the scan kernel on this platform ?
https://github.com/silx-kit/silx/blob/master/silx/opencl/codec/byte_offset.py#L119

**Comment by inducer** [comment]
Is this with the ROCm driver stack or the fglrx driver stack? fglrx towards the end was so broken that I stopped paying attention. ROCm is actually pretty decent, though. You could always try `test_algorithm.py` in the PyOpenCL test suite. That stresses the scan infrastructure quite a bit, and if those pass, I'd be fairly confident that the driver works. HTH!
