### ISSUE TITLE
[sx] Test points3d function with Windows PySide Python 2.7

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#1655]
Maybe i have an old version.

```
======================================================================
ERROR: test_points3d (silx.test.test_sx.SXTest)
Test points3d function
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\opdau\Documents\valls\silx.git\build\lib.win-amd64-2.7\silx\gui\test\utils.py", line 196, in tearDown
    raise AssertionError("Exception occured in Qt thread:\n" + messages)
AssertionError: Exception occured in Qt thread:
Traceback (most recent call last):
  File "C:\Users\opdau\Documents\valls\silx.git\build\lib.win-amd64-2.7\silx\gui\plot3d\_model\items.py", line 509, in _itemAdded
    self.addRow(nodeFromItem(item), row + self._CHILDREN_ROW_OFFSET)
  File "C:\Users\opdau\Documents\valls\silx.git\build\lib.win-amd64-2.7\silx\gui\plot3d\_model\items.py", line 1369, in nodeFromItem
    node.addRow(ColormapRow(item))
  File "C:\Users\opdau\Documents\valls\silx.git\build\lib.win-amd64-2.7\silx\gui\plot3d\_model\items.py", line 731, in __init__
    StaticRow.__init__(self, ('Colormap', None))
  File "C:\Users\opdau\Documents\valls\silx.git\build\lib.win-amd64-2.7\silx\gui\plot3d\_model\core.py", line 225, in __init__
    super(StaticRow, self).__init__(children)
  File "C:\Users\opdau\Documents\valls\silx.git\build\lib.win-amd64-2.7\silx\gui\plot3d\_model\core.py", line 52, in __init__
    super(BaseRow, self).__init__()
RuntimeError: You can't initialize an object twice!
Traceback (most recent call last):
  File "C:\Users\opdau\Documents\valls\silx.git\build\lib.win-amd64-2.7\silx\gui\plot3d\_model\items.py", line 509, in _itemAdded
    self.addRow(nodeFromItem(item), row + self._CHILDREN_ROW_OFFSET)
  File "C:\Users\opdau\Documents\valls\silx.git\build\lib.win-amd64-2.7\silx\gui\plot3d\_model\items.py", line 1369, in nodeFromItem
    node.addRow(ColormapRow(item))
  File "C:\Users\opdau\Documents\valls\silx.git\build\lib.win-amd64-2.7\silx\gui\plot3d\_model\items.py", line 731, in __init__
    StaticRow.__init__(self, ('Colormap', None))
  File "C:\Users\opdau\Documents\valls\silx.git\build\lib.win-amd64-2.7\silx\gui\plot3d\_model\core.py", line 225, in __init__
    super(StaticRow, self).__init__(children)
  File "C:\Users\opdau\Documents\valls\silx.git\build\lib.win-amd64-2.7\silx\gui\plot3d\_model\core.py", line 52, in __init__
    super(BaseRow, self).__init__()
RuntimeError: You can't initialize an object twice!
Traceback (most recent call last):
  File "C:\Users\opdau\Documents\valls\silx.git\build\lib.win-amd64-2.7\silx\gui\plot3d\_model\items.py", line 509, in _itemAdded
    self.addRow(nodeFromItem(item), row + self._CHILDREN_ROW_OFFSET)
  File "C:\Users\opdau\Documents\valls\silx.git\build\lib.win-amd64-2.7\silx\gui\plot3d\_model\items.py", line 1363, in nodeFromItem
    specificInit(node, item)
  File "C:\Users\opdau\Documents\valls\silx.git\build\lib.win-amd64-2.7\silx\gui\plot3d\_model\items.py", line 1294, in initScatter2DNode
    node.addRow(ColormapRow(item))
  File "C:\Users\opdau\Documents\valls\silx.git\build\lib.win-amd64-2.7\silx\gui\plot3d\_model\items.py", line 731, in __init__
    StaticRow.__init__(self, ('Colormap', None))
  File "C:\Users\opdau\Documents\valls\silx.git\build\lib.win-amd64-2.7\silx\gui\plot3d\_model\core.py", line 225, in __init__
    super(StaticRow, self).__init__(children)
  File "C:\Users\opdau\Documents\valls\silx.git\build\lib.win-amd64-2.7\silx\gui\plot3d\_model\core.py", line 52, in __init__
    super(BaseRow, self).__init__()
RuntimeError: You can't initialize an object twice!
Traceback (most recent call last):
  File "C:\Users\opdau\Documents\valls\silx.git\build\lib.win-amd64-2.7\silx\gui\plot3d\_model\items.py", line 509, in _itemAdded
    self.addRow(nodeFromItem(item), row + self._CHILDREN_ROW_OFFSET)
  File "C:\Users\opdau\Documents\valls\silx.git\build\lib.win-amd64-2.7\silx\gui\plot3d\_model\items.py", line 1363, in nodeFromItem
    specificInit(node, item)
  File "C:\Users\opdau\Documents\valls\silx.git\build\lib.win-amd64-2.7\silx\gui\plot3d\_model\items.py", line 1294, in initScatter2DNode
    node.addRow(ColormapRow(item))
  File "C:\Users\opdau\Documents\valls\silx.git\build\lib.win-amd64-2.7\silx\gui\plot3d\_model\items.py", line 731, in __init__
    StaticRow.__init__(self, ('Colormap', None))
  File "C:\Users\opdau\Documents\valls\silx.git\build\lib.win-amd64-2.7\silx\gui\plot3d\_model\core.py", line 225, in __init__
    super(StaticRow, self).__init__(children)
  File "C:\Users\opdau\Documents\valls\silx.git\build\lib.win-amd64-2.7\silx\gui\plot3d\_model\core.py", line 52, in __init__
    super(BaseRow, self).__init__()
RuntimeError: You can't initialize an object twice!
```

**Comment by vallsv** [comment]
Here is an hackish experiment https://github.com/silx-kit/silx/commit/af56e36ab0a43ad3f119d853989b5e2743fed04e to remove `super`, and use `object` for mixins. As result the initialization sequence of `ColormapRow` is not so easy
```
-        _ColormapBaseRowMixIn.__init__(self, item)
         StaticRow.__init__(self, ('Colormap', None))
+        _ColormapBaseRowMixIn.__init__(self, item)
```

Both are not working (chicken-egg problem). This one expect to access to `flags` to feed `setFlags` at the `__init__` while this information will never be used at the execution cause `flags` is overwritten (but flags expect the mixin which is not yet implemented). That is why this patch hack the `self.flags` with a dummy lambda. A solution could be to set setFlags to None, cause this function is anyway not expected for this implementation.

The other order complain about `emit` and `connect` cause it is not yet a `QObject` with well generated signals :-)

Another solution is to drop PySide ;-)

**Comment by t20100** [comment]
I reworked it to avoid multiple inheritance, thus it is simpler and more robust.

**Comment by t20100** [comment]
Also +1 for dropping PySide ;)
