### ISSUE TITLE
[sx] contour3d test fails on Windows Python 2.7

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#1667]
SX tests fails while plot3d tests not... Any idea?

```
> python run_tests.py silx.test.test_sx.SXTest.test_contour3d --installed -v

WARNING:run_tests:resource module missing
WARNING:py.warnings:C:\Python27\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument
of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(floa
t).type`.
  from ._conv import register_converters as _register_converters

INFO:silx.setup:Use setuptools
INFO:silx.setup:Use setuptools.setup
WARNING:run_tests:Test silx 0.7.0-rc0 from C:\Python27\lib\site-packages\silx
INFO:silx.gui.test.utils:QTest.qWaitForWindowExposed not available,using QTest.qWaitForWindowShown instead.
WARNING:py.warnings:C:\Python27\lib\site-packages\glymur\config.py:153: UserWarning: Neither the openjp2 nor the openjpe
g library could be loaded.
  warnings.warn(msg)

INFO:OpenGL.acceleratesupport:No OpenGL_accelerate module loaded: No module named OpenGL_accelerate
INFO:silx.gui._glutils.OpenGLWidget:Using QGLWidget
test_contour3d (silx.test.test_sx.SXTest)
Test contour3d function ... INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Not checking attribute offsetInViewportCoords dimensions
INFO:silx.gui.plot3d.scene.primitives:Not checking attribute vertexID dimensions
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Not checking attribute offsetInViewportCoords dimensions
INFO:silx.gui.plot3d.scene.primitives:Not checking attribute vertexID dimensions
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Not checking attribute offsetInViewportCoords dimensions
INFO:silx.gui.plot3d.scene.primitives:Not checking attribute vertexID dimensions
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.ScalarFieldView:Computed iso-surface in 0.151000 s.
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
ERROR:silx.gui._glutils.OpenGLWidget:OpenGL widget disabled: OpenGL 2.1 not available
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Not checking attribute offsetInViewportCoords dimensions
INFO:silx.gui.plot3d.scene.primitives:Not checking attribute vertexID dimensions
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Not checking attribute offsetInViewportCoords dimensions
INFO:silx.gui.plot3d.scene.primitives:Not checking attribute vertexID dimensions
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Not checking attribute offsetInViewportCoords dimensions
INFO:silx.gui.plot3d.scene.primitives:Not checking attribute vertexID dimensions
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.ScalarFieldView:Computed iso-surface in 0.039000 s.
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.ScalarFieldView:Computed iso-surface in 0.149000 s.
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.ScalarFieldView:Computed iso-surface in 0.025000 s.
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
ERROR:silx.gui._glutils.OpenGLWidget:OpenGL widget disabled: OpenGL 2.1 not available
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Not checking attribute offsetInViewportCoords dimensions
INFO:silx.gui.plot3d.scene.primitives:Not checking attribute vertexID dimensions
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Not checking attribute offsetInViewportCoords dimensions
INFO:silx.gui.plot3d.scene.primitives:Not checking attribute vertexID dimensions
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Not checking attribute offsetInViewportCoords dimensions
INFO:silx.gui.plot3d.scene.primitives:Not checking attribute vertexID dimensions
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.ScalarFieldView:Computed iso-surface in 0.025000 s.
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.ScalarFieldView:Computed iso-surface in 0.021000 s.
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
ERROR:silx.gui._glutils.OpenGLWidget:OpenGL widget disabled: OpenGL 2.1 not available
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Not checking attribute offsetInViewportCoords dimensions
INFO:silx.gui.plot3d.scene.primitives:Not checking attribute vertexID dimensions
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Not checking attribute offsetInViewportCoords dimensions
INFO:silx.gui.plot3d.scene.primitives:Not checking attribute vertexID dimensions
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Not checking attribute offsetInViewportCoords dimensions
INFO:silx.gui.plot3d.scene.primitives:Not checking attribute vertexID dimensions
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.ScalarFieldView:Computed iso-surface in 0.021000 s.
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
ERROR:silx.gui._glutils.OpenGLWidget:OpenGL widget disabled: OpenGL 2.1 not available
ERROR

======================================================================
ERROR: test_contour3d (silx.test.test_sx.SXTest)
Test contour3d function
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\silx\gui\test\utils.py", line 199, in tearDown
    self._checkForUnreleasedWidgets()
  File "C:\Python27\lib\site-packages\silx\gui\test\utils.py", line 191, in _checkForUnreleasedWidgets
    "Test ended with widgets alive: %s" % str(widgets))
RuntimeError: Test ended with widgets alive: [<PyQt4.QtGui.QWidget object at 0x000000000EB84EE8>]

----------------------------------------------------------------------
Ran 1 test in 1.295s

FAILED (errors=1)
```

```
> python run_tests.py silx.gui.plot3d.test.testScalarFieldView --installed -v

WARNING:run_tests:resource module missing
WARNING:py.warnings:C:\Python27\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument
of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(floa
t).type`.
  from ._conv import register_converters as _register_converters

INFO:silx.setup:Use setuptools
INFO:silx.setup:Use setuptools.setup
WARNING:run_tests:Test silx 0.7.0-rc0 from C:\Python27\lib\site-packages\silx
INFO:silx.gui.test.utils:QTest.qWaitForWindowExposed not available,using QTest.qWaitForWindowShown instead.
WARNING:py.warnings:C:\Python27\lib\site-packages\glymur\config.py:153: UserWarning: Neither the openjp2 nor the openjpe
g library could be loaded.
  warnings.warn(msg)

INFO:OpenGL.acceleratesupport:No OpenGL_accelerate module loaded: No module named OpenGL_accelerate
INFO:silx.gui._glutils.OpenGLWidget:Using QGLWidget
testNotFinite (silx.gui.plot3d.test.testScalarFieldView.TestScalarFieldView)
Test with NaN and inf in data set ... INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Not checking attribute offsetInViewportCoords dimensions
INFO:silx.gui.plot3d.scene.primitives:Not checking attribute vertexID dimensions
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Not checking attribute offsetInViewportCoords dimensions
INFO:silx.gui.plot3d.scene.primitives:Not checking attribute vertexID dimensions
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Not checking attribute offsetInViewportCoords dimensions
INFO:silx.gui.plot3d.scene.primitives:Not checking attribute vertexID dimensions
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
ERROR:silx.gui._glutils.OpenGLWidget:OpenGL widget disabled: OpenGL 2.1 not available
INFO:silx.gui.plot3d.ScalarFieldView:Computed iso-surface in 0.010000 s.
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.ScalarFieldView:Computed iso-surface in 0.000000 s.
INFO:silx.gui.plot3d.ScalarFieldView:Computed iso-surface in 0.000000 s.
ok
testSimple (silx.gui.plot3d.test.testScalarFieldView.TestScalarFieldView)
Set the data and an isosurface ... INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Not checking attribute offsetInViewportCoords dimensions
INFO:silx.gui.plot3d.scene.primitives:Not checking attribute vertexID dimensions
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Not checking attribute offsetInViewportCoords dimensions
INFO:silx.gui.plot3d.scene.primitives:Not checking attribute vertexID dimensions
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Not checking attribute offsetInViewportCoords dimensions
INFO:silx.gui.plot3d.scene.primitives:Not checking attribute vertexID dimensions
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
ERROR:silx.gui._glutils.OpenGLWidget:OpenGL widget disabled: OpenGL 2.1 not available
INFO:silx.gui.plot3d.ScalarFieldView:Computed iso-surface in 0.003000 s.
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.ScalarFieldView:Computed iso-surface in 0.002000 s.
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
ok

----------------------------------------------------------------------
Ran 2 tests in 0.325s

OK
```

**Comment by t20100** [comment]
No, they both use the same machinery to get OpenGL context...
