### ISSUE TITLE
[dialog] Fail on interaction tests on Windows Python 3.5 / 3.6

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#1668]
Maybe due to a custom directory env + an extra simplification of the tests

```
#####################
ERROR on Windows Py35
#####################

======================================================================
FAIL: testClickOnBackToParentTool (silx.gui.dialog.test.test_imagefiledialog.TestImageFileDialogInteraction)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python35-amd64\lib\site-packages\silx\gui\dialog\test\test_imagefiledialog.py", line 279, in testClickOnBackT
oParentTool
    self.assertSamePath(url.text(), os.path.dirname(_tmpDirectory))
  File "C:\Python35-amd64\lib\site-packages\silx\gui\dialog\test\test_imagefiledialog.py", line 132, in assertSamePath
    self.assertEquals(path1, path2)
AssertionError: 'C:/Temp/silx.gui.dialog.test.test_imagefiledialog4cr9pk2b' != 'C:\\TEMP'
- C:/Temp/silx.gui.dialog.test.test_imagefiledialog4cr9pk2b
+ C:\TEMP

======================================================================
FAIL: testClickOnBackToParentTool (silx.gui.dialog.test.test_datafiledialog.TestDataFileDialogInteraction)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python35-amd64\lib\site-packages\silx\gui\dialog\test\test_datafiledialog.py", line 293, in testClickOnBackTo
ParentTool
    self.assertSamePath(url.text(), os.path.dirname(_tmpDirectory))
  File "C:\Python35-amd64\lib\site-packages\silx\gui\dialog\test\test_datafiledialog.py", line 123, in assertSamePath
    self.assertEquals(path1, path2)
AssertionError: 'C:/Temp/silx.gui.dialog.test.test_datafiledialoggaix86nt' != 'C:\\TEMP'
- C:/Temp/silx.gui.dialog.test.test_datafiledialoggaix86nt
+ C:\TEMP

#####################
ERROR on Windows Py36
#####################

FAIL: testClickOnBackToParentTool (silx.gui.dialog.test.test_imagefiledialog.TestImageFileDialogInteraction)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\silx\gui\dialog\test\test_imagefiledialog.py", line 279, in testClickOnBackToParen
tTool
    self.assertSamePath(url.text(), os.path.dirname(_tmpDirectory))
  File "C:\Python36\lib\site-packages\silx\gui\dialog\test\test_imagefiledialog.py", line 132, in assertSamePath
    self.assertEquals(path1, path2)
AssertionError: 'C:/Temp/silx.gui.dialog.test.test_imagefiledialog5xndlegm' != 'C:\\TEMP'
- C:/Temp/silx.gui.dialog.test.test_imagefiledialog5xndlegm
+ C:\TEMP
```

**Comment by vallsv** [comment]
After killing 4GB of process in the computer, it looks to be fine again...
