### ISSUE TITLE
[mask] Test failing time to time on Windows Python 3.6

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#1670]
Sometimes everything is fine, sometimes no... Any idea?
```
E:\valls\silx_release\py36>python run_tests.py --installed silx.gui.plot.test.testMaskToolsWidget.TestMaskToolsWidget
WARNING:run_tests:resource module missing
WARNING:py.warnings:C:\Python36\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument
of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(floa
t).type`.
  from ._conv import register_converters as _register_converters

INFO:silx.setup:Use setuptools
INFO:silx.setup:Use setuptools.setup
WARNING:run_tests:Test silx 0.7.0-rc0 from C:\Python36\lib\site-packages\silx
WARNING:py.warnings:C:\Python36\lib\site-packages\glymur\config.py:153: UserWarning: Neither the openjp2 nor the openjpe
g library could be loaded.
  warnings.warn(msg)

WARNING:py.warnings:C:\Python36\lib\site-packages\IPython\qt.py:13: ShimWarning: The `IPython.qt` package has been depre
cated since IPython 4.0. You should import from qtconsole instead.
  "You should import from qtconsole instead.", ShimWarning)

....
======================================================================
FAIL: testWithAnImage (silx.gui.plot.test.testMaskToolsWidget.TestMaskToolsWidget) (origin=(1000, 1000), scale=(1, 1))
Plot with an image: test MaskToolsWidget interactions
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\silx\gui\plot\test\testMaskToolsWidget.py", line 215, in testWithAnImage
    numpy.all(numpy.equal(self.maskWidget.getSelectionMask(), 0)))
AssertionError: False is not true

======================================================================
FAIL: testWithAnImage (silx.gui.plot.test.testMaskToolsWidget.TestMaskToolsWidget) (origin=(0, 0), scale=(-1, -1))
Plot with an image: test MaskToolsWidget interactions
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\silx\gui\plot\test\testMaskToolsWidget.py", line 174, in testWithAnImage
    numpy.all(numpy.equal(self.maskWidget.getSelectionMask(), 0)))
AssertionError: False is not true

======================================================================
FAIL: testWithAnImage (silx.gui.plot.test.testMaskToolsWidget.TestMaskToolsWidget) (origin=(1000, 1000), scale=(-1, -1))

Plot with an image: test MaskToolsWidget interactions
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\silx\gui\plot\test\testMaskToolsWidget.py", line 174, in testWithAnImage
    numpy.all(numpy.equal(self.maskWidget.getSelectionMask(), 0)))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 5 tests in 8.646s

FAILED (failures=3)

E:\valls\silx_release\py36>
E:\valls\silx_release\py36>
E:\valls\silx_release\py36>pip list --format=columns
Package          Version
---------------- -----------
appdirs          1.4.3
cffi             1.10.0
colorama         0.3.9
cycler           0.10.0
Cython           0.26.1
decorator        4.1.2
fabio            0.6.0
Glymur           0.8.11
h5py             2.7.1
ipython          6.2.1
ipython-genutils 0.2.0
jedi             0.11.0
Mako             1.0.7
MarkupSafe       1.0
matplotlib       2.1.2
numexpr          2.6.4
numpy            1.14.1
olefile          0.44
packaging        16.8
parso            0.1.0
pickleshare      0.7.4
Pillow           5.0.0
pip              9.0.1
prompt-toolkit   1.0.15
py               1.4.34
pycparser        2.18
pyFAI            0.15.0
Pygments         2.2.0
pyopencl         2017.2+cl12
PyOpenGL         3.1.0
pyparsing        2.2.0
PyQt5            5.10
PySide2          5.6
pytest           3.1.3
python-dateutil  2.6.1
pytools          2017.3
pytz             2018.3
scipy            1.0.0
setuptools       38.4.0
silx             0.7.0b0
simplegeneric    0.8.1
sip              4.19.7
six              1.11.0
traitlets        4.3.2
wcwidth          0.1.7
wheel            0.30.0
wxPython         4.0.0b2
```

**Comment by vallsv** [comment]
The same on Python 3.5. And look how there is not `F` in the processing...
```
E:\valls\silx_release\py35>python run_tests.py --installed
WARNING:run_tests:resource module missing
WARNING:py.warnings:C:\Python35-amd64\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second arg
ument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtyp
e(float).type`.
  from ._conv import register_converters as _register_converters

INFO:silx.setup:Use setuptools
INFO:silx.setup:Use setuptools.setup
WARNING:run_tests:Test silx 0.7.0-rc0 from C:\Python35-amd64\lib\site-packages\silx
WARNING:py.warnings:C:\Python35-amd64\lib\site-packages\glymur\config.py:153: UserWarning: Neither the openjp2 nor the o
penjpeg library could be loaded.
  warnings.warn(msg)

WARNING:silx.opencl.sift.test.test_matching:feature module is not available to compare results with C++ implementation.
Matching cannot be tested.
........................................................................................................................
..............................................................s.........................................................
..........................................................s.............................................................
.......s.....................................................................QFileSystemWatcher: FindNextChangeNotificat
ion failed for "C:\Temp\silx.gui.dialog.test.test_imagefiledialog1f8cvs7l\dir"  (Access is denied.)
............................QFileSystemWatcher: FindNextChangeNotification failed for "C:\Temp\silx.gui.dialog.test.test
_datafiledialog3xdjw7g_\dir"  (Access is denied.)
........................................................................................................................
..................................................................................s.....................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................
======================================================================
FAIL: testWithAnImage (silx.gui.plot.test.testMaskToolsWidget.TestMaskToolsWidget) (origin=(0, 0), scale=(1, 1))
Plot with an image: test MaskToolsWidget interactions
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python35-amd64\lib\site-packages\silx\gui\plot\test\testMaskToolsWidget.py", line 215, in testWithAnImage
    numpy.all(numpy.equal(self.maskWidget.getSelectionMask(), 0)))
AssertionError: False is not true

======================================================================
FAIL: testWithAnImage (silx.gui.plot.test.testMaskToolsWidget.TestMaskToolsWidget) (origin=(1000, 1000), scale=(1, 1))
Plot with an image: test MaskToolsWidget interactions
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python35-amd64\lib\site-packages\silx\gui\plot\test\testMaskToolsWidget.py", line 174, in testWithAnImage
    numpy.all(numpy.equal(self.maskWidget.getSelectionMask(), 0)))
AssertionError: False is not true

======================================================================
FAIL: testWithAnImage (silx.gui.plot.test.testMaskToolsWidget.TestMaskToolsWidget) (origin=(0, 0), scale=(-1, -1))
Plot with an image: test MaskToolsWidget interactions
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python35-amd64\lib\site-packages\silx\gui\plot\test\testMaskToolsWidget.py", line 174, in testWithAnImage
    numpy.all(numpy.equal(self.maskWidget.getSelectionMask(), 0)))
AssertionError: False is not true

======================================================================
FAIL: testWithAnImage (silx.gui.plot.test.testMaskToolsWidget.TestMaskToolsWidget) (origin=(1000, 1000), scale=(-1, -1))

Plot with an image: test MaskToolsWidget interactions
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python35-amd64\lib\site-packages\silx\gui\plot\test\testMaskToolsWidget.py", line 174, in testWithAnImage
    numpy.all(numpy.equal(self.maskWidget.getSelectionMask(), 0)))
AssertionError: False is not true

======================================================================
SKIPPED: testAxisDestruction (silx.gui.plot.test.testUtilsAxis.TestAxisSync)
Test synchronization when an axis disappear
----------------------------------------------------------------------
Object not destroyed
======================================================================
SKIPPED: testMovieIconExists (silx.gui.test.test_icons.TestAnimatedIcons)
----------------------------------------------------------------------
MNG not supported
======================================================================
SKIPPED: testCubeWithComplex (silx.gui.data.test.test_dataviewer.TestDataView)
----------------------------------------------------------------------
OpenGL widget not yet tested
======================================================================
SKIPPED: test_locale_de_DE (silx.io.test.test_specfile.TestSFLocale)
----------------------------------------------------------------------
de_DE.utf8 locale not installed
----------------------------------------------------------------------
Ran 1394 tests in 190.551s

FAILED (failures=4, skipped=4)
```

And testing `silx.gui.plot.test.testMaskToolsWidget.TestMaskToolsWidget` alone many times looks to be fine.

**Comment by vallsv** [comment]
It looks like the problem come from the sidebar. This part of the GUI displays icons and uses `QFileInfo`. But it is very difficult to log or to check.

**Comment by vallsv** [comment]
As result we consider that the mask tool feature is working.
Tests on matplotlib are just difficult to fix.
