### ISSUE TITLE
[plot3d] Unreleased widget with tests of sx.contour3d

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#1699]
On Windows Python 2.7 (without using rdesktop).

```
ERROR: test_contour3d (silx.test.test_sx.SXTest)
Test contour3d function
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\silx\gui\test\utils.py", line 200, in tearDown
    self._checkForUnreleasedWidgets()
  File "C:\Python27\lib\site-packages\silx\gui\test\utils.py", line 192, in _checkForUnreleasedWidgets
    "Test ended with widgets alive: %s" % str(widgets))
RuntimeError: Test ended with widgets alive: [<PyQt4.QtGui.QWidget object at 0x0000000016610798>]
```

**Comment by vallsv** [comment]
I spend some times to fix it without success.

It should be fixed when we will use the new tree from @t20100.

**Comment by t20100** [comment]
I'll have a look at it, but final solution will be to use the new tree

**Comment by t20100** [comment]
Nothing appears on appveyor because OpenGL tests are skipped for PyQt4....

**Comment by vallsv** [comment]
Hehehe :-)
