### ISSUE TITLE
[test] Test on rnice/py3 segfault with 0.7.0

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#1719]
Maybe that's a pbm with my local env... silx view looks to work well.

```
$ python3.4 -m silx test -v
INFO:silx.app.test_:Set log level: INFO
INFO:silx.gui.test.utils:QTest.qWaitForWindowExposed not available,using QTest.qWaitForWindowShown instead.
INFO:OpenGL.acceleratesupport:No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
INFO:OpenGL.formathandler:Unable to load registered array format handler numeric:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/OpenGL/arrays/numeric.py", line 13, in <module>
    import Numeric
ImportError: No module named 'Numeric'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/OpenGL/arrays/formathandler.py", line 35, in loadPlugin
    plugin_class = entrypoint.load()
  File "/usr/lib/python3/dist-packages/OpenGL/plugins.py", line 14, in load
    return importByName( self.import_path )
  File "/usr/lib/python3/dist-packages/OpenGL/plugins.py", line 28, in importByName
    module = __import__( ".".join(moduleName), {}, {}, moduleName)
  File "/usr/lib/python3/dist-packages/OpenGL/arrays/numeric.py", line 15, in <module>
    raise ImportError( """No Numeric module present: %s"""%(err))
ImportError: No Numeric module present: No module named 'Numeric'

INFO:OpenGL.formathandler:Unable to load registered array format handler vbo:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/OpenGL/arrays/formathandler.py", line 35, in loadPlugin
    plugin_class = entrypoint.load()
  File "/usr/lib/python3/dist-packages/OpenGL/plugins.py", line 14, in load
    return importByName( self.import_path )
  File "/usr/lib/python3/dist-packages/OpenGL/plugins.py", line 28, in importByName
    module = __import__( ".".join(moduleName), {}, {}, moduleName)
  File "/usr/lib/python3/dist-packages/OpenGL/arrays/vbo.py", line 33, in <module>
    from OpenGL import GL
ImportError: cannot import name 'GL'

INFO:OpenGL.formathandler:Unable to load registered array format handler vbooffset:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/OpenGL/arrays/formathandler.py", line 35, in loadPlugin
    plugin_class = entrypoint.load()
  File "/usr/lib/python3/dist-packages/OpenGL/plugins.py", line 14, in load
    return importByName( self.import_path )
  File "/usr/lib/python3/dist-packages/OpenGL/plugins.py", line 28, in importByName
    module = __import__( ".".join(moduleName), {}, {}, moduleName)
  File "/usr/lib/python3/dist-packages/OpenGL/arrays/vbo.py", line 33, in <module>
    from OpenGL import GL
ImportError: cannot import name 'GL'

INFO:silx.gui._glutils.OpenGLWidget:Using QGLWidget
WARNING:silx.opencl.projection:Forward Projecter is untested and unsuported for now
WARNING:silx.opencl.sift.test.test_matching:feature module is not available to compare results with C++ implementation. Matching cannot be tested.
test_contour3d (silx.test.test_sx.SXTest)
Test contour3d function ... libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
X Error: GLXBadContext 169
  Extension:    155 (Uknown extension)
  Minor opcode: 6 (Unknown request)
  Resource id:  0x3000008
X Error: BadValue (integer parameter out of range for operation) 2
  Extension:    155 (Uknown extension)
  Minor opcode: 3 (Unknown request)
  Resource id:  0x0
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to int32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Not checking attribute vertexID dimensions
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Not checking attribute offsetInViewportCoords dimensions
INFO:silx.gui.plot3d.scene.primitives:Not checking attribute vertexID dimensions
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Not checking attribute offsetInViewportCoords dimensions
INFO:silx.gui.plot3d.scene.primitives:Not checking attribute vertexID dimensions
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Not checking attribute offsetInViewportCoords dimensions
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.ScalarFieldView:Computed iso-surface in 0.141760 s.
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
X Error: GLXBadContext 169
  Extension:    155 (Uknown extension)
  Minor opcode: 5 (Unknown request)
  Resource id:  0x3000008
X Error: 0 0
  Extension:    155 (Uknown extension)
  Minor opcode: 26 (Unknown request)
  Resource id:  0x0
QGLContext::makeCurrent(): Failed.
X Error: GLXBadContext 169
  Extension:    155 (Uknown extension)
  Minor opcode: 5 (Unknown request)
  Resource id:  0x3000008
X Error: 0 0
  Extension:    155 (Uknown extension)
  Minor opcode: 26 (Unknown request)
  Resource id:  0x0
QGLContext::makeCurrent(): Failed.
X Error: BadValue (integer parameter out of range for operation) 2
  Extension:    155 (Uknown extension)
  Minor opcode: 3 (Unknown request)
  Resource id:  0x0
X Error: GLXBadContext 169
  Extension:    155 (Uknown extension)
  Minor opcode: 5 (Unknown request)
  Resource id:  0x3000017
X Error: 0 0
  Extension:    155 (Uknown extension)
  Minor opcode: 26 (Unknown request)
  Resource id:  0x0
QGLTempContext: Unable to create GL context.
ERROR:silx.gui._glutils.OpenGLWidget:OpenGL not available: If connected remotely, GLX forwarding might be disabled.
X Error: GLXBadContext 169
  Extension:    155 (Uknown extension)
  Minor opcode: 4 (Unknown request)
  Resource id:  0x3000008
skipped 'OpenGL context is not valid'
test_ginput (silx.test.test_sx.SXTest)
Test ginput function ... INFO:silx.sx._plot:Performing ginput with plot widget <silx.gui.plot.PlotWindow.Plot1D object at 0x7fda36c7faf8>
ok
test_imshow (silx.test.test_sx.SXTest)
Test imshow function ... ok
test_plot (silx.test.test_sx.SXTest)
Test plot function ... ok
test_points3d (silx.test.test_sx.SXTest)
Test points3d function ... X Error: GLXBadContext 169
  Extension:    155 (Uknown extension)
  Minor opcode: 6 (Unknown request)
  Resource id:  0x30000de
X Error: BadValue (integer parameter out of range for operation) 2
  Extension:    155 (Uknown extension)
  Minor opcode: 3 (Unknown request)
  Resource id:  0x0
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to int32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Not checking attribute vertexID dimensions
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Not checking attribute offsetInViewportCoords dimensions
INFO:silx.gui.plot3d.scene.primitives:Not checking attribute vertexID dimensions
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Not checking attribute offsetInViewportCoords dimensions
INFO:silx.gui.plot3d.scene.primitives:Not checking attribute vertexID dimensions
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Not checking attribute offsetInViewportCoords dimensions
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
INFO:silx.gui.plot3d.scene.primitives:Cast array to float32
X Error: GLXBadContext 169
  Extension:    155 (Uknown extension)
  Minor opcode: 5 (Unknown request)
  Resource id:  0x30000de
X Error: 0 0
  Extension:    155 (Uknown extension)
  Minor opcode: 26 (Unknown request)
  Resource id:  0x0
QGLContext::makeCurrent(): Failed.
X Error: GLXBadContext 169
  Extension:    155 (Uknown extension)
  Minor opcode: 5 (Unknown request)
  Resource id:  0x30000de
X Error: 0 0
  Extension:    155 (Uknown extension)
  Minor opcode: 26 (Unknown request)
  Resource id:  0x0
QGLContext::makeCurrent(): Failed.
ERROR:silx.gui._glutils.OpenGLWidget:OpenGL not available: If connected remotely, GLX forwarding might be disabled.
X Error: GLXBadContext 169
  Extension:    155 (Uknown extension)
  Minor opcode: 4 (Unknown request)
  Resource id:  0x30000de
skipped 'OpenGL context is not valid'
testQObject (silx.gui.test.test_qt.TestQtWrapper)
Test that QObject is there. ... ok
testLoadUi (silx.gui.test.test_qt.TestLoadUi)
Create a QMainWindow from an ui file ... ok
testNiceNumbers (silx.gui.plot._utils.test.test_ticklayout.TestTickLayout)
Minimalistic tests of :func:`niceNumbers` ... ok
testNiceNumbersLog (silx.gui.plot._utils.test.test_ticklayout.TestTickLayout)
Minimalistic tests of :func:`niceNumbersForLog10` ... ok
testTicks (silx.gui.plot._utils.test.test_ticklayout.TestTickLayout)
Test of :func:`ticks` ... ok
testNoColormap (silx.gui.plot.test.testColorBar.TestColorScale)
Test _ColorScale without a colormap ... ok
testRelativePositionLinear (silx.gui.plot.test.testColorBar.TestColorScale) ... ok
testRelativePositionLog (silx.gui.plot.test.testColorBar.TestColorScale) ... ok
testLinearNormNoAutoscale (silx.gui.plot.test.testColorBar.TestNoAutoscale) ... ok
testLogNormNoAutoscale (silx.gui.plot.test.testColorBar.TestNoAutoscale) ... ok
testColormapWithoutRange (silx.gui.plot.test.testColorBar.TestColorBarWidget)
Test with a colormap with vmin==vmax ... ok
testEmptyColorBar (silx.gui.plot.test.testColorBar.TestColorBarWidget) ... ok
testNegativeColormaps (silx.gui.plot.test.testColorBar.TestColorBarWidget)
test the behavior of the ColorBarWidget in the case of negative ... ok
testPlotAssocation (silx.gui.plot.test.testColorBar.TestColorBarWidget)
Make sure the ColorBarWidget is properly connected with the plot ... ok
testUpdateColorMap (silx.gui.plot.test.testColorBar.TestColorBarUpdate) ... ok
testRGBA (silx.gui.plot.test.testColors.TestRGBA)
"Test rgba function with accepted values ... ok
testApplyColormapToData (silx.gui.plot.test.testColors.TestApplyColormapToData)
Simple test of applyColormapToData function ... ok
ColormapDialog (silx.gui.plot)
Doctest: silx.gui.plot.ColormapDialog ... Segmentation fault
```

**Comment by t20100** [comment]
`WITH_GL_TEST=False python3 -m silx test -v` makes it works.
It's probably related to the fact that OpenGL forwarding is disabled in your environment...
It should not segfault though....
