### ISSUE TITLE
[console] compatibility problem with silx.gui.qt binding

### ISSUE THREAD

**Issue by PiRK** [silx-kit/silx#1732]
This  works:
```
>>> import PyQt5
>>> from qtconsole.rich_ipython_widget import RichJupyterWidget
>>> 
```

This works too:
```
>>> import PyQt4
>>> from qtconsole.rich_ipython_widget import RichJupyterWidget
```

But this does not work:
```
>>> from silx.gui import qt
>>> from qtconsole.rich_ipython_widget import RichJupyterWidget
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/users/knobel/.local/lib/python2.7/site-packages/qtconsole/rich_ipython_widget.py", line 3, in <module>
    from .rich_jupyter_widget import *
  File "/users/knobel/.local/lib/python2.7/site-packages/qtconsole/rich_jupyter_widget.py", line 9, in <module>
    from qtconsole.qt import QtCore, QtGui
  File "/users/knobel/.local/lib/python2.7/site-packages/qtconsole/qt.py", line 23, in <module>
    QtCore, QtGui, QtSvg, QT_API = load_qt(api_opts)
  File "/users/knobel/.local/lib/python2.7/site-packages/qtconsole/qt_loaders.py", line 386, in load_qt
    api_options))
ImportError: 
    Could not load requested Qt binding. Please ensure that
    PyQt4 >= 4.7, PyQt5, PySide >= 1.0.3 or PySide2 is available,
    and only one is imported per session.

    Currently-imported Qt library:   'pyqt5'
    PyQt4 installed:                 True
    PyQt5 installed:                 False
    PySide >= 1.0.3 installed:       False
    PySide2 installed:               False
    Tried to load:                   ['pyqt5']
```

As an indirect result, I get an error when I try to import `silx.gui.console` because it tries an import which I apparently never tested:

```
>>> import silx.gui.console
/users/knobel/.local/lib/python2.7/site-packages/IPython/qt.py:13: ShimWarning: The `IPython.qt` package has been deprecated since IPython 4.0. You should import from qtconsole instead.
  "You should import from qtconsole instead.", ShimWarning)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/users/knobel/.local/lib/python2.7/site-packages/silx/gui/console.py", line 135, in <module>
    from IPython.qt.console.rich_ipython_widget import RichIPythonWidget
ImportError: No module named rich_ipython_widget

```

**Comment by t20100** [comment]
Depending on version used, it might be related to PR #1686: change of Qt binding order

**Comment by t20100** [comment]
@PiRK do you still have the issue since we clean-up the console module from "old" IPython support?

**Comment by t20100** [comment]
@PiRK can this be closed?

**Comment by PiRK** [comment]
No, it seems to be working fine now.
