### ISSUE TITLE
How to use the code that I check out from github.

### ISSUE THREAD

**Issue by titusjan** [silx-kit/silx#1735]
Dear all.

I've cloned the `silx` repo from github and am trying to import it, so that I can make changes to the source (and potentially submit pull requests back to you).

I have cloned the `silx` repository into my `src/extern` directory and added that directory to the `PYTHONPATH`. When I then try to `import silx` I get the following message:

```
~/src/pruts/trysilx> python -c 'import silx'
Traceback (most recent call last):
  File "/home/pepijnk/src/extern/silx/silx/__init__.py", line 43, in <module>
    from ._version import __date__ as date  # noqa
ImportError: No module named 'silx._version'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/pepijnk/src/extern/silx/silx/__init__.py", line 46, in <module>
    raise RuntimeError("Do NOT use %s from its sources: build it and use the built version" % project)
RuntimeError: Do NOT use silx from its sources: build it and use the built version
```

This seems clear enough, I should first build the code, but it is not clear to me how to do this exactly. I have read the detailed [installation steps](http://www.silx.org/doc/silx/dev/install.html#building-from-source). However, it only describes how to install from source (with `pip install`). I can't imaging that I have to do  an install every time I modify something to the `silx` library. I would expect a makefile or something similar. 

I did find the `bootstrap.py` file but I couldn't get it to work because it uses my Python 2 interpreter.

So, my question is: how do you use use the `silx` library during library development?

**Comment by payno** [comment]
> python3 bootstrap.py

should work for you.
Is it what you needed ?

**Comment by PiRK** [comment]
We work a lot with `bootstrap.py`. You can put some code in a script and run `python bootstrap.py yourscript.py`. This will run your script with the development version of *silx* after building it.

The other alternative is to uninstall and reinstall after each change, which is not that long. Only the first build will take some time, to build the compiled extensions. `cd repository;  pip uninstall silx; pip install . --user`

In any case, you should not add the repository to `PYTHONPATH`. It cannot work because of the missing compiled extensions.

**Comment by t20100** [comment]
`silx` has some C/C++/Cython extensions that needs to be compiled before being used, so you cannot use `silx` from the source directory directly, it needs to be built first.

The `bootstrap.py` script is building the project and modifies `sys.path` to add `build/lib-*` directory so it's using the fresh built `silx` package.

Alternatively, if you work on code that does not need to be compiled, you can install `silx` in development mode with: `pip install . -e [--user]` See https://pip.pypa.io/en/stable/reference/pip_install/#editable-installs

**Comment by titusjan** [comment]
Thank you both for your quick replies. The `pip -e` development mode install looks promising. I can't test it before Tuesday, but I'll let you know then.

**Comment by titusjan** [comment]
The `python3 bootstrap.py myscript.py` variant works, so I can get started. Thanks.

However I still prefer to install it with `pip -e`, which will make it easier to run it from PyCharm. I get the following error when I try it.

```
~/src/pruts/trysilx> pip3 install --user  -e /home/pepijnk/src/extern/silx
Obtaining file:///home/pepijnk/src/extern/silx
Collecting numpy (from silx==0.8.0a0)
  Using cached numpy-1.14.2-cp35-cp35m-manylinux1_x86_64.whl
Collecting setuptools (from silx==0.8.0a0)
  Using cached setuptools-39.0.1-py2.py3-none-any.whl
Installing collected packages: numpy, setuptools, silx
  Running setup.py develop for silx
    Complete output from command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/home/pepijnk/src/extern/silx/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps --user --prefix=:
    INFO:root:Generating grammar tables from /usr/lib/python3.5/lib2to3/Grammar.txt
    INFO:root:Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
    INFO:silx.setup:Use setuptools
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help
    
    error: option --user not recognized
    silx.io.specfile WARNING:
    A cleaner locale independent implementation
    may be achieved setting SPECFILE_USE_GNU_SOURCE to 1
    For instance running this script as:
    SPECFILE_USE_GNU_SOURCE=1 python setup.py build
    
    ----------------------------------------
Command "/usr/bin/python3 -c "import setuptools, tokenize;__file__='/home/pepijnk/src/extern/silx/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps --user --prefix=" failed with error code 1 in /home/pepijnk/src/extern/silx/

```
Using the same pip command without `--user` gives the same error. I believe that Debian uses `--user` automatically when you're not root.

Any help would be appreciated.

**Comment by t20100** [comment]
No particular idea, I don't have issue on both debian 8 and 9.
You can try to install it in a virtualenv (http://www.silx.org/doc/silx/latest/install.html#virtual-environment) where you can update `pip` independently of your system.

**Comment by t20100** [comment]
Not related to `--user` issue, but `pip -e` does not work out of the box with silx (I've used it with another project).
For `silx`, you need to copy `version.py` to `silx/_version.py` to make it work (this copy is usually done during installation, it's the way we use to check whether silx is imported from source or from installed path).

**Comment by vallsv** [comment]
Hi, is this issue is still alive?

**Comment by titusjan** [comment]
Not for me. I use the `boostrap.py` script now. I've added it as an _interpreter option_ in PyCharm so that I can use it from my IDE.
