### ISSUE TITLE
[masktool] Test fail on Windows Python3.6 PyQt5

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#1911]
Tested on our Windows computer

```
E:\valls\silx>python run_tests.py silx.gui.plot.test.testMaskToolsWidget.suite
```

```
======================================================================
FAIL: testWithAnImage (silx.gui.plot.test.testMaskToolsWidget.TestMaskToolsWidget) (origin=(0, 0), scale=(1, 1))
Plot with an image: test MaskToolsWidget interactions
----------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\valls\silx\build\lib.win-amd64-3.6\silx\gui\plot\test\testMaskToolsWidget.py", line 215, in testWithAnImage
    numpy.all(numpy.equal(self.maskWidget.getSelectionMask(), 0)))
AssertionError: False is not true

======================================================================
FAIL: testWithAnImage (silx.gui.plot.test.testMaskToolsWidget.TestMaskToolsWidget) (origin=(1000, 1000), scale=(1, 1))
Plot with an image: test MaskToolsWidget interactions
----------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\valls\silx\build\lib.win-amd64-3.6\silx\gui\plot\test\testMaskToolsWidget.py", line 174, in testWithAnImage
    numpy.all(numpy.equal(self.maskWidget.getSelectionMask(), 0)))
AssertionError: False is not true

======================================================================
FAIL: testWithAnImage (silx.gui.plot.test.testMaskToolsWidget.TestMaskToolsWidget) (origin=(0, 0), scale=(-1, -1))
Plot with an image: test MaskToolsWidget interactions
----------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\valls\silx\build\lib.win-amd64-3.6\silx\gui\plot\test\testMaskToolsWidget.py", line 174, in testWithAnImage
    numpy.all(numpy.equal(self.maskWidget.getSelectionMask(), 0)))
AssertionError: False is not true

======================================================================
FAIL: testWithAnImage (silx.gui.plot.test.testMaskToolsWidget.TestMaskToolsWidget) (origin=(1000, 1000), scale=(-1, -1))

Plot with an image: test MaskToolsWidget interactions
----------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\valls\silx\build\lib.win-amd64-3.6\silx\gui\plot\test\testMaskToolsWidget.py", line 174, in testWithAnImage
    numpy.all(numpy.equal(self.maskWidget.getSelectionMask(), 0)))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 5 tests in 7.338s

FAILED (failures=4)
```

**Comment by vallsv** [comment]
It looks to be random

**Comment by t20100** [comment]
closing as not reproduced during release, reopen if needed
