### ISSUE TITLE
Issue with scipy

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#1953]
Blocking problem on the continuous integration.

```
Traceback (most recent call last):
  File "run_tests.py", line 473, in <module>
    unittest.defaultTestLoader.loadTestsFromNames(options.test_name))
  File "c:\python27-x64\Lib\unittest\loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "c:\python27-x64\Lib\unittest\loader.py", line 115, in loadTestsFromName
    test = obj()
  File "C:\projects\silx\venv_test\lib\site-packages\silx\test\__init__.py", line 86, in suite
    test_suite.addTest(test_ocl.suite())
  File "C:\projects\silx\venv_test\lib\site-packages\silx\opencl\test\__init__.py", line 54, in suite
    from ..sift import test as test_sift
  File "C:\projects\silx\venv_test\lib\site-packages\silx\opencl\sift\test\__init__.py", line 30, in <module>
    from . import test_gaussian
  File "C:\projects\silx\venv_test\lib\site-packages\silx\opencl\sift\test\test_gaussian.py", line 53, in <module>
    import scipy.misc, scipy.ndimage
  File "C:\projects\silx\venv_test\lib\site-packages\scipy\misc\__init__.py", line 64, in <module>
    from . import doccer
ImportError: cannot import name doccer
```

**Comment by vallsv** [comment]
Looks to be transitional.

**Comment by vallsv** [comment]
Well it is still a problem on CI. Not on our windows machine.
I will patch tests to remove scipy dependency.
