### ISSUE TITLE
[scatterview] Master tests fail on Appveyor

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#1958]
```
======================================================================
ERROR: test (silx.gui.plot.test.testScatterView.TestScatterView)
Simple tests
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\silx\venv_test\lib\site-packages\silx\gui\plot\test\utils.py", line 94, in tearDown
    super(PlotWidgetTestCase, self).tearDown()
  File "C:\projects\silx\venv_test\lib\site-packages\silx\gui\test\utils.py", line 197, in tearDown
    raise AssertionError("Exception occured in Qt thread:\n" + messages)
AssertionError: Exception occured in Qt thread:
Traceback (most recent call last):
  File "C:\projects\silx\venv_test\lib\site-packages\silx\gui\plot\ScatterMaskToolsWidget.py", line 336, in _activeScatterChanged
    xMin, xMax = min_max(self._data_scatter.getXData(copy=False))
  File "silx\math\combo.pyx", line 329, in silx.math.combo.min_max
    return _min_max(data, min_positive)
  File "silx\math\combo.pyx", line 134, in silx.math.combo._min_max
    raise ValueError('Zero-size array')
ValueError: Zero-size array
```

**Comment by vallsv** [comment]
Was an issue from a branch, not the master.

PR #1960 fixes the URL links to the right logs
