### ISSUE TITLE
print preview: Issue when no printer defined

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#1987]
On macOS, python2.7, pyqt4, with no printer defined in the system, the printPreview.py example leads to the following issue:

```
Traceback (most recent call last):
  File "/Users/tvincent/silx0.8/lib/python2.7/site-packages/silx/gui/plot/PrintPreviewToolButton.py", line 181, in _plotToPrintPreview
    svgRenderer, viewBox = self._getSvgRendererAndViewbox()
  File "/Users/tvincent/silx0.8/lib/python2.7/site-packages/silx/gui/plot/PrintPreviewToolButton.py", line 211, in _getSvgRendererAndViewbox
    viewbox = self._getViewBox()
  File "/Users/tvincent/silx0.8/lib/python2.7/site-packages/silx/gui/plot/PrintPreviewToolButton.py", line 231, in _getViewBox
    dpix = printer.logicalDpiX()
AttributeError: 'NoneType' object has no attribute 'logicalDpiX'
```

**Comment by payno** [comment]
Python 2.7 is no more supported. Let's clean this issue
