### ISSUE TITLE
[debian][0.8.0] doc generation issues

### ISSUE THREAD

**Issue by picca** [silx-kit/silx#2057]
Hello while preparing the Debian package of 0.8.0, I get these error mesage during the doc generation.

the sift module issue can be forgot since it is not build on Debian.
but I do not know how to deal with the pytools problem whcih try to create a directory in the HOME dir.
which does not exist during the Debian build process.

The silx.sx module problem is also strange.

Cheers

Frederic

```
reading sources... [100%] virtualenv

/usr/lib/python3/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/<<BUILDDIR>>/silx-0.8.0+dfsg/doc/source/developers.rst:95: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/<<BUILDDIR>>/silx-0.8.0+dfsg/doc/source/developers.rst:7: WARNING: Unknown target name: "github flow<https://guides.github.com/introduction/flow/>".
/<<BUILDDIR>>/silx-0.8.0+dfsg/doc/source/developers.rst:7: WARNING: Unknown target name: "scikit-image contribution documentation<http://scikit-image.org/docs/stable/contribute.html#development-process>".
/<<BUILDDIR>>/silx-0.8.0+dfsg/doc/source/developers.rst:13: WARNING: Unknown target name: "scikit-image guidelines<http://scikit-image.org/docs/stable/contribute.html#guidelines>".
/<<BUILDDIR>>/silx-0.8.0+dfsg/doc/source/developers.rst:18: WARNING: Unknown target name: "pep 8<https://www.python.org/dev/peps/pep-0008/>".
/<<BUILDDIR>>/silx-0.8.0+dfsg/doc/source/developers.rst:37: WARNING: Unknown target name: "scikit-image coordinate conventions<http://scikit-image.org/docs/stable/user_guide/numpy_images.html#numpy-images-coordinate-conventions>".
WARNING: autodoc: failed to import module 'silx.image.sift'; the following exception was raised:
No module named 'silx.opencl.sift'
WARNING: autodoc: failed to import module 'silx.opencl.codec.byte_offset'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/ext/autodoc/importer.py", line 152, in import_module
    __import__(modname)
  File "/<<BUILDDIR>>/silx-0.8.0+dfsg/.pybuild/cpython3_3.6_silx/build/silx/opencl/codec/byte_offset.py", line 58, in <module>
    from pyopencl.algorithm import GenericScanKernel
  File "/usr/lib/python3/dist-packages/pyopencl/algorithm.py", line 37, in <module>
    from pyopencl.scan import ScanTemplate
  File "/usr/lib/python3/dist-packages/pyopencl/scan.py", line 1137, in <module>
    key_builder=_NumpyTypesKeyBuilder())
  File "/usr/lib/python3/dist-packages/pytools/persistent_dict.py", line 566, in __init__
    _PersistentDictBase.__init__(self, identifier, key_builder, container_dir)
  File "/usr/lib/python3/dist-packages/pytools/persistent_dict.py", line 463, in __init__
    self._make_container_dir()
  File "/usr/lib/python3/dist-packages/pytools/persistent_dict.py", line 97, in wrapper
    return f(obj, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/pytools/persistent_dict.py", line 505, in _make_container_dir
    _make_dir_recursively(self.container_dir)
  File "/usr/lib/python3/dist-packages/pytools/persistent_dict.py", line 72, in _make_dir_recursively
    os.makedirs(dir)
  File "/usr/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/sbuild-nonexistent'

WARNING: autodoc: failed to import module 'silx.opencl.sift.alignment'; the following exception was raised:
No module named 'silx.opencl.sift'
WARNING: autodoc: failed to import module 'silx.opencl.sift.match'; the following exception was raised:
No module named 'silx.opencl.sift'
WARNING: autodoc: failed to import module 'silx.opencl.sift.plan'; the following exception was raised:
No module named 'silx.opencl.sift'
WARNING: autodoc: failed to import function 'plot' from module 'silx.sx'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/util/inspect.py", line 204, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'silx.sx' has no attribute 'plot'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/ext/autodoc/importer.py", line 176, in import_object
    obj = attrgetter(obj, attrname)
  File "/usr/lib/python3/dist-packages/sphinx/ext/autodoc/__init__.py", line 274, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/usr/lib/python3/dist-packages/sphinx/ext/autodoc/__init__.py", line 1517, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/usr/lib/python3/dist-packages/sphinx/util/inspect.py", line 220, in safe_getattr
    raise AttributeError(name)
AttributeError: plot

WARNING: autodoc: failed to import function 'imshow' from module 'silx.sx'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/util/inspect.py", line 204, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'silx.sx' has no attribute 'imshow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/ext/autodoc/importer.py", line 176, in import_object
    obj = attrgetter(obj, attrname)
  File "/usr/lib/python3/dist-packages/sphinx/ext/autodoc/__init__.py", line 274, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/usr/lib/python3/dist-packages/sphinx/ext/autodoc/__init__.py", line 1517, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/usr/lib/python3/dist-packages/sphinx/util/inspect.py", line 220, in safe_getattr
    raise AttributeError(name)
AttributeError: imshow

WARNING: autodoc: failed to import function 'scatter' from module 'silx.sx'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/util/inspect.py", line 204, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'silx.sx' has no attribute 'scatter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/ext/autodoc/importer.py", line 176, in import_object
    obj = attrgetter(obj, attrname)
  File "/usr/lib/python3/dist-packages/sphinx/ext/autodoc/__init__.py", line 274, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/usr/lib/python3/dist-packages/sphinx/ext/autodoc/__init__.py", line 1517, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/usr/lib/python3/dist-packages/sphinx/util/inspect.py", line 220, in safe_getattr
    raise AttributeError(name)
AttributeError: scatter

WARNING: autodoc: failed to import function 'ginput' from module 'silx.sx'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/util/inspect.py", line 204, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'silx.sx' has no attribute 'ginput'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/ext/autodoc/importer.py", line 176, in import_object
    obj = attrgetter(obj, attrname)
  File "/usr/lib/python3/dist-packages/sphinx/ext/autodoc/__init__.py", line 274, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/usr/lib/python3/dist-packages/sphinx/ext/autodoc/__init__.py", line 1517, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/usr/lib/python3/dist-packages/sphinx/util/inspect.py", line 220, in safe_getattr
    raise AttributeError(name)
AttributeError: ginput

WARNING: autodoc: failed to import function 'contour3d' from module 'silx.sx'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/util/inspect.py", line 204, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'silx.sx' has no attribute 'contour3d'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/ext/autodoc/importer.py", line 176, in import_object
    obj = attrgetter(obj, attrname)
  File "/usr/lib/python3/dist-packages/sphinx/ext/autodoc/__init__.py", line 274, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/usr/lib/python3/dist-packages/sphinx/ext/autodoc/__init__.py", line 1517, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/usr/lib/python3/dist-packages/sphinx/util/inspect.py", line 220, in safe_getattr
    raise AttributeError(name)
AttributeError: contour3d

WARNING: autodoc: failed to import function 'points3d' from module 'silx.sx'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/util/inspect.py", line 204, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'silx.sx' has no attribute 'points3d'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/ext/autodoc/importer.py", line 176, in import_object
    obj = attrgetter(obj, attrname)
  File "/usr/lib/python3/dist-packages/sphinx/ext/autodoc/__init__.py", line 274, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/usr/lib/python3/dist-packages/sphinx/ext/autodoc/__init__.py", line 1517, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/usr/lib/python3/dist-packages/sphinx/util/inspect.py", line 220, in safe_getattr
    raise AttributeError(name)
AttributeError: points3d

looking for now-outdated files... none found
```

**Comment by t20100** [comment]
For the `silx.sx` module, we are now loading the GUI functions only if relevant, i.e., it is not loaded if DISPLAY is not defined under Linux... Is it your case? (It's the case for our nightly builds...).
Just defining this environment variable should do the trick...

**Comment by picca** [comment]
Ok so it means, that I need to run the docugeneration under xvfb-run.

thanks

**Comment by t20100** [comment]
Settting DISPLAY was not a good idea (Qt doesn't like it ;) )
PR #2060 enables building `silx.sx` documentation without the need for DISPLAY to be set.
Let us know if it fixes your issue.

**Comment by t20100** [comment]
xvfb-run would be better to run the tests (otherwise GUI stuff is skipped), but with PR #2060 the doc should now be fine without DISPLAY.

**Comment by picca** [comment]
I have to deal with this now :)
```
reading sources... [ 92%] modules/sx
QStandardPaths: XDG_RUNTIME_DIR points to non-existing path '/run/user/22503', please create it with 0700 permissions.
QStandardPaths: XDG_RUNTIME_DIR points to non-existing path '/run/user/22503', please create it with 0700 permissions.
```

I will discuss about this with Debian qt maintainer.

**Comment by picca** [comment]
We now have 5.11 on Debian unstable, do you know what was the problem with QT ?

**Comment by picca** [comment]
other doc warning

```
/<<BUILDDIR>>/silx-0.8.0+dfsg/.pybuild/cpython3_3.6_silx/build/silx/gui/dialog/ColormapDialog.py:docstring of silx.gui.dialog.ColormapDialog.ColormapDialog.getColormap:1: WARNING: more than one target found for cross-reference 'Colormap': silx.gui.colors.Colormap, silx.gui.plot3d.scene.function.Colormap
/<<BUILDDIR>>/silx-0.8.0+dfsg/.pybuild/cpython3_3.6_silx/build/silx/gui/plot/backends/BackendBase.py:docstring of silx.gui.plot.backends.BackendBase.BackendBase.addImage:17: WARNING: more than one target found for cross-reference 'Colormap': silx.gui.colors.Colormap, silx.gui.plot3d.scene.function.Colormap
/<<BUILDDIR>>/silx-0.8.0+dfsg/.pybuild/cpython3_3.6_silx/build/silx/gui/plot/backends/BackendBase.py:docstring of silx.gui.plot.backends.BackendBase.BackendBase.addImage:15: WARNING: more than one target found for cross-reference 'Colormap': silx.gui.colors.Colormap, silx.gui.plot3d.scene.function.Colormap
/<<BUILDDIR>>/silx-0.8.0+dfsg/.pybuild/cpython3_3.6_silx/build/silx/gui/plot/backends/BackendMatplotlib.py:docstring of silx.gui.plot.backends.BackendMatplotlib.BackendMatplotlib.addImage:17: WARNING: more than one target found for cross-reference 'Colormap': silx.gui.colors.Colormap, silx.gui.plot3d.scene.function.Colormap
/<<BUILDDIR>>/silx-0.8.0+dfsg/.pybuild/cpython3_3.6_silx/build/silx/gui/plot/backends/BackendMatplotlib.py:docstring of silx.gui.plot.backends.BackendMatplotlib.BackendMatplotlib.addImage:15: WARNING: more than one target found for cross-reference 'Colormap': silx.gui.colors.Colormap, silx.gui.plot3d.scene.function.Colormap
/<<BUILDDIR>>/silx-0.8.0+dfsg/doc/source/modules/gui/plot/getting_started.rst:298: WARNING: more than one target found for cross-reference 'Colormap': silx.gui.colors.Colormap, silx.gui.plot3d.scene.function.Colormap
/<<BUILDDIR>>/silx-0.8.0+dfsg/doc/source/modules/gui/plot/getting_started.rst:341: WARNING: more than one target found for cross-reference 'Colormap': silx.gui.colors.Colormap, silx.gui.plot3d.scene.function.Colormap
/<<BUILDDIR>>/silx-0.8.0+dfsg/.pybuild/cpython3_3.6_silx/build/silx/gui/plot/PlotWidget.py:docstring of silx.gui.plot.PlotWidget.PlotWidget.addImage:28: WARNING: more than one target found for cross-reference 'Colormap': silx.gui.colors.Colormap, silx.gui.plot3d.scene.function.Colormap
/<<BUILDDIR>>/silx-0.8.0+dfsg/.pybuild/cpython3_3.6_silx/build/silx/gui/plot/PlotWidget.py:docstring of silx.gui.plot.PlotWidget.PlotWidget.addScatter:17: WARNING: more than one target found for cross-reference 'Colormap': silx.gui.colors.Colormap, silx.gui.plot3d.scene.function.Colormap
/<<BUILDDIR>>/silx-0.8.0+dfsg/.pybuild/cpython3_3.6_silx/build/silx/gui/plot/PlotWidget.py:docstring of silx.gui.plot.PlotWidget.PlotWidget.getDefaultColormap:1: WARNING: more than one target found for cross-reference 'Colormap': silx.gui.colors.Colormap, silx.gui.plot3d.scene.function.Colormap
/<<BUILDDIR>>/silx-0.8.0+dfsg/.pybuild/cpython3_3.6_silx/build/silx/gui/plot/PlotWidget.py:docstring of silx.gui.plot.PlotWidget.PlotWidget.setDefaultColormap:9: WARNING: more than one target found for cross-reference 'Colormap': silx.gui.colors.Colormap, silx.gui.plot3d.scene.function.Colormap
/<<BUILDDIR>>/silx-0.8.0+dfsg/.pybuild/cpython3_3.6_silx/build/silx/gui/plot/ScatterView.py:docstring of silx.gui.plot.ScatterView.ScatterView.getColormap:1: WARNING: more than one target found for cross-reference 'Colormap': silx.gui.colors.Colormap, silx.gui.plot3d.scene.function.Colormap
/<<BUILDDIR>>/silx-0.8.0+dfsg/.pybuild/cpython3_3.6_silx/build/silx/gui/plot/ColorBar.py:docstring of silx.gui.plot.ColorBar.ColorBarWidget.getColormap:1: WARNING: more than one target found for cross-reference 'Colormap': silx.gui.colors.Colormap, silx.gui.plot3d.scene.function.Colormap
/<<BUILDDIR>>/silx-0.8.0+dfsg/.pybuild/cpython3_3.6_silx/build/silx/gui/plot/ColorBar.py:docstring of silx.gui.plot.ColorBar.ColorBarWidget.setColormap:5: WARNING: more than one target found for cross-reference 'Colormap': silx.gui.colors.Colormap, silx.gui.plot3d.scene.function.Colormap
```

**Comment by t20100** [comment]
Qt needed the RANDR extension which was not available with xvfb.
I don't remember what was the exact error though.

**Comment by picca** [comment]
Looking here[1] it sems that it is possible to add the RANDR extension on the command line.

[1] https://stackoverflow.com/questions/12644001/how-to-add-the-missing-randr-extension

**Comment by t20100** [comment]
I might have I tried it at that time (but I don't remember)... Anyway for travis it is fine as it is.

**Comment by t20100** [comment]
closing as it should be fixed, reopen if needed
