### ISSUE TITLE
[CI] pyopengl causes error on Win32

### ISSUE THREAD

**Issue by PiRK** [silx-kit/silx#2074]
A recent PyOpenGl pre-release (https://pypi.org/project/PyOpenGL/#history) causes a bug on AppVeyor. 

```

INFO:OpenGL.acceleratesupport:No OpenGL_accelerate module loaded: No module named OpenGL_accelerate
Traceback (most recent call last):
  File "run_tests.py", line 479, in <module>
    unittest.defaultTestLoader.loadTestsFromNames(options.test_name))
  File "c:\python27-x64\Lib\unittest\loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "c:\python27-x64\Lib\unittest\loader.py", line 115, in loadTestsFromName
    test = obj()
  File "C:\projects\silx\venv_test\lib\site-packages\silx\test\__init__.py", line 63, in suite
    from ..sx.test import suite as test_sx_suite
  File "C:\projects\silx\venv_test\lib\site-packages\silx\sx\__init__.py", line 121, in <module>
    enable_gui()
  File "C:\projects\silx\venv_test\lib\site-packages\silx\sx\__init__.py", line 113, in enable_gui
    from ._plot3d import contour3d, points3d  # noqa
  File "C:\projects\silx\venv_test\lib\site-packages\silx\sx\_plot3d.py", line 38, in <module>
    from ..gui.plot3d.SceneWindow import SceneWindow
  File "C:\projects\silx\venv_test\lib\site-packages\silx\gui\plot3d\SceneWindow.py", line 38, in <module>
    from .SceneWidget import SceneWidget
  File "C:\projects\silx\venv_test\lib\site-packages\silx\gui\plot3d\SceneWidget.py", line 40, in <module>
    from .Plot3DWidget import Plot3DWidget
  File "C:\projects\silx\venv_test\lib\site-packages\silx\gui\plot3d\Plot3DWidget.py", line 41, in <module>
    from .. import _glutils as glu
  File "C:\projects\silx\venv_test\lib\site-packages\silx\gui\_glutils\__init__.py", line 36, in <module>
    from .OpenGLWidget import OpenGLWidget  # noqa
  File "C:\projects\silx\venv_test\lib\site-packages\silx\gui\_glutils\OpenGLWidget.py", line 40, in <module>
    from .._glutils import gl
  File "C:\projects\silx\venv_test\lib\site-packages\silx\gui\_glutils\gl.py", line 50, in <module>
    import OpenGL.GL as _GL
  File "C:\projects\silx\venv_test\lib\site-packages\OpenGL\GL\__init__.py", line 6, in <module>
    from OpenGL.GL.images import *
  File "C:\projects\silx\venv_test\lib\site-packages\OpenGL\GL\images.py", line 628, in <module>
    suffix, arrayConstant, getattr(GL_1_1,functionName),
  File "C:\projects\silx\venv_test\lib\site-packages\OpenGL\GL\images.py", line 578, in typedImageFunction
    if baseFunction:
  File "C:\projects\silx\venv_test\lib\site-packages\OpenGL\platform\baseplatform.py", line 382, in __nonzero__
    self.load()
  File "C:\projects\silx\venv_test\lib\site-packages\OpenGL\platform\baseplatform.py", line 397, in load
    force_extension = self.force_extension,
TypeError: constructFunction() got an unexpected keyword argument 'force_extension'
```

Indeed there is no `force_extension` keyword in `OpenGl.platform.win32.constructFunction` (https://github.com/mcfletch/pyopengl/blob/0d71fcf307cc9c5f7a856d736ff6f502da1e8bc0/OpenGL/platform/win32.py#L110)

**Comment by t20100** [comment]
New beta of PyOpenGL needs a few patches to work on Windows (I proposed some fixes: https://code.launchpad.net/~t20100/pyopengl/fix-win32)

**Comment by t20100** [comment]
closing as issue solved upstream
