### ISSUE TITLE
Clean-up try/except import of fabio and h5py

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#2120]
As fabio and h5py are strong dependencies, this kind of special case is no longer needed

**Comment by alexmarie78** [comment]
Hello,
I'm trying to deal with this issue.
Is it "import fabio" or "import h5py" replacing "try/except" blocks ? 
Or does it need something else ?

**Comment by t20100** [comment]
Great!

It's not just replacing:
```
try:
    import fabio
except ImportError:
    fabio = None
```
with: `import fabio`, it is also cleaning-up the usage of it such as removing `if fabio is None: ...`, remove test skipping (e.g., https://github.com/silx-kit/silx/blob/master/silx/io/test/test_fabioh5.py#L50), etc...

Maybe it is worth splitting this if it's a lot of changes (e.g., going submodule by submodule, or one for `fabio` another one for `h5py`)

**Comment by alexmarie78** [comment]
Thanks ! 
I'll do that.

**Comment by alexmarie78** [comment]
Hello,
While cleaning #2120, I ran through these errors:
- [1]

ERROR: test_matching (silx.opencl.sift.test.test_matching.TestMatching)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/experiences/diffabs/mariea/Github/silx/silx/build/lib.linux-x86_64-2.7/silx/opencl/sift/test/test_matching.py", line 162, in test_matching
    delta = abs(res_sort - siftmatch).max()
ValueError: operands could not be broadcast together with shapes (491,2) (488,2)


- [2]

ERROR: testH5pyNotInstalled (silx.app.test.test_convert.TestConvertCommand)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/experiences/diffabs/mariea/Github/silx/silx/build/lib.linux-x86_64-2.7/silx/utils/testutils.py", line 227, in wrapper
    result = func(*args, **kwargs)
  File "/home/experiences/diffabs/mariea/Github/silx/silx/build/lib.linux-x86_64-2.7/silx/utils/testutils.py", line 183, in __exit__
    expected_count, logging.getLevelName(level), count))
RuntimeError: Expected 1 ERROR logging messages, got 0

These two errors (in python2 run_tests.py) prevent me from doing a PR, but I don't know how to deal with it

**Comment by t20100** [comment]
Hi,

What's your OS? and do you know what are the available opencl drivers?

**Comment by alexmarie78** [comment]
The computer I am using is running under Debian9. The driver used is the AMD's one

**Comment by alexmarie78** [comment]
With python3, there's only one error while running "run_tests.py" : 

ERROR: testH5pyNotInstalled (silx.app.test.test_convert.TestConvertCommand)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/experiences/diffabs/mariea/Github/silx/silx/build/lib.linux-x86_64-3.5/silx/utils/testutils.py", line 227, in wrapper
    result = func(*args, **kwargs)
  File "/home/experiences/diffabs/mariea/Github/silx/silx/build/lib.linux-x86_64-3.5/silx/app/test/test_convert.py", line 105, in testH5pyNotInstalled
    result = convert.main(["convert", "foo.spec", "bar.edf"])
  File "/home/experiences/diffabs/mariea/Github/silx/silx/build/lib.linux-x86_64-3.5/silx/app/convert.py", line 310, in main
    import h5py
ImportError: import of 'h5py' halted; None in sys.modules

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/experiences/diffabs/mariea/Github/silx/silx/build/lib.linux-x86_64-3.5/silx/utils/testutils.py", line 227, in wrapper
    result = func(*args, **kwargs)
  File "/home/experiences/diffabs/mariea/Github/silx/silx/build/lib.linux-x86_64-3.5/silx/utils/testutils.py", line 183, in __exit__
    expected_count, logging.getLevelName(level), count))
RuntimeError: Expected 1 ERROR logging messages, got 0

**Comment by vallsv** [comment]
This test check the software without h5py. If h5py is mandatory, this test could be removed.

**Comment by t20100** [comment]
closed by PR #2353
