### ISSUE TITLE
compileKernel error when executing SiftPlan

### ISSUE THREAD

**Issue by curry1990** [silx-kit/silx#2125]
Hi, I am running silx on macOS.

```
>>> sift.SiftPlan(template=image, devicetype="GPU")
/Users/myname/Library/Python/2.7/lib/python/site-packages/pyopencl/__init__.py:233: CompilerWarning: Non-empty compiler output encountered. Set the environment variable PYOPENCL_COMPILER_OUTPUT=1 to see more.
  "to see more.", CompilerWarning)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/myname/Library/Python/2.7/lib/python/site-packages/silx/opencl/sift/plan.py", line 172, in __init__
    self.compile_kernels()
  File "/Users/myname/Library/Python/2.7/lib/python/site-packages/silx/opencl/sift/plan.py", line 352, in compile_kernels
    res = self.check_workgroup_size(kn)
  File "/Users/myname/Library/Python/2.7/lib/python/site-packages/silx/opencl/processing.py", line 227, in check_workgroup_size
    return self.kernels.max_workgroup_size(kernel_name)
  File "/Users/myname/Library/Python/2.7/lib/python/site-packages/silx/opencl/processing.py", line 93, in max_workgroup_size
    return kernel_workgroup_size(self._program, kernel)
  File "/Users/myname/Library/Python/2.7/lib/python/site-packages/silx/opencl/common.py", line 573, in kernel_workgroup_size
    return kernel.get_work_group_info(query_wg, device)
  File "/Users/myname/Library/Python/2.7/lib/python/site-packages/pyopencl/__init__.py", line 817, in kernel_get_work_group_info
    return self._wg_info_cache[param, device]
AttributeError: 'pyopencl._cl.Kernel' object has no attribute '_wg_info_cache
```

**Comment by t20100** [comment]
This looks to be related to an issue in the last version of pyopencl (v2018.2), see https://github.com/inducer/pyopencl/issues/244.

Can you try with the previous version of pyopencl v2018.1.1?

**Comment by curry1990** [comment]
Thank you @t20100 !
I have check the version of pyopencl, it is v2018.2.
Requirement already satisfied: pyopencl in ./Library/Python/2.7/lib/python/site-packages (2018.2)
I am trying the previous version of pyopencl. Thanks again!
