### ISSUE TITLE
Possible problem with silx 0.8.0

### ISSUE THREAD

**Issue by lucarebuffi** [silx-kit/silx#2144]
```
IndexError                                    Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/silx/gui/plot/ColorBar.py", line 252, in _activeImageChanged
    data=image)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/silx/gui/plot/ColorBar.py", line 176, in setColormap
    data=data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/silx/gui/plot/ColorBar.py", line 413, in setColormap
    self.colorScale.setColormap(colormap, data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/silx/gui/plot/ColorBar.py", line 543, in setColormap
    self._updateColorGradient()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/silx/gui/plot/ColorBar.py", line 560, in _updateColorGradient
    colors = colormap.getNColors(nbColors=self._NB_CONTROL_POINTS)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/silx/gui/colors.py", line 267, in getNColors
    colormap = self.copy()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/silx/gui/colors.py", line 566, in copy
    normalization=self._normalization)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/silx/gui/colors.py", line 204, in __init__
    self._setColors(colors)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/silx/gui/colors.py", line 237, in _setColors
    colors.shape = -1, colors.shape[-1]
IndexError: tuple index out of range
```

**Comment by lucarebuffi** [comment]
This happened after installing six 0.8.0, no problems with 0.7.0

**Comment by vasole** [comment]
How did you reach that situation?

**Comment by lucarebuffi** [comment]
Just running ShadowOui as I normally do. I simply made pip3 install silx --upgrade

**Comment by lucarebuffi** [comment]
restoring to silx 0.7.0 fixed my problem

**Comment by lucarebuffi** [comment]
These are the two lines of code triggering the error:

`            self.plot_canvas = ImageView()

            self.plot_canvas.setColormap({"name":"temperature", "normalization":"linear", "autoscale":True, "vmin":0, "vmax":0, "colors":256})
`

**Comment by vallsv** [comment]
Hi. I try your code in many ways without finding problems.

But i notice that `colors` is specified in your colormap. This field is supposed to contain a list of RBG colors if the `name` is empty. We will add some tests in this case.

Could you try to replace:
```
self.plot_canvas.setColormap({"name":"temperature", "normalization":"linear", "autoscale":True, "vmin":0, "vmax":0, "colors":256})
```
By
```
self.plot_canvas.setColormap({"name":"temperature", "normalization":"linear", "autoscale":True, "vmin":0, "vmax":0})
```

**Comment by vallsv** [comment]
The PR #2146 should fix this issue. But as the `colors` is ignored, it would be anyway better to remove it from your dictionary.
