### ISSUE TITLE
Debian packaging on debian10:

### ISSUE THREAD

**Issue by kif** [silx-kit/silx#2154]
I found 1 failure and 1 error:
* there is a  test on locales and hence locales should be installed as Build-dep for debian packaging
* POCL which is still providing the wrong answer. This is still related to: https://github.com/pocl/pocl/issues/617

```
======================================================================
ERROR: test_locale_user (silx.io.test.test_specfile.TestSFLocale)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/workspace/silx/build/lib.linux-x86_64-3.6/silx/io/test/test_specfile.py", line 408, in test_locale_user
    locale.setlocale(locale.LC_NUMERIC, '')  # use user's preferred locale
  File "/usr/lib/python3.6/locale.py", line 598, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

======================================================================
FAIL: test_medfilt (silx.opencl.test.test_medfilt.TestMedianFilter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/workspace/silx/build/lib.linux-x86_64-3.6/silx/opencl/test/test_medfilt.py", line 115, in test_medfilt
    self.assertEqual(r.error, 0, 'Results are correct')
AssertionError: 3.4028235e+38 != 0 : Results are correct
```

This fails regardless if it is python3.6 or python3.7.

**Comment by kif** [comment]
@picca I can patch our build procedure but you will have to include locales into yours (or the official debian ones)

apparently installing locale this is not enough ... one needs to configure them
