### ISSUE TITLE
isdeleted in XAxis

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#2201]
While testing the branch 0.9 with PyQt5 5.10.0 Python 3.5

```
Stderr:
Exception ignored in: <bound method SyncAxes.__del__ of <silx.gui.plot.utils.axis.SyncAxes object at 0x7fc50d2a2390>>
Traceback (most recent call last):
  File "/workspace/valls/silx.git/build/lib.linux-x86_64-3.5/silx/gui/plot/utils/axis.py", line 155, in __del__
    self.stop()
  File "/workspace/valls/silx.git/build/lib.linux-x86_64-3.5/silx/gui/plot/utils/axis.py", line 145, in stop
    if axis is not None and _isQObjectValid(axis):
  File "/workspace/valls/silx.git/build/lib.linux-x86_64-3.5/silx/gui/qt/inspect.py", line 62, in isValid
    return not _isdeleted(obj)
TypeError: isdeleted() argument 1 must be sip.simplewrapper, not XAxis
```

**Comment by vallsv** [comment]
With PyQt5 5.11.2 i do not notice any problem yet

**Comment by t20100** [comment]
closing as fixed with latest PyQt5, reopen if needed
