### ISSUE TITLE
ColorBar error

### ISSUE THREAD

**Issue by alexbjorling** [silx-kit/silx#2202]
Hi. With silx 0.8.0, my simple beam viewer spews out the below error on every update. The code is here

https://github.com/alexbjorling/nanomax-analysis-utils/blob/master/apps/limaLiveViewer.py

```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/silx/gui/plot/ColorBar.py", line 252, in _activeImageChanged
    data=image)
  File "/usr/lib64/python2.7/site-packages/silx/gui/plot/ColorBar.py", line 176, in setColormap
    data=data)
  File "/usr/lib64/python2.7/site-packages/silx/gui/plot/ColorBar.py", line 413, in setColormap
    self.colorScale.setColormap(colormap, data)
  File "/usr/lib64/python2.7/site-packages/silx/gui/plot/ColorBar.py", line 536, in setColormap
    self.setEnabled(colormap is not None)
RuntimeError: wrapped C/C++ object of type _ColorScale has been deleted
```

**Comment by alexbjorling** [comment]
Trying but not doing too well...

```
[alebjo@b-nanomax-controlroom-cc-1]~/silx% python setup.py install --user
INFO:silx.setup:Use setuptools
INFO:silx.setup:Install requires: numpy >=1.7.1
silx.io.specfile WARNING:
A cleaner locale independent implementation
may be achieved setting SPECFILE_USE_GNU_SOURCE to 1
For instance running this script as:
SPECFILE_USE_GNU_SOURCE=1 python setup.py build
running install
WARNING:silx.setup:Cython version is too old. At least version is 0.21.1                         expected. Cythonization is skipped.
running bdist_egg
running egg_info
writing requirements to silx.egg-info/requires.txt
writing silx.egg-info/PKG-INFO
writing top-level names to silx.egg-info/top_level.txt
writing dependency_links to silx.egg-info/dependency_links.txt
writing entry points to silx.egg-info/entry_points.txt
reading manifest file 'silx.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '.ipynb_checkpoints/*' found anywhere in distribution
writing manifest file 'silx.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
Traceback (most recent call last):
  File "setup.py", line 983, in <module>
    setup_package()
  File "setup.py", line 979, in setup_package
    setup(**setup_kwargs)
  File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 73, in run
    self.do_egg_install()
  File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 93, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/bdist_egg.py", line 185, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/lib/python2.7/site-packages/setuptools/command/bdist_egg.py", line 171, in call_command
    self.run_command(cmdname)
  File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/install_lib.py", line 20, in run
    self.build()
  File "/usr/lib64/python2.7/distutils/command/install_lib.py", line 111, in build
    self.run_command('build_ext')
  File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/build_ext.py", line 52, in run
    _build_ext.run(self)
  File "/usr/lib64/python2.7/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "setup.py", line 677, in build_extensions
    self.patch_extension(ext)
  File "setup.py", line 586, in patch_extension
    self.patch_with_default_cythonized_files(ext)
  File "setup.py", line 571, in patch_with_default_cythonized_files
    raise RuntimeError("Source file not found: %s. Cython is needed" % cythonized)
RuntimeError: Source file not found: silx/io/specfile.c. Cython is needed
```

I do have Cython of course.

```
[alebjo@b-nanomax-controlroom-cc-1]~/silx% sudo yum install Cython
[sudo] password for alebjo: 
Loaded plugins: fastestmirror, langpacks, nvidia, versionlock
Repository core-0 is listed more than once in the configuration
Loading mirror speeds from cached hostfile
Package Cython-0.19-5.el7.x86_64 already installed and latest version
Nothing to do
```

**Comment by payno** [comment]
Thank you for the report.

Current policy is to use pip.
Can you try installing Cython using pip please ?

```bash
pip2 install Cython --user
```

Then install silx

Instead of 
```bash
python2 setup.py install --user
```
use: 
```bash
pip2 install . --user
```

**Comment by vasole** [comment]
@alexbjorling 

What PiRK is saying with:

- from the source package which should contain the cythonized files https://files.pythonhosted.org/packages/e6/7a/ee7583a38e1d4fb6ce90719dc3a3bf67c8b89dad1ef61e7447a252bf4388/silx-0.9.0b0.tar.gz

is that with that file you would not need to upgrade cython and ``pip install . --no-cython`` should do the job

**Comment by alexbjorling** [comment]
@vasole thanks for explaining. But now I get 

```
[alebjo@b-v-nanomax-ec-0]~/silx-0.9.0b0% pip install . --no-cython       

Usage:   
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: --no-cython
```

**Comment by vasole** [comment]
@alexbjorling 

Then try to set it from the environment:

export WITH_CYTHON=0
pip install . --user

**Comment by PiRK** [comment]
`--no-cython` would have worked the following way (2 steps):
```
python setup.py build --no-cython
pip install . --user
```

**Comment by alexbjorling** [comment]
Ok thanks for all the help, `--no-cython` never worked but installed a newer Cython plus all the gcc stuff. Unfortunately the warning is still there (the segfault is from me closing the app)

```
Traceback (most recent call last):
  File "/mxn/home/alebjo/.local/lib/python2.7/site-packages/silx/gui/plot/ColorBar.py", line 250, in _activeImageChanged
    data=image)
  File "/mxn/home/alebjo/.local/lib/python2.7/site-packages/silx/gui/plot/ColorBar.py", line 174, in setColormap
    data=data)
  File "/mxn/home/alebjo/.local/lib/python2.7/site-packages/silx/gui/plot/ColorBar.py", line 411, in setColormap
    self.colorScale.setColormap(colormap, data)
  File "/mxn/home/alebjo/.local/lib/python2.7/site-packages/silx/gui/plot/ColorBar.py", line 534, in setColormap
    self.setEnabled(colormap is not None)
RuntimeError: wrapped C/C++ object of type _ColorScale has been deleted
zsh: segmentation fault (core dumped)  python  pil100k
[alebjo@b-nanomax-controlroom-cc-1]~% python -c "import silx; print silx.version"
0.9.0-rc0
```

**Comment by payno** [comment]
within distance it looks like your `_update` function is called after the destruction of the QWidget.
But I failed to reproduce the issue on my computer. Which Qt version are you using ? 

```python -c "from silx.gui import qt; print qt.qVersion()"```

One fix could be to disconnect the QTimer when the widget will be destroyed. You can try:

```python

import functools
...

callback = functools.partial(self.timer.timeout.disconnect, self._update)
self.destroyed.connect(callback)
```

**Comment by t20100** [comment]
I could not reproduce by patching your script to remove PyTango.
Which version of Qt are you using? (`python -c "from silx.gui import qt; print(qt.BINDING)"`)
Could you try calling `setImage` outside of the `try: ... except:` blcok in `_update` to see if the root of the issue is not hidden there?

**Comment by alexbjorling** [comment]
So for completeness, it's `PyQt4` and moving `setImage` outside the `try`/`except` block gives no more info. The application works but is just annoying to look at. I've failed to reproduce this on a different machine with the same `PyQt4` and `silx` versions. 

Giving up on finding the problem. Thanks again for your input.

**Comment by alexbjorling** [comment]
So for completeness, it's `PyQt4` and moving `setImage` outside the `try`/`except` block gives no more info. The application works but is just annoying to look at. I've failed to reproduce this on a different machine with the same `PyQt4` and `silx` versions. 

Giving up on finding the problem. Thanks again for your input.

**Comment by t20100** [comment]
There is a possible explanation: `ImageView` modifies the content of the `PlotWindow` and as a consequence the `ColorBarWidget` gets destroyed... but signals registered internally should also be disconnected...

Can you try to add the following line in `ImageView.py` line 349 (https://github.com/silx-kit/silx/blob/master/silx/gui/plot/ImageView.py#L349):
`        layout.addWidget(self.getColorBarWidget(), 0, 2)`
This might fix your issue.

I would also be interested to know which PyQt/PySide binding (and which version) you are using as so far I could not reproduce your problem.
