### ISSUE TITLE
[silx view] Fabio file not released

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#2238]
While loading an EDF file.

I don't know yet what's happen.
```
Exception ignored in: <bound method File.__del__ of <_io.FileIO name='../data/edf/payno/ref0001_0050.edf' mode='rb' closefd=True>>
Traceback (most recent call last):
  File "/home/valls/.local/lib/python3.5/site-packages/fabio/fabioutils.py", line 470, in __del__
  File "/home/valls/.local/lib/python3.5/site-packages/fabio/fabioutils.py", line 474, in close
AttributeError: 'NoneType' object has no attribute 'close'
```

**Comment by vallsv** [comment]
`FabioH5.File` was deleted and `FabioH5.EdfFabioReader` was deleted. Then no idea why this very low level object from fabio is still alive.
