### ISSUE TITLE
[mask] Problem to set mask with different sizes

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#2286]
```
ERROR:pyFAI-calib2.UNCAUGHT:operands could not be broadcast together with shapes (1065,1030) (0,0) 
Traceback (most recent call last):
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-3.5/pyFAI/gui/calibration/MaskTask.py", line 264, in __widgetShow
    self.__updateWidgetFromModel()
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-3.5/pyFAI/gui/calibration/MaskTask.py", line 285, in __updateWidgetFromModel
    self.__maskPanel.setSelectionMask(mask)
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/plot/MaskToolsWidget.py", line 316, in setSelectionMask
    self._mask.commit()
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/plot/_BaseMaskToolsWidget.py", line 144, in commit
    not numpy.all(numpy.equal(self._mask, self._history[-1]))):
ValueError: operands could not be broadcast together with shapes (1065,1030) (0,0) 
```

**Comment by t20100** [comment]
As far as I remember, as it is, it does not support setting a mask while there is no image.... but it should not raise an exception (or at least a more explicit one).
When there is a change of image size, the mask is clipped or expanded.

**Comment by payno** [comment]
Tried to reproduce with the following code:
```python
import numpy
from silx.gui import qt
from silx.gui.plot.MaskToolsWidget import MaskToolsWidget
from silx.gui.plot import Plot2D

app = qt.QApplication()

plot = Plot2D()
widget = MaskToolsWidget(plot=plot)
widget.setSelectionMask(mask=numpy.ones((2000, 2000)))
widget.show()
plot.show()

app.exec_()
```

The `commit` function is called but the blocking lines are no more used. Execution seems fine with different values of mask.

**Comment by payno** [comment]
As a consequence we cannot reproduce, processing seems fine -> closing the issue.

Please feel free to reopen the issue, if possible with code to reproduce if relevant.
