### ISSUE TITLE
tests of silx with MAX IV data

### ISSUE THREAD

**Issue by kklmn** [silx-kit/silx#2297]
Hi,
We at MAX IV typically save scans in two data formats: spec and hdf5. I am trying to test silx with them.

When I open an hdf5 file in hdf5widget.py, I get this error message:
```
'Hdf5LoadingItem' object has no attribute 'h5Class'   File "C:\WPy-3701\python-3.7.0.amd64\lib\site-packages\silx\gui\hdf5\NexusSortFilterProxyModel.py", line 202, in data
    if self.__isNXnode(item):
  File "C:\WPy-3701\python-3.7.0.amd64\lib\site-packages\silx\gui\hdf5\NexusSortFilterProxyModel.py", line 93, in __isNXnode
    class_ = node.h5Class
```
but without crash. Everything looks ok in the widget but I might miss some functionality as a result of the above error (?), please confirm I don't.
Please comment on the error: is it due to our non-standard hdf5 file format or a bug?

If I try with a spec file in fileDialog.py, I get this:
```
DEBUG:fabio.openimage:Attempting to open C:/ParSeq/tmp/tst2.dat
DEBUG:fabio.fabioutils:l262: invalid literal for int() with base 10: 'dat'
DEBUG:fabio.openimage:Backtrace
Traceback (most recent call last):
  File "C:\WPy-3701\python-3.7.0.amd64\lib\site-packages\fabio\openimage.py", line 195, in _openimage
    filetype = do_magic(magic_bytes, filename)
  File "C:\WPy-3701\python-3.7.0.amd64\lib\site-packages\fabio\openimage.py", line 117, in do_magic
    raise Exception("Could not interpret magic string")
Exception: Could not interpret magic string
DEBUG:fabio.fabioutils:l262: invalid literal for int() with base 10: 'dat'
WARNING:silx.io.spech5:Could not parse date format in scan 704.1 header. Using original date not converted to ISO-8601
DEBUG:silx.io.utils:File 'C:/ParSeq/tmp/tst2.dat' can't be read as fabio file.
Traceback (most recent call last):
  File "C:\WPy-3701\python-3.7.0.amd64\lib\site-packages\silx\io\utils.py", line 471, in _open_local_file
    return fabioh5.File(filename)
  File "C:\WPy-3701\python-3.7.0.amd64\lib\site-packages\silx\io\fabioh5.py", line 917, in __init__
    self.__fabio_reader = self.create_fabio_reader(file_name, fabio_image, file_series)
  File "C:\WPy-3701\python-3.7.0.amd64\lib\site-packages\silx\io\fabioh5.py", line 994, in create_fabio_reader
    reader = FabioReader(file_name, fabio_image, file_series)
  File "C:\WPy-3701\python-3.7.0.amd64\lib\site-packages\silx\io\fabioh5.py", line 343, in __init__
    self.__load(file_name, fabio_image, file_series)
  File "C:\WPy-3701\python-3.7.0.amd64\lib\site-packages\silx\io\fabioh5.py", line 361, in __load
    self.__fabio_file = fabio.open(file_name)
  File "C:\WPy-3701\python-3.7.0.amd64\lib\site-packages\fabio\openimage.py", line 142, in openimage
    obj = _openimage(filename)
  File "C:\WPy-3701\python-3.7.0.amd64\lib\site-packages\fabio\openimage.py", line 214, in _openimage
    raise IOError("Fabio could not identify " + filename)
OSError: Fabio could not identify C:/ParSeq/tmp/tst2.dat
DEBUG:silx.gui.dialog.AbstractDataFileDialog:Clear dialog
Nothing selected
DEBUG:silx.gui.dialog.AbstractDataFileDialog:Clear AbstractDataFileDialog
DEBUG:silx.gui.hdf5.Hdf5TreeModel:Clear Hdf5TreeModel
```
Again, is something wrong with the data? Or the data must be a 2D image and silx is not meant for spectroscopy? Please comment.

I attach a zip with both data versions, they have a single scan.
[tst2.zip](https://github.com/silx-kit/silx/files/2695147/tst2.zip)

Thank you in advance!
Konstantin

**Comment by vallsv** [comment]
I will take a look at it.

For the spec file, fabio is not supposed to load it, then maybe change the file format filter first to select "HDF5-like spec", or something like that.

**Comment by vallsv** [comment]
From command line, i did not notice any problems with both files, using the master branch, then your first problem is already maybe solved.
```
silx view tst2.dat tst2.h5
```

**Comment by vallsv** [comment]
No problem to load spec file using the file dialog.

Then which version of `silx` do you use? And which version of `fabio`?

The output of `pip list` could help.

**Comment by kklmn** [comment]
fabio                    0.8.0
silx                     0.8.0

**Comment by kklmn** [comment]
yes, with 'silx view' it works, just with a warning
```
WARNING:silx.io.spech5:Could not parse date format in scan 704.1 header. Using original date not converted to ISO-8601
```
This is good enough for me. Thanks!
The widgets were just a starting point.

**Comment by kklmn** [comment]
sorry, didn't want to close it

**Comment by kklmn** [comment]
with 0.9.0 it's worse:
```
>silx view tst2.dat tst2.h5
WARNING:silx.io.spech5:Could not parse date format in scan 704.1 header. Using original date not converted to ISO-8601
ERROR:silx.gui.qt._qt:<class 'UnicodeDecodeError'> 'utf-8' codec can't decode byte 0xb7 in position 2: invalid start byte   File "C:\WPy-3701\python-3.7.0.amd64\lib\site-packages\silx\gui\hdf5\Hdf5TreeModel.py", line 515, in data
    return node.dataType(role)
  File "C:\WPy-3701\python-3.7.0.amd64\lib\site-packages\silx\gui\hdf5\Hdf5Item.py", line 380, in dataType
    text = self.nexusClassName
  File "C:\WPy-3701\python-3.7.0.amd64\lib\site-packages\silx\gui\hdf5\Hdf5Item.py", line 354, in nexusClassName
    self.__nx_class = str(self.__nx_class, "UTF-8")
```

**Comment by vasole** [comment]
@kklmn 

The last one should have been already fixed by #2293

**Comment by kklmn** [comment]
Yes, the last one has gone but there is an import error now:
```
ERROR:silx.gui.qt._qt:<class 'ModuleNotFoundError'> No module named 'silx.app.view.Viewer'   File "C:\WPy-3701\python-3.7.0.amd64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\WPy-3701\python-3.7.0.amd64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\WPy-3701\python-3.7.0.amd64\Scripts\silx.exe\__main__.py", line 9, in <module>
    sys.exit(main())
  File "C:\WPy-3701\python-3.7.0.amd64\lib\site-packages\silx\__main__.py", line 65, in main
    status = launcher.execute(sys.argv)
  File "C:\WPy-3701\python-3.7.0.amd64\lib\site-packages\silx\utils\launcher.py", line 295, in execute
    return command.execute(command_argv)
  File "C:\WPy-3701\python-3.7.0.amd64\lib\site-packages\silx\utils\launcher.py", line 129, in execute
    status = func(argv)
  File "C:\WPy-3701\python-3.7.0.amd64\lib\site-packages\silx\app\view\main.py", line 145, in main
    from .Viewer import Viewer
```
`.Viewer` doesn't match the file name `viewer.py`

**Comment by kklmn** [comment]
There are other import errors with the same file naming reason.
Please run `silx view tst2.dat` with the dat file from my 1st post in this thread.
Thanks!

**Comment by kklmn** [comment]
ok, this is not a silx's problem. The downloaded silx-master.zip does have properly capitalized file names. The install by `pip install silx-master.zip` corrupts the names to the lower case.

**Comment by vallsv** [comment]
Hi. Could it be possible to create new issue for each problems. It will be much more easy for use to manage it. Then could we close this issue?
