### ISSUE TITLE
[plot] ROI example with Debian Python 2.7

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#2325]
Looks to be a problem with old version of matplotlib
```
Traceback (most recent call last):
  File "/workspace/valls/silx.git/build/lib.linux-x86_64-2.7/silx/gui/plot/backends/BackendBase.py", line 337, in postRedisplay
    plot.replot()
  File "/workspace/valls/silx.git/build/lib.linux-x86_64-2.7/silx/gui/plot/PlotWidget.py", line 2560, in replot
    self._backend.replot()
  File "/workspace/valls/silx.git/build/lib.linux-x86_64-2.7/silx/gui/plot/backends/BackendMatplotlib.py", line 1142, in replot
    self.draw()
  File "/workspace/valls/silx.git/build/lib.linux-x86_64-2.7/silx/gui/plot/backends/BackendMatplotlib.py", line 1126, in draw
    self._drawOverlays()
  File "/workspace/valls/silx.git/build/lib.linux-x86_64-2.7/silx/gui/plot/backends/BackendMatplotlib.py", line 1079, in _drawOverlays
    self.ax.draw_artist(item)
  File "/usr/lib/python2.7/dist-packages/matplotlib/axes/_base.py", line 2104, in draw_artist
    a.draw(self._cachedRenderer)
  File "/usr/lib/python2.7/dist-packages/matplotlib/artist.py", line 59, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/matplotlib/patches.py", line 449, in draw
    gc.set_linestyle(self._linestyle)
  File "/usr/lib/python2.7/dist-packages/matplotlib/backend_bases.py", line 1032, in set_linestyle
    raise ValueError('Unrecognized linestyle: %s' % str(style))
ValueError: Unrecognized linestyle: --
```

**Comment by vallsv** [comment]
It was patched in the mask PR. Maybe it is already solved in PR #2266

**Comment by t20100** [comment]
Master works with matplotlib 1.4.2 (debian 8).

**Comment by vallsv** [comment]
Checked. It's fine.
