### ISSUE TITLE
[CI] Nightly build failure due to FFT norm keyword and numpy version lower than 1.10

### ISSUE THREAD

**Issue by vasole** [silx-kit/silx#2329]
Decide if to ignore the norm keyword for versions of numpy lower than 1.10 or if we bump the minimum version required to the highest available for debian 8 via backports. Nightly build log follows
```
ERROR: test_numpy_fft (silx.math.fft.test.test_fft.TestNumpyFFT)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tester/silx/build/lib.linux-x86_64-2.7/silx/math/fft/test/test_fft.py", line 257, in test_numpy_fft
    res = F.fft(input_data)
  File "/home/tester/silx/build/lib.linux-x86_64-2.7/silx/math/fft/npfft.py", line 109, in fft
    return self.numpy_funcs[0](array, **self.numpy_args)
TypeError: fft() got an unexpected keyword argument 'norm'

======================================================================
ERROR: test_numpy_fft (silx.math.fft.test.test_fft.TestNumpyFFT)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tester/silx/build/lib.linux-x86_64-2.7/silx/math/fft/test/test_fft.py", line 257, in test_numpy_fft
    res = F.fft(input_data)
  File "/home/tester/silx/build/lib.linux-x86_64-2.7/silx/math/fft/npfft.py", line 109, in fft
    return self.numpy_funcs[0](array, **self.numpy_args)
TypeError: fft() got an unexpected keyword argument 'norm'

======================================================================
ERROR: test_numpy_fft (silx.math.fft.test.test_fft.TestNumpyFFT)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tester/silx/build/lib.linux-x86_64-2.7/silx/math/fft/test/test_fft.py", line 257, in test_numpy_fft
    res = F.fft(input_data)
  File "/home/tester/silx/build/lib.linux-x86_64-2.7/silx/math/fft/npfft.py", line 109, in fft
    return self.numpy_funcs[0](array, **self.numpy_args)
TypeError: fft() got an unexpected keyword argument 'norm'

======================================================================
ERROR: test_numpy_fft (silx.math.fft.test.test_fft.TestNumpyFFT)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tester/silx/build/lib.linux-x86_64-2.7/silx/math/fft/test/test_fft.py", line 257, in test_numpy_fft
    res = F.fft(input_data)
  File "/home/tester/silx/build/lib.linux-x86_64-2.7/silx/math/fft/npfft.py", line 109, in fft
    return self.numpy_funcs[0](array, **self.numpy_args)
TypeError: fft() got an unexpected keyword argument 'norm'

======================================================================
ERROR: test_numpy_fft (silx.math.fft.test.test_fft.TestNumpyFFT)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tester/silx/build/lib.linux-x86_64-2.7/silx/math/fft/test/test_fft.py", line 257, in test_numpy_fft
    res = F.fft(input_data)
  File "/home/tester/silx/build/lib.linux-x86_64-2.7/silx/math/fft/npfft.py", line 109, in fft
    return self.numpy_funcs[0](array, **self.numpy_args)
TypeError: rfft() got an unexpected keyword argument 'norm'

======================================================================
ERROR: test_numpy_fft (silx.math.fft.test.test_fft.TestNumpyFFT)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tester/silx/build/lib.linux-x86_64-2.7/silx/math/fft/test/test_fft.py", line 257, in test_numpy_fft
    res = F.fft(input_data)
  File "/home/tester/silx/build/lib.linux-x86_64-2.7/silx/math/fft/npfft.py", line 109, in fft
    return self.numpy_funcs[0](array, **self.numpy_args)
TypeError: rfft() got an unexpected keyword argument 'norm'

======================================================================
ERROR: test_numpy_fft (silx.math.fft.test.test_fft.TestNumpyFFT)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tester/silx/build/lib.linux-x86_64-2.7/silx/math/fft/test/test_fft.py", line 257, in test_numpy_fft
    res = F.fft(input_data)
  File "/home/tester/silx/build/lib.linux-x86_64-2.7/silx/math/fft/npfft.py", line 109, in fft
    return self.numpy_funcs[0](array, **self.numpy_args)
TypeError: rfft() got an unexpected keyword argument 'norm'
```

**Comment by t20100** [comment]
I would be in favor of supporting `numpy` v1.8.2 for next release (and then move to 1.12 so we can inform about it in the release note) even if it is by failing gracefully for new features like FFT stuff.

**Comment by vasole** [comment]
In such a case, it is relatively easy to patch the module to strip the "norm" keyword if the numpy version is lower than 1.10
