### ISSUE TITLE
[CI] Error on doc

### ISSUE THREAD

**Issue by vasole** [silx-kit/silx#2339]
@payno 

Continuous integration fails

```'
Running Sphinx v1.4.9
Traceback (most recent call last):
  File "setup.py", line 1023, in <module>
    setup_package()
  File "setup.py", line 1019, in setup_package
    setup(**setup_kwargs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 346, in run
    BuildDoc.run(self)
  File "/usr/lib/python2.7/dist-packages/sphinx/setup_command.py", line 161, in run
    freshenv=self.fresh_env)
  File "/usr/lib/python2.7/dist-packages/sphinx/application.py", line 163, in __init__
    self.setup_extension(extension)
  File "/usr/lib/python2.7/dist-packages/sphinx/application.py", line 473, in setup_extension
    mod = __import__(extension, None, None, ['setup'])
  File "/home/tester/silx/doc/source/ext/snapshotqt_directive.py", line 269
    exec(code)
SyntaxError: unqualified exec is not allowed in function 'makescreenshot' because it contains a nested function with free variables
``

**Comment by payno** [comment]
issue come from sphinx parse the snapshot_directive. Fail on 'exec()' synthax. Need to add locals, globals... even if python2 will never execute this code...
PR will close it #2340
