### ISSUE TITLE
Yet another issue with nightly build

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#2346]
Looks to be due to loading different version of PyQt during the doc generation:
```
[...]
/home/tester/silx/doc/source/modules/gui/console.rst:7: WARNING: autodoc: failed to import module u'silx.gui.console'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 529, in import_object
    __import__(self.modname)
  File "/home/tester/silx/build/lib.linux-x86_64-2.7/silx/gui/console.py", line 95, in <module>
    from qtconsole.rich_ipython_widget import RichIPythonWidget
ImportError: No module named qtconsole.rich_ipython_widget
/home/tester/silx/doc/source/modules/gui/data/dataviewer.rst:4: WARNING: autodoc: failed to import module u'silx.gui.data.DataViewer'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 529, in import_object
    __import__(self.modname)
  File "/home/tester/silx/build/lib.linux-x86_64-2.7/silx/gui/data/DataViewer.py", line 30, in <module>
    from silx.gui.data import DataViews
  File "/home/tester/silx/build/lib.linux-x86_64-2.7/silx/gui/data/DataViews.py", line 40, in <module>
    from silx.gui.dialog.ColormapDialog import ColormapDialog
  File "/home/tester/silx/build/lib.linux-x86_64-2.7/silx/gui/dialog/ColormapDialog.py", line 76, in <module>
    from ..plot import PlotWidget
  File "/home/tester/silx/build/lib.linux-x86_64-2.7/silx/gui/plot/__init__.py", line 63, in <module>
    from .PlotWidget import PlotWidget  # noqa
  File "/home/tester/silx/build/lib.linux-x86_64-2.7/silx/gui/plot/PlotWidget.py", line 50, in <module>
    from .backends.BackendMatplotlib import BackendMatplotlibQt
  File "/home/tester/silx/build/lib.linux-x86_64-2.7/silx/gui/plot/backends/BackendMatplotlib.py", line 47, in <module>
    from ..matplotlib import FigureCanvasQTAgg
  File "/home/tester/silx/build/lib.linux-x86_64-2.7/silx/gui/plot/matplotlib/__init__.py", line 95, in <module>
    import matplotlib.backends.backend_qt5agg as backend
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_qt5agg.py", line 18, in <module>
    from .backend_qt5 import QtCore
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_qt5.py", line 27, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/qt_editor/figureoptions.py", line 17, in <module>
    import matplotlib.backends.qt_editor.formlayout as formlayout
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/qt_editor/formlayout.py", line 58, in <module>
    from matplotlib.backends.qt_compat import QtGui, QtWidgets, QtCore
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/qt_compat.py", line 91, in <module>
    from PyQt4 import QtCore, QtGui
RuntimeError: the PyQt4.QtCore and PyQt5.QtCore modules both wrap the QObject class
/home/tester/silx/doc/source/modules/gui/data/dataviewer.rst:6: WARNING: don't know which module to import for autodocumenting u'DataViewer' (try placing a "module" or "currentmodule" directive in the document, or giving an explicit module name)
/home/tester/silx/doc/source/modules/gui/data/dataviewerframe.rst:4: WARNING: autodoc: failed to import module u'silx.gui.data.DataViewerFrame'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 529, in import_object
    __import__(self.modname)
  File "/home/tester/silx/build/lib.linux-x86_64-2.7/silx/gui/data/DataViewerFrame.py", line 33, in <module>
    from .DataViewer import DataViewer
  File "/home/tester/silx/build/lib.linux-x86_64-2.7/silx/gui/data/DataViewer.py", line 30, in <module>
    from silx.gui.data import DataViews
  File "/home/tester/silx/build/lib.linux-x86_64-2.7/silx/gui/data/DataViews.py", line 40, in <module>
    from silx.gui.dialog.ColormapDialog import ColormapDialog
  File "/home/tester/silx/build/lib.linux-x86_64-2.7/silx/gui/dialog/ColormapDialog.py", line 76, in <module>
    from ..plot import PlotWidget
  File "/home/tester/silx/build/lib.linux-x86_64-2.7/silx/gui/plot/__init__.py", line 63, in <module>
    from .PlotWidget import PlotWidget  # noqa
  File "/home/tester/silx/build/lib.linux-x86_64-2.7/silx/gui/plot/PlotWidget.py", line 50, in <module>
    from .backends.BackendMatplotlib import BackendMatplotlibQt
  File "/home/tester/silx/build/lib.linux-x86_64-2.7/silx/gui/plot/backends/BackendMatplotlib.py", line 47, in <module>
    from ..matplotlib import FigureCanvasQTAgg
  File "/home/tester/silx/build/lib.linux-x86_64-2.7/silx/gui/plot/matplotlib/__init__.py", line 95, in <module>
    import matplotlib.backends.backend_qt5agg as backend
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_qt5agg.py", line 18, in <module>
    from .backend_qt5 import QtCore
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_qt5.py", line 27, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/qt_editor/figureoptions.py", line 17, in <module>
    import matplotlib.backends.qt_editor.formlayout as formlayout
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/qt_editor/formlayout.py", line 58, in <module>
    from matplotlib.backends.qt_compat import QtGui, QtWidgets, QtCore
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/qt_compat.py", line 91, in <module>
    from PyQt4 import QtCore, QtGui
RuntimeError: the PyQt4.QtCore module failed to register with the sip module
[...]
```

**Comment by t20100** [comment]
Actually, it's probably not this error that makes it fails...

**Comment by vallsv** [comment]
We should force using Python3 for documentation no?

**Comment by t20100** [comment]
yes

**Comment by vasole** [comment]
I thought the problem was an old and buggy Qt console trying to access Qt4 stuff and not realizing that Qt5 was already there.

**Comment by t20100** [comment]
Nightly build is now successful, but there are still issues with PyQt4 and PyQt5 both being loaded during documentation generation.

**Comment by vasole** [comment]
Can we afford to uninstall PyQt4 on that machine?

**Comment by t20100** [comment]
Nigthly build machine updates fixed this issue
