### ISSUE TITLE
[0.10 release] test_fbp

### ISSUE THREAD

**Issue by payno** [silx-kit/silx#2460]
on scisoft13 with python 2.7. Error is:

ERROR: test_fbp (silx.opencl.test.test_backprojection.TestFBP)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/users/payno/.local/lib/python2.7/site-packages/silx/opencl/test/test_backprojection.py", line 146, in test_fbp
    t, res = self.measure()
  File "/users/payno/.local/lib/python2.7/site-packages/silx/opencl/test/test_backprojection.py", line 118, in measure
    result = self.fbp.filtered_backprojection(self.sino)
  File "/users/payno/.local/lib/python2.7/site-packages/silx/opencl/backprojection.py", line 376, in filtered_backprojection
    self.sino_filter(sino, output=self.d_sino)
  File "/users/payno/.local/lib/python2.7/site-packages/silx/opencl/sinofilter.py", line 470, in filter_sino
    self._prepare_input_sino(sino)
  File "/users/payno/.local/lib/python2.7/site-packages/silx/opencl/sinofilter.py", line 371, in _prepare_input_sino
    self.copy2d(self.d_sino_padded, d_sino_ref, self.sino_shape)
  File "/users/payno/.local/lib/python2.7/site-packages/silx/opencl/sinofilter.py", line 332, in copy2d
    np.int32(transfer_shape[::-1])
  File "/usr/lib/python2.7/dist-packages/pyopencl/cffi_cl.py", line 1973, in __call__
    return self._enqueue(self, queue, global_size, local_size, *args, **kwargs)
  File "<generated function enqueue_knl_cpy2d>", line 157, in enqueue_knl_cpy2d
  File "/usr/lib/python2.7/dist-packages/pyopencl/cffi_cl.py", line 2157, in enqueue_nd_range_kernel
    global_work_size, local_work_size, c_wait_for, num_wait_for))
TypeError: initializer for ctype 'size_t *' must be a cdata pointer, not numpy.ndarray

**Comment by payno** [comment]
My bad, wrong virtualenv. Work on scisoft13
