### ISSUE TITLE
IPythonDockWidget import order

### ISSUE THREAD

**Issue by alexbjorling** [silx-kit/silx#2553]
I am having trouble using the `IPythonDockWidget` as expected. It is perhaps not a silx issue really, I'm not sure.

First of all, qtconsole doesn't find PyQt5 even though silx finds it, so just importing `IPythonDockWidget` gives
```
    Currently-imported Qt library:   'pyqt5'
    PyQt4 installed:                 True
    PyQt5 installed:                 False
    PySide >= 1.0.3 installed:       False
    PySide2 installed:               False
    Tried to load:                   ['pyqt5']
```

Forcing PyQt4 like
```python
from PyQt4 import QtCore
from silx.gui.console import IPythonDockWidget
```
gives a console which doesn't work. Every time I type a letter I get an error raised, for example:
```
Traceback (most recent call last):
  File "/home/alex/.local/lib/python2.7/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/home/alex/.local/lib/python2.7/site-packages/qtconsole/jupyter_widget.py", line 187, in _handle_execute_reply
    self._show_interpreter_prompt(number)
  File "/home/alex/.local/lib/python2.7/site-packages/qtconsole/jupyter_widget.py", line 380, in _show_interpreter_prompt
    self._make_continuation_prompt(self._prompt), html=True)
  File "/home/alex/.local/lib/python2.7/site-packages/qtconsole/jupyter_widget.py", line 514, in _make_continuation_prompt
    space_count = len(prompt.lstrip('\n')) - len(end_chars)
AttributeError: 'QString' object has no attribute 'lstrip'
Traceback (most recent call last):
  File "/home/alex/.local/lib/python2.7/site-packages/qtconsole/frontend_widget.py", line 78, in highlightBlock
    without_prompt = self.transform_ipy_prompt(string)
  File "/home/alex/.local/lib/python2.7/site-packages/qtconsole/frontend_widget.py", line 56, in transform_ipy_prompt
    if not line or line.isspace():
AttributeError: 'QString' object has no attribute 'isspace'
Traceback (most recent call last):
  File "/home/alex/.local/lib/python2.7/site-packages/qtconsole/frontend_widget.py", line 78, in highlightBlock
    without_prompt = self.transform_ipy_prompt(string)
  File "/home/alex/.local/lib/python2.7/site-packages/qtconsole/frontend_widget.py", line 56, in transform_ipy_prompt
    if not line or line.isspace():
AttributeError: 'QString' object has no attribute 'isspace'
```

The only thing which seems to work for me is to first import from qtconsole
```python
from qtconsole.rich_ipython_widget import RichIPythonWidget
from silx.gui.console import IPythonDockWidget
```
but then of course qtconsole gets to choose the PyQt version and it doesn't do a very good job.

To the question: is all of this just a result of a bad PyQt5 installation / qtconsole configuration? Or is it something to do with silx?

**Comment by t20100** [comment]
Which version of `qtconsole` do you use? Can you try with an updated version?
It seems like an incompatibility in the way Qt binding is probed. As `qtconsole` does not see `PyQt5` I would say that's the root of the issue.
We had quite a few issues when we switched the order in which we probe Qt bindings from PyQt4-PyQt5 to PyQt5-PyQt4.

The error when forcing `PyQt4`, is the sip API level (see https://www.riverbankcomputing.com/static/Docs/PyQt4/incompatible_apis.html), try:
```
from PyQt4 import QtCore
import sip
sip.setapi('QString', 2)
```

**Comment by vasole** [comment]
I think the sip import has to take place prior to the PyQt4 import.

**Comment by t20100** [comment]
Yes you're right... previous post updated.

**Comment by alexbjorling** [comment]
It's actually `qtconsole` 4.4.3 which looks like the latest release.

I don't want to force `PyQt4` of course, so I guess I'll just consider it a `qtconsole` problem and keep the proper `IPythonDockWidget` import in my `silx` application. Thanks for the feedback!

**Comment by t20100** [comment]
OK.

I tried a few different ways to import, but I cannot reproduce this.
