### ISSUE TITLE
[plot gl] is there a size limit for plotting RGB images with the gl backend?

### ISSUE THREAD

**Issue by PiRK** [silx-kit/silx#2557]
I'm trying to show RGB images with the silx plot using the gl backend, and I get an error for large files only (~900Mb). It works ok with smaller images (~500 Mb).

With the backend mpl, I was able to display (slowly) all of these images.

To replicate :
```
from silx.gui import qt
from silx.gui.plot import Plot2D
import numpy
# from PIL import Image
# Image.MAX_IMAGE_PIXELS = None

app = qt.QApplication([])
plt = Plot2D(backend="gl")

img = numpy.arange(22386*15182*3, dtype=numpy.uint8)
img.shape = (22386, 15182, 3)

plt.addImage(img)
plt.show()

app.exec_()
```

And the error is:
```
Traceback (most recent call last):
  File "/home/pierre/.local/lib/python3.7/site-packages/silx/gui/_glutils/OpenGLWidget.py", line 234, in paintGL
    parent.paintGL()
  File "/home/pierre/.local/lib/python3.7/site-packages/silx/gui/plot/backends/BackendOpenGL.py", line 548, in paintGL
    self._paintFBOGL()
  File "/home/pierre/.local/lib/python3.7/site-packages/silx/gui/plot/backends/BackendOpenGL.py", line 492, in _paintFBOGL
    self._renderPlotAreaGL()
  File "/home/pierre/.local/lib/python3.7/site-packages/silx/gui/plot/backends/BackendOpenGL.py", line 742, in _renderPlotAreaGL
    isXLog, isYLog)
  File "/home/pierre/.local/lib/python3.7/site-packages/silx/gui/plot/backends/glutils/GLPlotImage.py", line 674, in render
    self._renderLinear(matrix)
  File "/home/pierre/.local/lib/python3.7/site-packages/silx/gui/plot/backends/glutils/GLPlotImage.py", line 599, in _renderLinear
    self.prepare()
  File "/home/pierre/.local/lib/python3.7/site-packages/silx/gui/plot/backends/glutils/GLPlotImage.py", line 590, in prepare
    texUnit=self._DATA_TEX_UNIT)
  File "/home/pierre/.local/lib/python3.7/site-packages/silx/gui/plot/backends/glutils/GLTexture.py", line 170, in __init__
    wrap=self._WRAP)
  File "/home/pierre/.local/lib/python3.7/site-packages/silx/gui/_glutils/Texture.py", line 73, in __init__
    assert shape is None
AssertionError
```

```
pip3 list 
PyOpenGL                      3.1.0 
PySide2                       5.12.3  
silx                          0.10.1 
numpy                         1.16.3   
```

**Comment by t20100** [comment]
There is a typo, comment the following line and it should work (at least it works for me):
https://github.com/silx-kit/silx/blob/305615c29cd9c05d379ca965b7ded3b65631c8ae/silx/gui/plot/backends/glutils/GLTexture.py#L166

**Comment by t20100** [comment]
BTW, for large images it's loading the image as tiles in the GPU to overcome the limited size of a single texture. Yet it is loading all the data as textures at once, so you should reach a limit at some point...
