### ISSUE TITLE
[PPC64LE] Interesting endianness issues with specfiles

### ISSUE THREAD

**Issue by kif** [silx-kit/silx#2562]
```
======================================================================
ERROR: testLosePrecisionUsingFloat80 (silx.utils.test.test_number.TestConversionTypes)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/test/workspace/silx/build/lib.linux-ppc64le-3.6/silx/utils/test/test_number.py", line 154, in testLosePrecisionUsingFloat80
    dtype = func(value)
  File "/home/test/workspace/silx/build/lib.linux-ppc64le-3.6/silx/utils/testutils.py", line 227, in wrapper
    result = func(*args, **kwargs)
  File "/home/test/workspace/silx/build/lib.linux-ppc64le-3.6/silx/utils/testutils.py", line 183, in __exit__
    expected_count, logging.getLevelName(level), count))
RuntimeError: Expected 1 WARNING logging messages, got 0

======================================================================
FAIL: testH5CityAttrs (silx.io.test.test_dictdump.TestDictToH5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/test/workspace/silx/build/lib.linux-ppc64le-3.6/silx/io/test/test_dictdump.py", line 91, in testH5CityAttrs
    5.7196)
AssertionError: 45.183000000000554 != 5.7196 within 7 places

======================================================================
FAIL: testAppendToHDF5 (silx.io.test.test_spectoh5.TestConvertSpecHDF5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/test/workspace/silx/build/lib.linux-ppc64le-3.6/silx/io/test/test_spectoh5.py", line 120, in testAppendToHDF5
    self.h5f["/foo/bar/spam/1.2/measurement/mca_1/data"])
AssertionError: False is not true

======================================================================
FAIL: testLinks (silx.io.test.test_spectoh5.TestConvertSpecHDF5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/test/workspace/silx/build/lib.linux-ppc64le-3.6/silx/io/test/test_spectoh5.py", line 180, in testLinks
    self.h5f["/1.2/measurement/mca_0/data"])
AssertionError: False is not true

======================================================================
FAIL: testHdf5 (silx.io.test.test_utils.TestH5Ls)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/test/workspace/silx/build/lib.linux-ppc64le-3.6/silx/io/test/test_utils.py", line 241, in testHdf5
    self.assertMatchAnyStringInList(match, lines)
  File "/home/test/workspace/silx/build/lib.linux-ppc64le-3.6/silx/io/test/test_utils.py", line 217, in assertMatchAnyStringInList
    " string in list " + str(list_of_strings))
AssertionError: regex pattern \t<HDF5 dataset "data": shape \(1,\), type "<f[48]"> does not match any string in list ['+foo', '\t+bar', '\t\t<HDF5 dataset "spam": shape (2, 2), type "<i8">', '\t\t<HDF5 dataset "tmp": shape (3,), type "<i8">', '\t<HDF5 dataset "data": shape (1,), type "<f16">', '']

======================================================================
FAIL: testSpectra (silx.io.test.test_nxdata.TestNXdata)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/test/workspace/silx/build/lib.linux-ppc64le-3.6/silx/io/test/test_nxdata.py", line 247, in testSpectra
    0.8)      # numpy.arange(10) * 0.4
AssertionError: 0.0 != 0.8 within 7 places
```

**Comment by t20100** [comment]
I could not reproduce with current master.
