### ISSUE TITLE
[plot] pressing exotic mouse buttons cause errors

### ISSUE THREAD

**Issue by PiRK** [silx-kit/silx#2585]
The plot seems to have issues when used with a gaming mouse (accidental clicks)

```
Traceback (most recent call last):
  File "/home/pierre/.local/lib/python3.7/site-packages/silx/gui/plot/backends/BackendOpenGL.py", line 385, in mousePressEvent
    btn = self._MOUSE_BTNS[event.button()]
KeyError: PySide2.QtCore.Qt.MouseButton.ForwardButton

Traceback (most recent call last):
  File "/home/pierre/.local/lib/python3.7/site-packages/silx/gui/plot/backends/BackendOpenGL.py", line 385, in mousePressEvent
    btn = self._MOUSE_BTNS[event.button()]
KeyError: PySide2.QtCore.Qt.MouseButton.TaskButton

Traceback (most recent call last):
  File "/home/pierre/.local/lib/python3.7/site-packages/silx/gui/plot/backends/BackendOpenGL.py", line 385, in mousePressEvent
    btn = self._MOUSE_BTNS[event.button()]
KeyError: PySide2.QtCore.Qt.MouseButton.BackButton

```

Accepting these buttons in `BackendOpenGL.mousePressEvent` will probably cause issues downstream: https://github.com/silx-kit/silx/blob/6cfaaf05d87e2f1d978fcc0dce06b74111e5f270/silx/gui/plot/PlotEvents.py#L62

Maybe they should be ignored.

**Comment by t20100** [comment]
Yes, they should be ignored.

**Comment by PiRK** [comment]
Unless someone wants to program a FPS video game with a sniper riffle option, using the plot widget.

**Comment by t20100** [comment]
What else!
