### ISSUE TITLE
[debian][0.10.1] error during build

### ISSUE THREAD

**Issue by picca** [silx-kit/silx#2606]
Hello, I have uploaded silx into Debian experimental but I get error on the arm64 architecture.

https://buildd.debian.org/status/fetch.php?pkg=silx&arch=arm64&ver=0.10.1%2Bdfsg-1%7Eexp1&stamp=1559037411&raw=0

**Comment by picca** [comment]
It seems that we have this kind of error,
```
DEBUG:silx.io.utils:File '/tmp/tmp058jgd93' can't be read as fabio file.
Traceback (most recent call last):
  File "/<<BUILDDIR>>/silx-0.10.1+dfsg/.pybuild/cpython3_3.7_silx/build/silx/io/utils.py", line 467, in _open_local_file
    return fabioh5.File(filename)
  File "/<<BUILDDIR>>/silx-0.10.1+dfsg/.pybuild/cpython3_3.7_silx/build/silx/io/fabioh5.py", line 938, in __init__
    self.__fabio_reader = self.create_fabio_reader(file_name, fabio_image, file_series)
  File "/<<BUILDDIR>>/silx-0.10.1+dfsg/.pybuild/cpython3_3.7_silx/build/silx/io/fabioh5.py", line 1021, in create_fabio_reader
    reader = FabioReader(file_name, fabio_image, file_series)
  File "/<<BUILDDIR>>/silx-0.10.1+dfsg/.pybuild/cpython3_3.7_silx/build/silx/io/fabioh5.py", line 363, in __init__
    self.__load(file_name, fabio_image, file_series)
  File "/<<BUILDDIR>>/silx-0.10.1+dfsg/.pybuild/cpython3_3.7_silx/build/silx/io/fabioh5.py", line 381, in __load
    self.__fabio_file = fabio.open(file_name)
  File "/usr/lib/python3/dist-packages/fabio/openimage.py", line 142, in openimage
    obj = _openimage(filename)
  File "/usr/lib/python3/dist-packages/fabio/openimage.py", line 214, in _openimage
    raise IOError("Fabio could not identify " + filename)
OSError: Fabio could not identify /tmp/tmp058jgd93
```

**Comment by picca** [comment]
the first problematic test is this one.

```
testAppendToHDF5 (silx.io.test.test_spectoh5.TestConvertSpecHDF5) ... DEBUG:fabio.openimage:Attempting to open /tmp/tmpHv2OAi
```

**Comment by picca** [comment]
Now the only detected as FAILED test is this one

```
======================================================================
ERROR: testLosePrecisionUsingFloat80 (silx.utils.test.test_number.TestConversionTypes)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/.pybuild/cpython2_2.7_silx/build/silx/utils/test/test_number.py", line 154, in testLosePrecisionUsingFloat80
    dtype = func(value)
  File "/<<PKGBUILDDIR>>/.pybuild/cpython2_2.7_silx/build/silx/utils/testutils.py", line 227, in wrapper
    result = func(*args, **kwargs)
  File "/<<PKGBUILDDIR>>/.pybuild/cpython2_2.7_silx/build/silx/utils/testutils.py", line 183, in __exit__
    expected_count, logging.getLevelName(level), count))
RuntimeError: Expected 1 WARNING logging messages, got 0
```

**Comment by t20100** [comment]
I don't see any reason for this test not to pass (it's passing in our CI, and this is not the only place we test for warnings)....

**Comment by t20100** [comment]
I read architecture too fast : arm64 -> amd64. We have the same issue on power9.
