### ISSUE TITLE
Can't zoom in 1D widgets

### ISSUE THREAD

**Issue by alexbjorling** [silx-kit/silx#2722]
In a `PlotWindow` derivative, trying to zoom with the mouse crashes everything. Here's the code I need to reproduce the bug,

```python
from silx.gui.plot import PlotWindow
from silx.gui import qt
import sys

app = qt.QApplication(sys.argv)
pw = PlotWindow()
pw.show()
app.exec_()
```

and here's the output,

```
Traceback (most recent call last):
  File "/mxn/home/nanomax-user/.local/lib/python2.7/site-packages/silx/gui/plot/backends/BackendBase.py", line 356, in postRedisplay
    plot.replot()
  File "/mxn/home/nanomax-user/.local/lib/python2.7/site-packages/silx/gui/plot/PlotWidget.py", line 2694, in replot
    item._update(self._backend)
  File "/mxn/home/nanomax-user/.local/lib/python2.7/site-packages/silx/gui/plot/items/core.py", line 312, in _update
    self._backendRenderer = self._addBackendRenderer(backend)
  File "/mxn/home/nanomax-user/.local/lib/python2.7/site-packages/silx/gui/plot/items/shape.py", line 81, in _addBackendRenderer
    linebgcolor=self.getLineBgColor())
  File "/mxn/home/nanomax-user/.local/lib/python2.7/site-packages/silx/gui/plot/backends/BackendMatplotlib.py", line 582, in addItem
    self.ax.add_patch(item)
  File "/usr/lib64/python2.7/site-packages/matplotlib/axes.py", line 1570, in add_patch
    self._update_patch_limits(p)
  File "/usr/lib64/python2.7/site-packages/matplotlib/axes.py", line 1591, in _update_patch_limits
    self.transData)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'CompositeGenericTransform'
```

I am running in an ancient environment (over which I have limited control), `silx` is 0.11 but it's Python 2.7 and `matplotlib` 1.2.0. Is this simply a case of updating the environment?

**Comment by vallsv** [comment]
Did you always click outside of the plot axes to zoom?  Or inside the data area?

I am afraid it will be difficult to maintain old versions yes.

Maybe you could have a little more feed back from @t20100

**Comment by alexbjorling** [comment]
Inside the data area

**Comment by alexbjorling** [comment]
OK clearly this is not a silx problem, I guess it's time to move to python3...
