### ISSUE TITLE
NoneType error in addMarginsToLimits

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#2826]
This have to be investigate.

I was playing with left and right axes, removing and creating object randomly.

My code is maybe responsible of that.

```
Traceback (most recent call last):
  File "/users/valls/workspace/test/animated-axes/curves_autozoom2.py", line 103, in __tick
    plot.resetZoom()
  File "/users/valls/workspace/silx.git/build/lib.linux-x86_64-3.7/silx/gui/plot/PlotWidget.py", line 2815, in resetZoom
    self._forceResetZoom(dataMargins=dataMargins)
  File "/users/valls/workspace/silx.git/build/lib.linux-x86_64-3.7/silx/gui/plot/PlotWidget.py", line 2754, in _forceResetZoom
    xmin, xmax, ymin, ymax, ymin2, ymax2))
  File "/users/valls/workspace/silx.git/build/lib.linux-x86_64-3.7/silx/gui/plot/_utils/__init__.py", line 67, in addMarginsToLimits
    yRange = yMax - yMin
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'
```

**Comment by vallsv** [comment]
Was my code.
Then it's fine.
