### ISSUE TITLE
Issue pyside2 & matplotlib

### ISSUE THREAD

**Issue by payno** [silx-kit/silx#2882]
When I try to use PySide2 () and matplotlib () importing PlotWidget ends up with an error:

``` bash
Traceback (most recent call last):
  File "./bootstrap.py", line 271, in <module>
    main(sys.argv)
  File "./bootstrap.py", line 219, in main
    run_file(target, argv)
  File "./bootstrap.py", line 106, in run_file
    execfile(filename, module_globals, module_globals)
  File "./bootstrap.py", line 79, in execfile
    exec(code, globals, locals)
  File "/users_ext/dev/esrf/silx/silx/examples/imageStack.py", line 45, in <module>
    from silx.gui.plot.ImageStack import ImageStack, UrlLoader
  File "/users_ext/dev/esrf/silx/silx/build/lib.linux-x86_64-3.7/silx/gui/plot/__init__.py", line 63, in <module>
    from .PlotWidget import PlotWidget  # noqa
  File "/users_ext/dev/esrf/silx/silx/build/lib.linux-x86_64-3.7/silx/gui/plot/PlotWidget.py", line 50, in <module>
    from .backends.BackendMatplotlib import BackendMatplotlibQt
  File "/users_ext/dev/esrf/silx/silx/build/lib.linux-x86_64-3.7/silx/gui/plot/backends/BackendMatplotlib.py", line 47, in <module>
    from ..matplotlib import FigureCanvasQTAgg
  File "/users_ext/dev/esrf/silx/silx/build/lib.linux-x86_64-3.7/silx/gui/plot/matplotlib/__init__.py", line 90, in <module>
    _configure('Qt5Agg', backend_qt5="PySide2", check=_matplotlib_already_loaded)
  File "/users_ext/dev/esrf/silx/silx/build/lib.linux-x86_64-3.7/silx/gui/plot/matplotlib/__init__.py", line 78, in _configure
    matplotlib.rcParams['backend.qt5'] = backend_qt5
  File "/users/payno/.local/share/virtualenvs/silx_venv_pyside2/lib/python3.7/site-packages/matplotlib/__init__.py", line 808, in __setitem__
    f"{key} is not a valid rc parameter (see rcParams.keys() for "
KeyError: 'backend.qt5 is not a valid rc parameter (see rcParams.keys() for a list of valid parameters)'
```

It looks like 'backend.qt5' is not supported anymore (maybe qt4 is not more maintened and it is why ...)

**Comment by payno** [comment]
comes with matplotlib 3.1.0

**Comment by payno** [comment]
By the way it's look like there is no changelog in matplotlib ?!

**Comment by payno** [comment]
was already fixed by ` if parse_version(matplotlib.__version__) < parse_version('2.2'):` I was not up to date my bad.
