### ISSUE TITLE
[scatter plot] Regular grid breaks the plot in some cases

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#2916]
With Flint, my scan simulator is able to produce data that can break the scatter item.

Yet, I did not try to reproduce the result with silx.

I used axis X and axis Y with the same array (210 points for both, same as the value array)

That's problematic cause after that the plot is not anymore working.

Other visualizations, like irregular grid or interpolation display things or nothing, but do not fail the plot.

That's blocking for me cause, it's easy to reproduce by clicking on all by buttons, for example, to swap X and Y axis, you have pass by a state where both axis point to the same data.

```
CRITICAL:root:Uncaught exception
Traceback (most recent call last):
  File "/users/valls/Software/miniconda3/envs/blissenv/lib/python3.7/site-packages/silx/gui/plot/backends/BackendBase.py", line 361, in postRedisplay
    plot.replot()
  File "/users/valls/Software/miniconda3/envs/blissenv/lib/python3.7/site-packages/silx/gui/plot/PlotWidget.py", line 2713, in replot
    item._update(self._backend)
  File "/users/valls/Software/miniconda3/envs/blissenv/lib/python3.7/site-packages/silx/gui/plot/items/core.py", line 319, in _update
    self._backendRenderer = self._addBackendRenderer(backend)
  File "/users/valls/Software/miniconda3/envs/blissenv/lib/python3.7/site-packages/silx/gui/plot/items/scatter.py", line 453, in _addBackendRenderer
    image[:len(rgbacolors)] = rgbacolors
ValueError: could not broadcast input array from shape (210,4) into shape (196,4)
```

**Comment by vallsv** [comment]
BTW, I did not try to update silx.

**Comment by t20100** [comment]
I can reproduce this by setting a `GRID_SHAPE` visualization parameter that is smaller than the number of points in the scatter plot.
So you probably have an issue on your side.
Anyway, I will make it resilient to this situation by enlarging the grid shape in this case.

**Comment by t20100** [comment]
Code to reproduce:

```
from silx import sx; import numpy
w = sx.scatter(numpy.arange(100), numpy.arange(100), numpy.random.random(100))
item = w.getScatterItem()
item.setVisualizationParameter(item.VisualizationParameter.GRID_SHAPE, (5, 10))
item.setVisualization(item.Visualization.REGULAR_GRID)
```
