### ISSUE TITLE
Exception raised in ColormapDialog

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#2921]
With recent updates of the `ColormapDialog`, I get this error from time to time:
```
Exception ignored in: <bound method ColormapDialog._itemAboutToFinalize of <silx.gui.dialog.ColormapDialog.ColormapDialog object at 0x7f12b196d438>>
Traceback (most recent call last):
  File "/users/tvincent/src/silx/build/lib.linux-x86_64-3.7/silx/gui/dialog/ColormapDialog.py", line 1201, in _itemAboutToFinalize
    self.setItem(None)
  File "/users/tvincent/src/silx/build/lib.linux-x86_64-3.7/silx/gui/dialog/ColormapDialog.py", line 1148, in setItem
    self._invalidateData()
  File "/users/tvincent/src/silx/build/lib.linux-x86_64-3.7/silx/gui/dialog/ColormapDialog.py", line 957, in _invalidateData
    if self.isVisible():
RuntimeError: wrapped C/C++ object of type ColormapDialog has been deleted
```

**Comment by vallsv** [comment]
PyQt or PySide?
Maybe we can check together.
Looks like the dialog receive event after it was closed?

**Comment by vallsv** [comment]
Hmmm... Which is the case most of the time for `_itemAboutToFinalize`, makes sense.
