### ISSUE TITLE
[fit] Exception while fitting curves

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#2952]
Some feedback from Flint.

The following one could be catched and  displayed with a convenient message.
I really think the backtrace is pointless.
![Screenshot from 2020-03-12 11-52-09](https://user-images.githubusercontent.com/7579321/76514471-35c19480-6458-11ea-846f-3acc803f4816.png)

The following one should be investigated. It is maybe due to my integration.
![Screenshot from 2020-03-12 11-44-01](https://user-images.githubusercontent.com/7579321/76514559-5c7fcb00-6458-11ea-8d1a-7e95ff96e447.png)

**Comment by vallsv** [comment]
Here is another traceback.
```
CRITICAL:root:Uncaught exception
Traceback (most recent call last):
  File "/users/valls/Software/miniconda3/envs/blissenv/lib/python3.7/site-packages/silx/gui/plot/actions/fit.py", line 160, in handle_signal
    resetzoom=False)
  File "/users/valls/Software/miniconda3/envs/blissenv/lib/python3.7/site-packages/silx/gui/plot/PlotWidget.py", line 922, in addCurve
    curve.setData(x, y, xerror, yerror, baseline=baseline, copy=copy)
  File "/users/valls/Software/miniconda3/envs/blissenv/lib/python3.7/site-packages/silx/gui/plot/items/curve.py", line 389, in setData
    copy=copy)
  File "/users/valls/Software/miniconda3/envs/blissenv/lib/python3.7/site-packages/silx/gui/plot/items/core.py", line 1411, in setData
    assert len(x) == len(y)
AssertionError
```
- Open a fit widget with a curve
- Estimate, fit, and close it
- Remove everything from the plot
- Open back the fit widget
- Dialog to select a curve -> Cancel it
- The fit dialog was anyway displayed
- Click on fit, here is a traceback

**Comment by vallsv** [comment]
Another one
```
Traceback (most recent call last):
  File "/users/valls/Software/miniconda3/envs/blissenv/lib/python3.7/site-packages/silx/gui/plot/actions/fit.py", line 104, in <lambda>
    qt.QTimer.singleShot(10, lambda: self._initFit(window))
  File "/users/valls/Software/miniconda3/envs/blissenv/lib/python3.7/site-packages/silx/gui/plot/actions/fit.py", line 127, in _initFit
    self.legend = item.getName()
AttributeError: 'NoneType' object has no attribute 'getName'
```

**Comment by t20100** [comment]
Is it with the master branch or a tagged version?

**Comment by vallsv** [comment]
I am pretty sure both

**Comment by vallsv** [comment]
But the last tests was with the tagger version i think. Cause i was testing the integration in Flint.

**Comment by t20100** [comment]
I didn't manage to reproduce the 2nd issue (https://github.com/silx-kit/silx/issues/2952#issuecomment-598252497) neither with the master tip nor with PR #2960

**Comment by t20100** [comment]
Last issue (https://github.com/silx-kit/silx/issues/2952#issuecomment-598265337) reproduced by clearing the plot *while* the curve selection widget is displayed and fixed.
