### ISSUE TITLE
Silx incompatible with Matplotlib 3.2.1

### ISSUE THREAD

**Issue by lucarebuffi** [silx-kit/silx#2966]
After upgrading matplotlib I have this issue:

```
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/silx/gui/plot/matplotlib/__init__.py:59: MatplotlibDeprecationWarning: The 'warn' parameter of use() is deprecated since Matplotlib 3.1 and will be removed in 3.3.  If any parameter follows 'warn', they should be pass as keyword, not positionally.
  matplotlib.use(backend, warn=warn, force=force)
Traceback (most recent call last):
  File "/Users/lrebuffi/Documents/Workspace/Oasys/OASYS1/oasys/canvas/__main__.py", line 42, in <module>
    from oasys.canvas.mainwindow import OASYSMainWindow
  File "/Users/lrebuffi/Documents/Workspace/Oasys/OASYS1/oasys/canvas/mainwindow.py", line 35, in <module>
    from oasys.widgets.gui import OptionDialog
  File "/Users/lrebuffi/Documents/Workspace/Oasys/OASYS1/oasys/widgets/gui.py", line 167, in <module>
    from silx.gui.plot.backends.BackendMatplotlib import BackendMatplotlibQt
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/silx/gui/plot/__init__.py", line 63, in <module>
    from .PlotWidget import PlotWidget  # noqa
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/silx/gui/plot/PlotWidget.py", line 55, in <module>
    from . import matplotlib
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/silx/gui/plot/matplotlib/__init__.py", line 67, in <module>
    _matplotlib_use('Qt5Agg', warn=True, force=False)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/silx/gui/plot/matplotlib/__init__.py", line 59, in _matplotlib_use
    matplotlib.use(backend, warn=warn, force=force)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/cbook/deprecation.py", line 296, in wrapper
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/cbook/deprecation.py", line 358, in wrapper
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/__init__.py", line 1280, in use
    from matplotlib import pyplot as plt
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/pyplot.py", line 40, in <module>
    from matplotlib.figure import Figure, figaspect
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/figure.py", line 20, in <module>
    from matplotlib import backends, docstring, projections
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/projections/__init__.py", line 4, in <module>
    from mpl_toolkits.mplot3d import Axes3D
  File "/Users/lrebuffi/Library/Python/3.7/lib/python/site-packages/mpl_toolkits/mplot3d/__init__.py", line 1, in <module>
    from .axes3d import Axes3D
  File "/Users/lrebuffi/Library/Python/3.7/lib/python/site-packages/mpl_toolkits/mplot3d/axes3d.py", line 42, in <module>
    class Axes3D(Axes):
  File "/Users/lrebuffi/Library/Python/3.7/lib/python/site-packages/mpl_toolkits/mplot3d/axes3d.py", line 52, in Axes3D
    azim=-60, elev=30, zscale=None, sharez=None, proj_type='persp',
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/docstring.py", line 116, in dedent_interpd
    return interpd(func)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/docstring.py", line 40, in __call__
    func.__doc__ %= self.params
KeyError: 'scale'
```

**Comment by t20100** [comment]
For the first line:
```/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/silx/gui/plot/matplotlib/__init__.py:59: MatplotlibDeprecationWarning: The 'warn' parameter of use() is deprecated since Matplotlib 3.1 and will be removed in 3.3.  If any parameter follows 'warn', they should be pass as keyword, not positionally.
  matplotlib.use(backend, warn=warn, force=force)
```

This has been fixed in PR #2890, and it is available in `v0.13.0b0` so you should get it with `pip install --pre`.

For the reset, I don't see where it comes from.
I could not reproduce, neither the tip of the master nor `v0.12.0` 
Which version of `silx` do you use?

**Comment by lucarebuffi** [comment]
0.12.0

**Comment by vallsv** [comment]
Do you use custom things in `matplotlib.rc_params`?

**Comment by lucarebuffi** [comment]
matplotlib.rcParams['axes.formatter.useoffset']='False'

**Comment by vallsv** [comment]
BTW, it is now applied by default to silx plots.
But then i don't think this causes the problem.

**Comment by t20100** [comment]
Looking further at it, it looks you have conflicting versions installed  `/Users/lrebuffi/Library/Python/3.7/lib/python/site-packages/mpl_toolkits/` and `/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib`

See https://github.com/matplotlib/matplotlib/issues/16668#issuecomment-594980061

**Comment by lucarebuffi** [comment]
Oh, thank you, I didn't see that. Sorry for the waste of time!

Cheers,

L.
