### ISSUE TITLE
[plot] Robustness on Shape.setPoints

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#2992]
It would be good to have a stronger setter method here.
As the computation is done by the backend, setting the data in the setter should help a lot to debug the code, else the problem occur at the rendering time.

- Any input is allowed (no type, size, dim check)
- I noticed, in polygon mode, the array can't be empty
- I also noticed issues on polylines

Like:
```
Traceback (most recent call last):
  File "/home/ordinateur/workspace/silx.git/build/lib.linux-x86_64-3.8/silx/gui/plot/backends/BackendBase.py", line 357, in postRedisplay
    plot.replot()
  File "/home/ordinateur/workspace/silx.git/build/lib.linux-x86_64-3.8/silx/gui/plot/PlotWidget.py", line 2736, in replot
    item._update(self._backend)
  File "/home/ordinateur/workspace/silx.git/build/lib.linux-x86_64-3.8/silx/gui/plot/items/core.py", line 333, in _update
    self._backendRenderer = self._addBackendRenderer(backend)
  File "/home/ordinateur/workspace/silx.git/build/lib.linux-x86_64-3.8/silx/gui/plot/items/shape.py", line 70, in _addBackendRenderer
    x, y = points.T[0], points.T[1]
IndexError: index 0 is out of bounds for axis 0 with size 0
```

**Comment by t20100** [comment]
The `Shape` object was done at minimum, so I'm not surprise.
Another option is to make specific items of for different shapes (rect, polygone, circle...)
