### ISSUE TITLE
[profile] isdeleted() argument must not be None

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#3003]
We really should get ride of `RegionOfInterest.__del__`, but in the mid time we could fix that exception.
```
Exception ignored in: <function RegionOfInterest.__del__ at 0x7ff672d1cdc0>
Traceback (most recent call last):
  File "/home/ordinateur/workspace/silx.git/build/lib.linux-x86_64-3.8/silx/gui/plot/items/roi.py", line 149, in __del__
    self._removePlotItems()
  File "/home/ordinateur/workspace/silx.git/build/lib.linux-x86_64-3.8/silx/gui/plot/items/roi.py", line 528, in _removePlotItems
    if inspect.isValid(plot):
  File "/home/ordinateur/workspace/silx.git/build/lib.linux-x86_64-3.8/silx/gui/qt/inspect.py", line 62, in isValid
    return not _isdeleted(obj)
TypeError: isdeleted() argument 1 must be sip.simplewrapper, not None
```

**Comment by vallsv** [comment]
This was related to #2988, i fixed it on this PR
