### ISSUE TITLE
Nightly debian build failed

### ISSUE THREAD

**Issue by kif** [silx-kit/silx#3021]
Here is the error message:
```
======================================================================
ERROR: testAttributeAlreadyExists (silx.io.test.test_dictdump.TestDictToH5)
A duplicated attribute warns if overwriting is not enabled
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tester/silx/build/lib.linux-x86_64-3.7/silx/io/test/test_dictdump.py", line 181, in testAttributeAlreadyExists
    with h5py.File(mem, "w") as h5file:
  File "/usr/lib/python3/dist-packages/h5py/_hl/files.py", line 309, in __init__
    name = filename_encode(name)
  File "/usr/lib/python3/dist-packages/h5py/_hl/compat.py", line 111, in filename_encode
    filename = fspath(filename)
TypeError: expected str, bytes or os.PathLike object, not _io.BytesIO

======================================================================
ERROR: testAttributeValues (silx.io.test.test_dictdump.TestDictToH5)
Any NX data types can be used
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tester/silx/build/lib.linux-x86_64-3.7/silx/io/test/test_dictdump.py", line 162, in testAttributeValues
    with h5py.File(mem, "w") as h5file:
  File "/usr/lib/python3/dist-packages/h5py/_hl/files.py", line 309, in __init__
    name = filename_encode(name)
  File "/usr/lib/python3/dist-packages/h5py/_hl/compat.py", line 111, in filename_encode
    filename = fspath(filename)
TypeError: expected str, bytes or os.PathLike object, not _io.BytesIO

======================================================================
ERROR: testAttributes (silx.io.test.test_dictdump.TestDictToH5)
Any kind of attribute can be described
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tester/silx/build/lib.linux-x86_64-3.7/silx/io/test/test_dictdump.py", line 126, in testAttributes
    with h5py.File(mem, "w") as h5file:
  File "/usr/lib/python3/dist-packages/h5py/_hl/files.py", line 309, in __init__
    name = filename_encode(name)
  File "/usr/lib/python3/dist-packages/h5py/_hl/compat.py", line 111, in filename_encode
    filename = fspath(filename)
TypeError: expected str, bytes or os.PathLike object, not _io.BytesIO

======================================================================
ERROR: testFlatDict (silx.io.test.test_dictdump.TestDictToH5)
Description of a tree with a single level of keys
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tester/silx/build/lib.linux-x86_64-3.7/silx/io/test/test_dictdump.py", line 194, in testFlatDict
    with h5py.File(mem, "w") as h5file:
  File "/usr/lib/python3/dist-packages/h5py/_hl/files.py", line 309, in __init__
    name = filename_encode(name)
  File "/usr/lib/python3/dist-packages/h5py/_hl/compat.py", line 111, in filename_encode
    filename = fspath(filename)
TypeError: expected str, bytes or os.PathLike object, not _io.BytesIO

======================================================================
ERROR: testKeyOrder (silx.io.test.test_dictdump.TestDictToH5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tester/silx/build/lib.linux-x86_64-3.7/silx/io/test/test_dictdump.py", line 143, in testKeyOrder
    with h5py.File(mem, "w") as h5file:
  File "/usr/lib/python3/dist-packages/h5py/_hl/files.py", line 309, in __init__
    name = filename_encode(name)
  File "/usr/lib/python3/dist-packages/h5py/_hl/compat.py", line 111, in filename_encode
    filename = fspath(filename)
TypeError: expected str, bytes or os.PathLike object, not _io.BytesIO

======================================================================
ERROR: testAttributeValues (silx.io.test.test_dictdump.TestDictToNx)
Any NX data types can be used
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tester/silx/build/lib.linux-x86_64-3.7/silx/io/test/test_dictdump.py", line 249, in testAttributeValues
    with h5py.File(mem, "w") as h5file:
  File "/usr/lib/python3/dist-packages/h5py/_hl/files.py", line 309, in __init__
    name = filename_encode(name)
  File "/usr/lib/python3/dist-packages/h5py/_hl/compat.py", line 111, in filename_encode
    filename = fspath(filename)
TypeError: expected str, bytes or os.PathLike object, not _io.BytesIO

======================================================================
ERROR: testAttributes (silx.io.test.test_dictdump.TestDictToNx)
Any kind of attribute can be described
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tester/silx/build/lib.linux-x86_64-3.7/silx/io/test/test_dictdump.py", line 213, in testAttributes
    with h5py.File(mem, "w") as h5file:
  File "/usr/lib/python3/dist-packages/h5py/_hl/files.py", line 309, in __init__
    name = filename_encode(name)
  File "/usr/lib/python3/dist-packages/h5py/_hl/compat.py", line 111, in filename_encode
    filename = fspath(filename)
TypeError: expected str, bytes or os.PathLike object, not _io.BytesIO

======================================================================
ERROR: testFlatDict (silx.io.test.test_dictdump.TestDictToNx)
Description of a tree with a single level of keys
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tester/silx/build/lib.linux-x86_64-3.7/silx/io/test/test_dictdump.py", line 269, in testFlatDict
    with h5py.File(mem, "w") as h5file:
  File "/usr/lib/python3/dist-packages/h5py/_hl/files.py", line 309, in __init__
    name = filename_encode(name)
  File "/usr/lib/python3/dist-packages/h5py/_hl/compat.py", line 111, in filename_encode
    filename = fspath(filename)
TypeError: expected str, bytes or os.PathLike object, not _io.BytesIO

======================================================================
ERROR: testKeyOrder (silx.io.test.test_dictdump.TestDictToNx)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tester/silx/build/lib.linux-x86_64-3.7/silx/io/test/test_dictdump.py", line 230, in testKeyOrder
    with h5py.File(mem, "w") as h5file:
  File "/usr/lib/python3/dist-packages/h5py/_hl/files.py", line 309, in __init__
    name = filename_encode(name)
  File "/usr/lib/python3/dist-packages/h5py/_hl/compat.py", line 111, in filename_encode
    filename = fspath(filename)
TypeError: expected str, bytes or os.PathLike object, not _io.BytesIO
```

**Comment by kif** [comment]
Probably related to #3013 or #3017

**Comment by t20100** [comment]
Might be related to the version of `h5py`?

**Comment by t20100** [comment]
This is it: `BytesIO` support was introduced in `h5py` 2.9.0 (see https://github.com/h5py/h5py/releases/tag/2.9.0), while debian 10 provides 2.8.0...

**Comment by t20100** [comment]
Dropping debian 10 is probably a bit early ;) so we'll have to remove the use of `BytesIO`.
