### ISSUE TITLE
Nightly debian build failed

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#3030]
Those tests fail:
```
======================================================================
ERROR: testAttributeValues (silx.io.test.test_dictdump.TestDictToH5)
Any NX data types can be used
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tester/silx/build/lib.linux-x86_64-3.7/silx/io/test/test_dictdump.py", line 159, in testAttributeValues
    dictdump.dicttoh5(ddict, h5file)
  File "/home/tester/silx/build/lib.linux-x86_64-3.7/silx/io/dictdump.py", line 282, in dicttoh5
    h5f[h5path + key[0]].attrs[key[1]] = treedict[key]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/lib/python3/dist-packages/h5py/_hl/attrs.py", line 95, in __setitem__
    self.create(name, data=value, dtype=base.guess_dtype(value))
  File "/usr/lib/python3/dist-packages/h5py/_hl/attrs.py", line 171, in create
    htype = h5t.py_create(original_dtype, logical=True)
  File "h5py/h5t.pyx", line 1611, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1633, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1694, in h5py.h5t.py_create
TypeError: No conversion path for dtype: dtype('<U3')

======================================================================
ERROR: testAttributeValues (silx.io.test.test_dictdump.TestDictToNx)
Any NX data types can be used
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tester/silx/build/lib.linux-x86_64-3.7/silx/io/test/test_dictdump.py", line 249, in testAttributeValues
    dictdump.dicttonx(ddict, h5file)
  File "/home/tester/silx/build/lib.linux-x86_64-3.7/silx/io/dictdump.py", line 352, in dicttonx
    create_dataset_args=create_dataset_args,
  File "/home/tester/silx/build/lib.linux-x86_64-3.7/silx/io/dictdump.py", line 282, in dicttoh5
    h5f[h5path + key[0]].attrs[key[1]] = treedict[key]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/lib/python3/dist-packages/h5py/_hl/attrs.py", line 95, in __setitem__
    self.create(name, data=value, dtype=base.guess_dtype(value))
  File "/usr/lib/python3/dist-packages/h5py/_hl/attrs.py", line 171, in create
    htype = h5t.py_create(original_dtype, logical=True)
  File "h5py/h5t.pyx", line 1611, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1633, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1694, in h5py.h5t.py_create
TypeError: No conversion path for dtype: dtype('<U3')
```

**Comment by vallsv** [comment]
Really sad... I think it is because i used python list for tests instead of H5PY special type. Nice to catch it.

I think tests are good, it have to be handled by the implementation.
Or this tests have to be skipped for this version of h5py.
What do you think?

**Comment by t20100** [comment]
I think we should fully support debian10.

**Comment by vallsv** [comment]
remember me the h5py version please? I will take a look.

**Comment by t20100** [comment]
It's `h5py 2.8.0`, I already downgraded, I can have a look.
