### ISSUE TITLE
Cannot synchronize ROIs between themself

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#3071]
I have an issue with synchronizing ROIs ending in infinite recursion.
Checking that the value doesn't change when being set should fix it.

In my case it is between different plots, but here is a simple example to reproduce it with a single one:
```
from silx.gui import qt
from silx.gui.plot import Plot2D
from silx.gui.plot.tools.roi import RegionOfInterestManager
from silx.gui.plot.items.roi import RectangleROI

import numpy

app = qt.QApplication([])

roi1 = RectangleROI()
roi2 = RectangleROI()

def roi1Updated():
    roi2.setCenter(roi1.getCenter())
roi1.sigRegionChanged.connect(roi1Updated)

def roi2Updated():
    roi1.setCenter(roi2.getCenter())
roi2.sigRegionChanged.connect(roi2Updated)

roi1.setCenter((3, 3))

w = Plot2D()
w.addImage(numpy.arange(100).reshape(10, 10))
w.show()

manager = RegionOfInterestManager(w)
manager.setColor('pink')
manager.addRoi(roi1)
manager.addRoi(roi2)

app.exec_()
```

Leading to:
```
Traceback (most recent call last):
  File "silx/test_roi.py", line 17, in roi1Updated
    roi2.setCenter(roi1.getCenter())
  File "silx/gui/plot/items/roi.py", line 1303, in setCenter
    self.setGeometry(center=position, size=size)
  File "silx/gui/plot/items/roi.py", line 1320, in setGeometry
    with utils.blockSignals(self._handleBottomLeft):
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "silx/gui/utils/__init__.py", line 43, in blockSignals
    blocked = [(obj, obj.blockSignals(True)) for obj in objs]
RecursionError: maximum recursion depth exceeded
```

**Comment by vallsv** [comment]
You have to block respectively roi1 and roi2 in your example.

**Comment by vallsv** [comment]
Which make me think that in case of profiles, blocking a ROI will break the update of the other shapes.
What a life...

**Comment by vallsv** [comment]
Here is an updated version. everything looks fine.
```
from silx.gui import qt
from silx.gui.plot import Plot2D
from silx.gui.plot.tools.roi import RegionOfInterestManager
from silx.gui.plot.items.roi import RectangleROI
from silx.gui import utils

import numpy

app = qt.QApplication([])

roi1 = RectangleROI()
roi2 = RectangleROI()


def roi1Updated():
    with utils.blockSignals(roi2):
        roi2.setCenter(roi1.getCenter())


roi1.sigRegionChanged.connect(roi1Updated)


def roi2Updated():
    with utils.blockSignals(roi1):
        roi1.setCenter(roi2.getCenter())


roi2.sigRegionChanged.connect(roi2Updated)

roi1.setCenter((3, 3))
roi2.setSize((10, 10))
roi1.setSize((5, 5))
roi1.setEditable(True)


w = Plot2D()
w.addImage(numpy.arange(100).reshape(10, 10))
w.show()

manager = RegionOfInterestManager(w)
manager.setColor("pink")
manager.addRoi(roi1)
manager.addRoi(roi2)

app.exec_()
```

**Comment by vallsv** [comment]
But in this case, it means you own the ROIs.

If other part of your application except the receive the signal, you can't do that or you have to emit the signal manually.

That is why we also have
```
from silx.gui import utils
utils.LockReentrant
```
which can be used like that:
```
l = utils.LockReentrant() # Global

...
if not l.locked():
    with l:
        roi1.setCenter()
```

**Comment by t20100** [comment]
I think it would be nicer if the methods checks that there is an actual change, so you don't take care about it later.
I will have a look at it.

**Comment by vallsv** [comment]
Sure, you can reduce the propagation, but in case of oscillation or non convergent functions you will anyway have the problem.

**Comment by t20100** [comment]
Indeed, but that's not what is limiting me here, I have different ROIs in different plot that are all synchronized so the propagation would stop quickly.
