### ISSUE TITLE
[profile] Exception while processing a live scatter

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#3096]
Flint exception. Still have to investigate.

```
ERROR 2020-06-05 12:52:36,156 flint.output: ERROR:silx.gui.plot.tools.profile.manager:Error while computing profilea [01:27]                  
ERROR 2020-06-05 12:52:36,192 flint.output: Traceback (most recent call last):                            20                                  
ERROR 2020-06-05 12:52:36,192 flint.output:   File "/home/ordinateur/Software/miniconda3/envs/blissenv/lib/python3.7/site-packages/silx/gui/pl
ot/tools/profile/manager.py", line 110, in run                                                                                                
ERROR 2020-06-05 12:52:36,194 flint.output:     profileData = self._roi.computeProfile(self._item)                                            
ERROR 2020-06-05 12:52:36,200 flint.output:   File "/home/ordinateur/Software/miniconda3/envs/blissenv/lib/python3.7/site-packages/silx/gui/plot/tools/profile/rois.py", line 794, in computeProfile
ERROR 2020-06-05 12:52:36,200 flint.output:     profile = self._computeProfile(item, x0, y0, x1, y1)                               
ERROR 2020-06-05 12:52:36,201 flint.output:   File "/home/ordinateur/Software/miniconda3/envs/blissenv/lib/python3.7/site-packages/silx/gui/pl
ot/tools/profile/rois.py", line 750, in _computeProfile                                                                                       ERROR 2020-06-05 12:52:36,203 flint.output:     interpolator = future.result()                                                                
ERROR 2020-06-05 12:52:36,203 flint.output:   File "/home/ordinateur/Software/miniconda3/envs/blissenv/lib/python3.7/concurrent/futures/_base.
py", line 433, in result                                                                                                           
ERROR 2020-06-05 12:52:36,204 flint.output:     raise CancelledError()                                                                        ERROR 2020-06-05 12:52:36,208 flint.output: concurrent.futures._base.CancelledError                                                           
ERROR 2020-06-05 12:52:36,642 flint.output: ERROR:silx.gui.plot.tools.profile.manager:Error while computing profile       7        
ERROR 2020-06-05 12:52:36,642 flint.output: Traceback (most recent call last):                                                     
ERROR 2020-06-05 12:52:36,674 flint.output:   File "/home/ordinateur/Software/miniconda3/envs/blissenv/lib/python3.7/site-packages/silx/gui/plot/tools/profile/manager.py", line 110, in run
ERROR 2020-06-05 12:52:36,674 flint.output:     profileData = self._roi.computeProfile(self._item)                                            
ERROR 2020-06-05 12:52:36,676 flint.output:   File "/home/ordinateur/Software/miniconda3/envs/blissenv/lib/python3.7/site-packages/silx/gui/plot/tools/profile/rois.py", line 794, in computeProfile
ERROR 2020-06-05 12:52:36,717 flint.output:     profile = self._computeProfile(item, x0, y0, x1, y1)                      8                   ERROR 2020-06-05 12:52:36,718 flint.output:   File "/home/ordinateur/Software/miniconda3/envs/blissenv/lib/python3.7/site-packages/silx/gui/pl
ot/tools/profile/rois.py", line 750, in _computeProfile
ERROR 2020-06-05 12:52:36,719 flint.output:     interpolator = future.result()                                                                
ERROR 2020-06-05 12:52:36,727 flint.output:   File "/home/ordinateur/Software/miniconda3/envs/blissenv/lib/python3.7/concurrent/futures/_base.
py", line 433, in result
ERROR 2020-06-05 12:52:36,727 flint.output:     raise CancelledError()                                                                        
ERROR 2020-06-05 12:52:36,727 flint.output: concurrent.futures._base.CancelledError                                                           
```

**Comment by vallsv** [comment]
It looks to be obvious, and on my side.
```
ERROR 2020-06-05 12:53:12,044 flint.output: ERROR:silx.gui.plot.tools.profile.manager:Error while computing profile
ERROR 2020-06-05 12:53:12,047 flint.output: Traceback (most recent call last):
ERROR 2020-06-05 12:53:12,048 flint.output:   File "/home/ordinateur/Software/miniconda3/envs/blissenv/lib/python3.7/site-packages/silx/gui/plot/tools/profile/manager.py", line 110, in run
ERROR 2020-06-05 12:53:12,048 flint.output:     profileData = self._roi.computeProfile(self._item)
ERROR 2020-06-05 12:53:12,056 flint.output:   File "/home/ordinateur/Software/miniconda3/envs/blissenv/lib/python3.7/site-packages/silx/gui/plot/tools/profile/rois.py", line 812, in computeProfile
ERROR 2020-06-05 12:53:12,056 flint.output:     title = _relabelAxes(plot, title)
ERROR 2020-06-05 12:53:12,057 flint.output:   File "/home/ordinateur/Software/miniconda3/envs/blissenv/lib/python3.7/site-packages/silx/gui/plot/tools/profile/rois.py", line 56, in _relabelAxes
ERROR 2020-06-05 12:53:12,058 flint.output:     xLabel = plot.getXAxis().getLabel()
ERROR 2020-06-05 12:53:12,059 flint.output: AttributeError: 'NoneType' object has no attribute 'getXAxis'
```
I progress.

**Comment by vallsv** [comment]
Or the item was already removed from the plot... Hmmm.

**Comment by vallsv** [comment]
That's too complex to reuse the items between 2 updates. So i clean up the plot between two data reception.

I don't know what to do. Maybe we have to abort the profile ?

Then in this case no profiles will be displayed until the end.

**Comment by vallsv** [comment]
I will try to reach the plot before processing the concurrent computation of the scatter data. It's maybe the key point here. There is an API issue anyway, i think.
