### ISSUE TITLE
[math] FFT test fails with FFTW 

### ISSUE THREAD

**Issue by pierrepaleo** [silx-kit/silx#3121]
FFT with backend fftw fails with C2C transform. 
AFAIK nothing was changed since version 0.12. The only thing I see is numpy having changed its internal FFT backend ([pocketFFT](https://numpy.org/devdocs/release/1.17.0-notes.html)) since `1.17.0`, but then tests should fail with other backends (not only fftw).

Anyway the metric is Maximum Absolute Difference (`max_i |x_i - y_i|`). 
It is not surprising to see `MAD = 0.3` on float32 precision, I wonder why we did not have this issue before.

```bash
======================================================================
FAIL: test_fftw (silx.math.fft.test.test_fft.TestFFT) (trdim='2D', mode='C2C', size=(512, 512))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/users/kieffer/workspace-400/silx/build/lib.linux-x86_64-3.7/silx/math/fft/test/test_fft.py", line 144, in __run_tests
    self.__test(backend, trdim, mode, size, **extra_args)
  File "/users/kieffer/workspace-400/silx/build/lib.linux-x86_64-3.7/silx/math/fft/test/test_fft.py", line 182, in __test
    "FFT %s:%s, MAE(%s, numpy) = %f" % (mode, trdim, backend, mae)
AssertionError: False is not true : FFT C2C:2D, MAE(fftw, numpy) = 0.302643

======================================================================
FAIL: test_fftw (silx.math.fft.test.test_fft.TestFFT) (trdim='2D', mode='C2C', size=(512, 511))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/users/kieffer/workspace-400/silx/build/lib.linux-x86_64-3.7/silx/math/fft/test/test_fft.py", line 144, in __run_tests
    self.__test(backend, trdim, mode, size, **extra_args)
  File "/users/kieffer/workspace-400/silx/build/lib.linux-x86_64-3.7/silx/math/fft/test/test_fft.py", line 182, in __test
    "FFT %s:%s, MAE(%s, numpy) = %f" % (mode, trdim, backend, mae)
AssertionError: False is not true : FFT C2C:2D, MAE(fftw, numpy) = 0.302643

======================================================================
FAIL: test_fftw (silx.math.fft.test.test_fft.TestFFT) (trdim='2D', mode='C2C', size=(511, 512))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/users/kieffer/workspace-400/silx/build/lib.linux-x86_64-3.7/silx/math/fft/test/test_fft.py", line 144, in __run_tests
    self.__test(backend, trdim, mode, size, **extra_args)
  File "/users/kieffer/workspace-400/silx/build/lib.linux-x86_64-3.7/silx/math/fft/test/test_fft.py", line 182, in __test
    "FFT %s:%s, MAE(%s, numpy) = %f" % (mode, trdim, backend, mae)
AssertionError: False is not true : FFT C2C:2D, MAE(fftw, numpy) = 0.302643

======================================================================
FAIL: test_fftw (silx.math.fft.test.test_fft.TestFFT) (trdim='2D', mode='C2C', size=(511, 511))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/users/kieffer/workspace-400/silx/build/lib.linux-x86_64-3.7/silx/math/fft/test/test_fft.py", line 144, in __run_tests
    self.__test(backend, trdim, mode, size, **extra_args)
  File "/users/kieffer/workspace-400/silx/build/lib.linux-x86_64-3.7/silx/math/fft/test/test_fft.py", line 182, in __test
    "FFT %s:%s, MAE(%s, numpy) = %f" % (mode, trdim, backend, mae)
AssertionError: False is not true : FFT C2C:2D, MAE(fftw, numpy) = 0.302643
```

**Comment by t20100** [comment]
Closed by #3122 on branch 0.13.
