### ISSUE TITLE
ValueError: Axis limits cannot be NaN or Inf

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#3174]
Here is an issue from Flint with some curve using a monitor containing a 0.
```
Traceback (most recent call last):
  File "/users/valls/workspace/bliss.git/bliss/flint/widgets/utils/refresh_helper.py", line 55, in __update
    self.__aggregator.flush()
  File "/users/valls/workspace/bliss.git/bliss/flint/utils/signalutils.py", line 105, in flush
    callback(*args, **kwargs)
  File "/users/valls/workspace/bliss.git/bliss/flint/widgets/curve_plot.py", line 388, in __structureChanged
    self.__redrawAllScans()
  File "/users/valls/workspace/bliss.git/bliss/flint/widgets/curve_plot.py", line 643, in __redrawAllScans
    self.__redrawScan(currentScan)
  File "/users/valls/workspace/bliss.git/bliss/flint/widgets/curve_plot.py", line 684, in __redrawScan
    self.__updatePlotItem(item, scan)
  File "/users/valls/workspace/bliss.git/bliss/flint/widgets/curve_plot.py", line 870, in __updatePlotItem
    self.__updatePlotZoom(updateZoomNow)
  File "/users/valls/workspace/bliss.git/bliss/flint/widgets/curve_plot.py", line 874, in __updatePlotZoom
    self.__view.plotUpdated()
  File "/users/valls/workspace/bliss.git/bliss/flint/widgets/utils/view_helper.py", line 55, in plotUpdated
    self.__plot.resetZoom()
  File "/users/valls/Software/miniconda3/envs/blissenv/lib/python3.7/site-packages/silx/gui/plot/PlotWidget.py", line 2890, in resetZoom
    self._forceResetZoom(dataMargins=dataMargins)
  File "/users/valls/Software/miniconda3/envs/blissenv/lib/python3.7/site-packages/silx/gui/plot/PlotWidget.py", line 2854, in _forceResetZoom
    self.setLimits(*newLimits)
  File "/users/valls/Software/miniconda3/envs/blissenv/lib/python3.7/site-packages/silx/gui/plot/PlotWidget.py", line 2321, in setLimits
    self._backend.setLimits(xmin, xmax, ymin, ymax, y2min, y2max)
  File "/users/valls/Software/miniconda3/envs/blissenv/lib/python3.7/site-packages/silx/gui/plot/backends/BackendMatplotlib.py", line 1052, in setLimits
    self.ax2.set_ylim(min(y2min, y2max), max(y2min, y2max))
  File "/users/valls/Software/miniconda3/envs/blissenv/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 3622, in set_ylim
    bottom = self._validate_converted_limits(bottom, self.convert_yunits)
  File "/users/valls/Software/miniconda3/envs/blissenv/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 3158, in _validate_converted_limits
    raise ValueError("Axis limits cannot be NaN or Inf")
ValueError: Axis limits cannot be NaN or Inf
```

Here is the content of `xmin, xmax, ymin, ymax, y2min, y2max`
```
(-0.02, 1.02, -inf, inf, -inf, inf)
```
It would be nice to filter inf?

**Comment by vallsv** [comment]
Nonetheless i don't know why both min and max of y1 is inf here. With my data, only one side should be inf.

**Comment by t20100** [comment]
No matter of the data, when it reaches matplotlib in should not be `inf`... do you have some data to reproduce that ?

**Comment by vasole** [comment]
Monitor data have to be filtered at the application side prior to perform the normalization.

**Comment by t20100** [comment]
Yes, but there is/should be some defensive testing at the `silx` level.

**Comment by vasole** [comment]
Like ignoring the request to set the limits without raising an exception but a warning?

**Comment by vallsv** [comment]
I will try to reproduce it with pure silx components. For now i just have 2 curves, and 1 with inf values. But there is other objects in the scene.

**Comment by t20100** [comment]
@vasole yes, to me it is similar to handling negative values with log scale axes, just discard those and log a warning.

**Comment by t20100** [comment]
How to reproduce:
```
from silx import sx; import numpy                                       
sx.plot(numpy.arange(4), numpy.array([0, 1, 2, float('inf')]))
```

**Comment by t20100** [comment]
It's funny we didn't had this issue so far...

**Comment by vallsv** [comment]
Could be part of a bug fix release.

**Comment by vasole** [comment]
Well, since matplotlib is rising a exception it was not needed to handle it at our side. Basically every application is/was aware thus making sure the behavior was correct prior to set the limits.

**Comment by vallsv** [comment]
You mean filtering HDF5 raw data before displaying it?

**Comment by vasole** [comment]
When you are using a monitor you have to get the indices of the non-zero monitor values and send to the plot the x values and the normalized y values of those indices. Handling the use of monitors at the plot side (as old Newplot was doing) was more complex than making a "dumb" plotting widget that only know about showing x and y values and putting the responsibility on the plot caller.

**Comment by t20100** [comment]
This is a general issue: any curve data with infinite values no matter where it comes from will raise an exception. That should be avoided... and it's easy to do.

**Comment by vasole** [comment]
Setting the limits to infinity is what raises an exception.

Matplotlib has no problem at all showing the curve you have shown.

![image](https://user-images.githubusercontent.com/5636251/91437820-c35c3980-e86a-11ea-971e-6ec1d1cdadb2.png)

![image](https://user-images.githubusercontent.com/5636251/91437883-d7a03680-e86a-11ea-832e-cc63effff3ab.png)

**Comment by vallsv** [comment]
From my backtrace, silx set itself the limits to infinite.

**Comment by t20100** [comment]
Yes, but silx has some problem.
To me it is an expected behavior to raise an exception if on calls `setLimits` with infinite values and that should not change, but it is a bug if this exception is raised when one calls `PlotWidget.addCurve` with data containing infinite values.

**Comment by vasole** [comment]
The silx calculation of the limits then is buggy.

**Comment by t20100** [comment]
Yes, it ignores NaN but not `inf`, that's the issue.

**Comment by t20100** [comment]
I made a fix, I had some tests and make a PR.
