### ISSUE TITLE
ModuleNotFoundError: No module named 'concurrent.futures'; 'concurrent' is not a package

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#3182]
Fun issue, no idea why it happens now on my machine.

This avoid to launch Flint with OpenGL, so it is quite annoying.

```
In [1]: import silx.gui.utils.glutils              
   ...: silx.gui.utils.glutils.isOpenGLAvailable()                                                                                                                                                                                                   
['/users/valls/Software/miniconda3/envs/silxenv/bin/python', '/users/valls/workspace/silx.git/build/lib.linux-x86_64-3.7/silx/gui/utils/glutils.py', '2', '1']
Traceback (most recent call last):
  File "/users/valls/workspace/silx.git/build/lib.linux-x86_64-3.7/silx/gui/utils/glutils.py", line 30, in <module>
    import subprocess
  File "/users/valls/Software/miniconda3/envs/silxenv/lib/python3.7/subprocess.py", line 50, in <module>
    import signal
  File "/users/valls/workspace/silx.git/build/lib.linux-x86_64-3.7/silx/gui/utils/signal.py", line 32, in <module>
    from silx.gui.utils import concurrent
  File "/users/valls/workspace/silx.git/build/lib.linux-x86_64-3.7/silx/gui/utils/concurrent.py", line 35, in <module>
    from concurrent.futures import Future
  File "/users/valls/workspace/silx.git/build/lib.linux-x86_64-3.7/silx/gui/utils/concurrent.py", line 35, in <module>
    from concurrent.futures import Future
ModuleNotFoundError: No module named 'concurrent.futures'; 'concurrent' is not a package
Out[1]: <_isOpenGLAvailableResult: False, "Qt OpenGL widget error: retcode=1, error=b''">
```

**Comment by t20100** [comment]
From what I tested, it is an issue with python 3.7 and 3.8 but not with 3.5.
