### ISSUE TITLE
CI: tests breaks with h5py 3.0rc1

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#3218]
Tests fails for both Linux and Windows with the following message with h5py3.0rc1:
```
======================================================================

ERROR: testArrayUnicode (silx.gui.data.test.test_textformatter.TestTextFormatterWithH5py)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/silx/gui/data/test/test_textformatter.py", line 170, in testArrayUnicode

    result = self.formatter.toString(d[()], dtype=d.dtype)

  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/silx/gui/data/TextFormatter.py", line 299, in toString

    text = [self.toString(d, dtype) for d in data]

  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/silx/gui/data/TextFormatter.py", line 299, in <listcomp>

    text = [self.toString(d, dtype) for d in data]

  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/silx/gui/data/TextFormatter.py", line 302, in toString

    text = self.__formatH5pyObject(data, dtype)

  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/silx/gui/data/TextFormatter.py", line 270, in __formatH5pyObject

    return self.__formatText(data)

  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/silx/gui/data/TextFormatter.py", line 200, in __formatText

    text = "\"%s\"" % text.replace("\\", "\\\\").replace("\"", "\\\"")

TypeError: a bytes-like object is required, not 'str'

======================================================================

ERROR: testUnicode (silx.gui.data.test.test_textformatter.TestTextFormatterWithH5py)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/silx/gui/data/test/test_textformatter.py", line 133, in testUnicode

    result = self.formatter.toString(d[()], dtype=d.dtype)

  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/silx/gui/data/TextFormatter.py", line 302, in toString

    text = self.__formatH5pyObject(data, dtype)

  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/silx/gui/data/TextFormatter.py", line 270, in __formatH5pyObject

    return self.__formatText(data)

  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/silx/gui/data/TextFormatter.py", line 200, in __formatText

    text = "\"%s\"" % text.replace("\\", "\\\\").replace("\"", "\\\"")

TypeError: a bytes-like object is required, not 'str'

======================================================================

ERROR: test_hdf5_array_slice_out_of_range (silx.io.test.test_utils.TestGetData)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/silx/io/test/test_utils.py", line 570, in test_hdf5_array_slice_out_of_range

    self.assertRaises(ValueError, utils.get_data, url)

  File "/opt/python/3.8.1/lib/python3.8/unittest/case.py", line 816, in assertRaises

    return context.handle('assertRaises', args, kwargs)

  File "/opt/python/3.8.1/lib/python3.8/unittest/case.py", line 202, in handle

    callable_obj(*args, **kwargs)

  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/silx/io/utils.py", line 816, in get_data

    data = data[data_slice]

  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper

  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper

  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/h5py/_hl/dataset.py", line 704, in __getitem__

    return self._fast_reader.read(args)

  File "h5py/_selector.pyx", line 344, in h5py._selector.Reader.read

  File "h5py/_selector.pyx", line 148, in h5py._selector.Selector.apply_args

IndexError: Index (5) out of range for (0-1)

======================================================================

FAIL: testTitle (silx.io.test.test_spectoh5.TestConvertSpecHDF5)

Test the value of a dataset

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/silx/io/test/test_spectoh5.py", line 133, in testTitle

    self.assertEqual(title12,

AssertionError: b'aaaaaa' != 'aaaaaa'

======================================================================

FAIL: testSpectra (silx.io.test.test_nxdata.TestNXdata)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/silx/io/test/test_nxdata.py", line 241, in testSpectra

    self.assertEqual(nxd.title, "Title as dataset (like nexpy)")

AssertionError: "b'Title as dataset (like nexpy)'" != 'Title as dataset (like nexpy)'

- b'Title as dataset (like nexpy)'

? --                             -

+ Title as dataset (like nexpy)

======================================================================

FAIL: testFile (silx.app.test.test_convert.TestConvertCommand)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/silx/app/test/test_convert.py", line 143, in testFile

    self.assertEqual(title12,

AssertionError: b'aaaaaa' != 'aaaaaa'
```

**Comment by t20100** [comment]
Doc about new string handling in h5py is here: https://github.com/h5py/h5py/blob/master/docs/strings.rst#reading-strings

**Comment by woutdenolf** [comment]
I'll have a look at this. What about adding the two utility methods below? Then we'll have to use them everywhere we read HDF5 dataset (at least in `h5todict`).

```python
import h5py
import h5py.h5t

h5py3 = int(h5py.version.version.split(".")[0]) >= 3

def prepareDatasetRead(dset, decode_bytes=False):
    """
    Get dataset-like object for reading
    """
    if h5py3:
        str_info = h5py.h5t.check_string_dtype(dset.dtype)
        if str_info:
            if decode_bytes or str_info.encoding != "ascii":
                # dataset-like object with on-the-fly decoding
                # Note: dataset attributes do this by default
                return dset.asstr()
    return dset


def readDataset(dset, **kw):
    """
    Read data from dataset object
    """
    rdset = prepareDatasetRead(dset, **kw)
    try:
        return rdset[()]
    except UnicodeDecodeError:
        return dset[()]  # bytes
```

**Comment by vallsv** [comment]
Just a question @woutdenolf, why do you only use `asstr` if it is not `ascii`? ascii is also text.

**Comment by woutdenolf** [comment]
If `decode_bytes=True` it returns `asstr` also for `ascii`.

If the encoding is `ascii`, it means the dataset was written like this: `group[name] = b"mybytes"`.

**Comment by vallsv** [comment]
> `group[name] = b"mybytes"`

So they break the API and still use the python 2 way of thinking. Sad.

**Comment by woutdenolf** [comment]
Not sure what you mean, but just to be clear, this has not changed (was already the case for h5py 2.x):

```python
group["bytes"] = b"mybytes"
info = h5py.h5t.check_string_dtype(group["bytes"].dtype)
assert info
assert info.encoding == "ascii"
assert group["bytes"] == b"mybytes"
```

You mean that it should have been this?

```python
group["bytes"] = b"mybytes"
info = h5py.h5t.check_string_dtype(group["bytes"].dtype)
assert not info
assert group["bytes"] == b"mybytes"
```

**Comment by vallsv** [comment]
I don't understand your last sentence. But yes `bytes` is the definition of opaque type. Encoding have a meaning only for strings, and bytes are not strings. They did it well on HDF5, but it is strangely mapped in h5py (i guess cause of Python 2). But that's another story anyway.

**Comment by t20100** [comment]
Yes, it seems we'll need some helper function to read dataset as `str` within silx.

See https://gist.github.com/takluyver/32512eb5367d11d013029af5fbf1d3e1 for a function to read HDF5 dataset as `str`.
But we need more than that since we don't always know whether we are reading str or not.
