### ISSUE TITLE
[H5Node] soft link to external link bug

### ISSUE THREAD

**Issue by woutdenolf** [silx-kit/silx#3219]
There is a bug in getting the physical target of a softlink that points to on external link

```python
import h5py

with h5py.File("source.h5", mode="w") as f:
    f["data"] = 10

with h5py.File("dest.h5", mode="w") as f:
    f["external"] = h5py.ExternalLink("source.h5", "/data")
    f["soft"] = h5py.SoftLink("/external")  # H5Node.h5py_target exception
```

**Comment by woutdenolf** [comment]
@vallsv The `Hdf5Item` already results in the dereferenced link so how is `H5Node` supposed to work?

```python
class Hdf5Item(Hdf5Node):
    @property
    def obj(self):
        if self.__key:
            self.__initH5Object()
        return self.__obj  # This is the dereferenced link

    def __initH5Object(self):
        self.__obj = parent_obj.get(self.__key)  # Links are already dereferenced !!! (if the destination exists)

class H5Node(object):
    def __init__(self, h5py_item=None):
        """Constructor

        :param Hdf5Item h5py_item: An Hdf5Item
        """
        self.__h5py_object = h5py_item.obj # This is the dereferenced link
```

**Comment by woutdenolf** [comment]
@vallsv It seems the implementation assumes that `parent.get("name").parent` is the same as `parent` which is not the case.

**Comment by vallsv** [comment]
Objects and paths are 2 different things. Here we just store both. The path is based on the item tree of the view. And failing nodes are specific node.

As far as i remember.

**Comment by woutdenolf** [comment]
Ok it's in fact an h5py bug:

```python
import h5py

with h5py.File("source.h5", mode="w") as f:
    f["/group/data"] = 10

with h5py.File("dest.h5", mode="w") as f:
    f["/link/external"] = h5py.ExternalLink("source.h5", "/group/data")
    f["/link/soft"] = h5py.SoftLink("external")

with h5py.File("dest.h5", mode="r") as f:
    f["/link/soft"].parent

Traceback (most recent call last):
  File "test.py", line 11, in <module>
    f["/link/soft"].parent
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/users/denolf/virtualenvs/silx/py38/lib/python3.8/site-packages/h5py/_hl/base.py", line 239, in parent
    return self.file[posixpath.dirname(self.name)]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/users/denolf/virtualenvs/silx/py38/lib/python3.8/site-packages/h5py/_hl/group.py", line 264, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'link' doesn't exist)"
```

**Comment by woutdenolf** [comment]
https://github.com/h5py/h5py/issues/1706

**Comment by vallsv** [comment]
Then I guess the h5py property view entirely fail?

**Comment by woutdenolf** [comment]
When clicking on the node in the tree view, you get a pop-up with an exception but for the rest everything works (except that the node info is not correct, but that's normal).

**Comment by payno** [comment]
Today retrieving the physical target fails as well:

![Image](https://github.com/user-attachments/assets/2424720d-08ce-4946-a8a8-218c61eda4e9)

There is no pop-up but logs on the terminal. This is still not handled at h5py side. But I would consider this an 'expected behavior' from silx side. So let's close this one.
Please reopen if you think this is worth it.
