### ISSUE TITLE
Segfault when loading silx in some cases

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#3232]
For you information here is a segfault happening with some env. Noticed on a Windows WSL with Debian.

silx view alone was working, Flint was crashing.

The segfault was created at the `PlotWidget` loading, a Python side call produced at the termination of the import of `silx.gui.plot.matplotlib`.

I mitigate the problem my moving `import silx.gui.plot.matplotlib` at the very beginning of the Flint start.

If you have an idea. Else we can close this issue.

```
Thread 1 "python" received signal SIGSEGV, Segmentation fault.
PyModule_GetState () at /tmp/build/80754af9/python_1565725737370/work/Objects/moduleobject.c:565
565 /tmp/build/80754af9/python_1565725737370/work/Objects/moduleobject.c: No such file or directory.
(gdb) tb
Temporary breakpoint 1 at 0x812d161: file /tmp/build/80754af9/python_1565725737370/work/Objects/moduleobject.c, line 565.
(gdb) bt
#0  PyModule_GetState () at /tmp/build/80754af9/python_1565725737370/work/Objects/moduleobject.c:565
#1  0x00007fffee01ac54 in on_startup_hook () at /usr/local/src/conda/python-3.7.4/Modules/readline.c:900
#2  0x00007fffe472dce1 in rl_initialize () from /usr/lib/x86_64-linux-gnu/libedit.so.2
#3  0x00007fffee01ae4d in setup_readline.isra.0 () at /usr/local/src/conda/python-3.7.4/Modules/readline.c:1156
#4  PyInit_readline () at /usr/local/src/conda/python-3.7.4/Modules/readline.c:1372
#5  0x000000000822d895 in _PyImport_LoadDynamicModuleWithSpec ()
    at /tmp/build/80754af9/python_1565725737370/work/Python/importdl.c:159
#6  0x000000000822daa9 in _imp_create_dynamic_impl.isra.15 (file=0x0, spec=0x7fffd6814b50)
    at /tmp/build/80754af9/python_1565725737370/work/Python/import.c:2167
#7  _imp_create_dynamic () at /tmp/build/80754af9/python_1565725737370/work/Python/clinic/import.c.h:289
#8  0x00000000081356a2 in _PyMethodDef_RawFastCallDict ()
    at /tmp/build/80754af9/python_1565725737370/work/Objects/call.c:530
#9  0x00000000081357c1 in _PyCFunction_FastCallDict (func=0x7fffff5d07d0, args=<optimized out>, nargs=<optimized out>,
    kwargs=<optimized out>) at /tmp/build/80754af9/python_1565725737370/work/Objects/call.c:586
#10 0x00000000081d1007 in do_call_core (kwdict=0x7fffd6a86550, callargs=0x7fffd6814ad0, func=0x7fffff5d07d0)
    at /tmp/build/80754af9/python_1565725737370/work/Python/ceval.c:4641
#11 _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1565725737370/work/Python/ceval.c:3191
#12 0x0000000008114539 in _PyEval_EvalCodeWithName ()
    at /tmp/build/80754af9/python_1565725737370/work/Python/ceval.c:3930
#13 0x0000000008163f57 in _PyFunction_FastCallKeywords ()
    at /tmp/build/80754af9/python_1565725737370/work/Objects/call.c:433
#14 0x00000000081cff29 in call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>)
    at /tmp/build/80754af9/python_1565725737370/work/Python/ceval.c:4616
#15 _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1565725737370/work/Python/ceval.c:3093
#16 0x0000000008163ccb in function_code_fastcall (globals=<optimized out>, nargs=2, args=<optimized out>,
    co=<optimized out>) at /tmp/build/80754af9/python_1565725737370/work/Objects/call.c:283
#17 _PyFunction_FastCallKeywords () at /tmp/build/80754af9/python_1565725737370/work/Objects/call.c:408
#18 0x00000000081cba93 in call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>)
    at /tmp/build/80754af9/python_1565725737370/work/Python/ceval.c:4616
---Type <return> to continue, or q <return> to quit---
#19 _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1565725737370/work/Python/ceval.c:3110
#20 0x0000000008163ccb in function_code_fastcall (globals=<optimized out>, nargs=1, args=<optimized out>,
    co=<optimized out>) at /tmp/build/80754af9/python_1565725737370/work/Objects/call.c:283
#21 _PyFunction_FastCallKeywords () at /tmp/build/80754af9/python_1565725737370/work/Objects/call.c:408
#22 0x00000000081cb806 in call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>)
    at /tmp/build/80754af9/python_1565725737370/work/Python/ceval.c:4616
#23 _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1565725737370/work/Python/ceval.c:3124
#24 0x0000000008163ccb in function_code_fastcall (globals=<optimized out>, nargs=1, args=<optimized out>,
    co=<optimized out>) at /tmp/build/80754af9/python_1565725737370/work/Objects/call.c:283
#25 _PyFunction_FastCallKeywords () at /tmp/build/80754af9/python_1565725737370/work/Objects/call.c:408
#26 0x00000000081cb806 in call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>)
    at /tmp/build/80754af9/python_1565725737370/work/Python/ceval.c:4616
#27 _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1565725737370/work/Python/ceval.c:3124
#28 0x0000000008163ccb in function_code_fastcall (globals=<optimized out>, nargs=2, args=<optimized out>,
    co=<optimized out>) at /tmp/build/80754af9/python_1565725737370/work/Objects/call.c:283
#29 _PyFunction_FastCallKeywords () at /tmp/build/80754af9/python_1565725737370/work/Objects/call.c:408
#30 0x00000000081cb806 in call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>)
    at /tmp/build/80754af9/python_1565725737370/work/Python/ceval.c:4616
#31 _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1565725737370/work/Python/ceval.c:3124
#32 0x000000000811556b in function_code_fastcall (globals=<optimized out>, nargs=2, args=<optimized out>,
    co=0x7fffff5c5930) at /tmp/build/80754af9/python_1565725737370/work/Objects/call.c:283
#33 _PyFunction_FastCallDict () at /tmp/build/80754af9/python_1565725737370/work/Objects/call.c:322
#34 0x000000000813414e in object_vacall () at /tmp/build/80754af9/python_1565725737370/work/Objects/call.c:1202
#35 0x000000000818f68d in _PyObject_CallMethodIdObjArgs ()
    at /tmp/build/80754af9/python_1565725737370/work/Objects/call.c:1252
#36 0x000000000811decc in import_find_and_load (abs_name=0x7fffff562370)
    at /tmp/build/80754af9/python_1565725737370/work/Python/import.c:1645
#37 PyImport_ImportModuleLevelObject () at /tmp/build/80754af9/python_1565725737370/work/Python/import.c:1757
#38 0x00000000081cdf39 in import_name (level=0x8368300 <small_ints+160>, fromlist=0x8346f90 <_Py_NoneStruct>,
---Type <return> to continue, or q <return> to quit--- 
```

**Comment by t20100** [comment]
No idea what might cause this.

**Comment by t20100** [comment]
> If you have an idea. Else we can close this issue.

I'm closing, reopen if it still needs to be investigated.
