### ISSUE TITLE
[MaskToolsWidget] issue in pyFAI-drawmask

### ISSUE THREAD

**Issue by kif** [silx-kit/silx#324]
lintaillefer:~/Notebooks/Rietveld/ID28 % pyFAI-drawmask det130_g0_0001p.cbf
Traceback (most recent call last):
  File "/usr/bin/pyFAI-drawmask", line 221, in <module>
    main()
  File "/usr/bin/pyFAI-drawmask", line 206, in main
    window = MaskImageWidget()
  File "/usr/bin/pyFAI-drawmask", line 109, in __init__
    self.__maskPanel = silx.gui.plot.MaskToolsWidget.MaskToolsWidget(self.__plot2D)
  File "/usr/lib/python2.7/dist-packages/silx/gui/plot/MaskToolsWidget.py", line 364, in __init__
    self.plot.sigInteractiveModeChanged.connect(
AttributeError: 'NoneType' object has no attribute 'sigInteractiveModeChanged'

**Comment by kif** [comment]
Apparently it is the parent/self issue.

**Comment by vallsv** [comment]
Yes it is. That's an issue with pyFAI, fixed on my branch.

**Comment by kif** [comment]
OK sorry for the noise then ..
