### ISSUE TITLE
backprojection not usable

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#3243]
Hi,

It looks like on my platform/device IMAGES are not supported.

Any idea if it could be known before creating anything?

```
Traceback (most recent call last):
  File "/users/valls/workspace/bliss.git/bliss/flint/widgets/slice_reconstruction_widget.py", line 39, in __selectionChanged
    self.setItem(item)
  File "/users/valls/workspace/bliss.git/bliss/flint/widgets/slice_reconstruction_widget.py", line 64, in setItem
    sino_shape=sino.shape, angles=angles, devicetype="all"
  File "/users/valls/Software/miniconda3/envs/blissenv/lib/python3.7/site-packages/silx/opencl/backprojection.py", line 110, in __init__
    self._allocate_memory()
  File "/users/valls/Software/miniconda3/envs/blissenv/lib/python3.7/site-packages/silx/opencl/backprojection.py", line 184, in _allocate_memory
    self._allocate_textures()
  File "/users/valls/Software/miniconda3/envs/blissenv/lib/python3.7/site-packages/silx/opencl/backprojection.py", line 252, in _allocate_textures
    hostbuf=np.zeros(self.shape[::-1], dtype=np.float32)
  File "/users/valls/Software/miniconda3/envs/blissenv/lib/python3.7/site-packages/pyopencl/__init__.py", line 987, in image_init
    image_old_init(self, context, flags, format, desc, hostbuf)
pyopencl._cl.RuntimeError: clCreateImage failed: IMAGE_FORMAT_NOT_SUPPORTED
```

**Comment by pierrepaleo** [comment]
What are the platform/devices ?

This error occurred when the OpenCL backprojection kernel was compiled for CPU which does not support "textures" (`Image`). There is a dedicated kernel (`backproj_cpu_kernel`) for it, but it does not seem to be dispatched correctly here.

**Comment by vallsv** [comment]
I finally found something which is working.

Here is the one which was failing. I can try to reach more informations if you like.
```
In [2]: import pyopencl                                                                                                                                                                                                      

In [4]: pyopencl.get_platforms()                                                                                                                                                                                             
Out[4]: [<pyopencl.Platform 'Intel Gen OCL Driver' at 0x7fcdc31f4400>]

In [6]: p = pyopencl.get_platforms()[0]                                                                                                                                                                                      

In [7]: p.get_devices()                                                                                                                                                                                                      
Out[7]: [<pyopencl.Device 'Intel(R) UHD Graphics Coffee Lake Desktop GT2' on 'Intel Gen OCL Driver' at 0x7fcdc31f4ec0>]
```

**Comment by pierrepaleo** [comment]
OK thanks, it looks like a GPU integrated in CPU.

We should add a mechanism for checking textures availability, other than "CPU/GPU".

**Comment by vallsv** [comment]
Could it do the job?
```
d.get_info(pyopencl.device_info.IMAGE_SUPPORT)
```

**Comment by pierrepaleo** [comment]
Yes, or even something like

```python
try:
    tex = pyopencl.Image(...)
    textures_supported = True
except:
    textures_supported = False
```
because we are not really sure that textures are actually supported before allocating one ; and sometimes `get_info()` does not work and/or returns incorrect results.

**Comment by pierrepaleo** [comment]
Handled by #3273 (don't know why it was not closed automatically).
