### ISSUE TITLE
opengl: bound error

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#3256]
Exception while playing with arc ROIs (whne i have tried to close an arc to a circle)

```
Traceback (most recent call last):
  File "/users/valls/workspace/silx.git/build/lib.linux-x86_64-3.7/silx/gui/_glutils/OpenGLWidget.py", line 224, in paintGL
    parent.paintGL()
  File "/users/valls/workspace/silx.git/build/lib.linux-x86_64-3.7/silx/gui/plot/backends/BackendOpenGL.py", line 405, in paintGL
    self._paintFBOGL()
  File "/users/valls/workspace/silx.git/build/lib.linux-x86_64-3.7/silx/gui/plot/backends/BackendOpenGL.py", line 386, in _paintFBOGL
    self._renderOverlayGL()
  File "/users/valls/workspace/silx.git/build/lib.linux-x86_64-3.7/silx/gui/plot/backends/BackendOpenGL.py", line 640, in _renderOverlayGL
    self._renderItems(overlay=True)
  File "/users/valls/workspace/silx.git/build/lib.linux-x86_64-3.7/silx/gui/plot/backends/BackendOpenGL.py", line 476, in _renderItems
    for (x, y) in zip(item['x'], item['y'])])
  File "/users/valls/workspace/silx.git/build/lib.linux-x86_64-3.7/silx/gui/plot/backends/BackendOpenGL.py", line 476, in <listcomp>
    for (x, y) in zip(item['x'], item['y'])])
  File "/users/valls/workspace/silx.git/build/lib.linux-x86_64-3.7/silx/gui/plot/backends/glutils/GLPlotFrame.py", line 1029, in dataToPixel
    (trBounds.x[1] - trBounds.x[0]))
ValueError: cannot convert float NaN to integer

```

**Comment by t20100** [comment]
Do you have a way to reproduce this?

**Comment by vallsv** [comment]
Yes. Create an arc ROI, close it.

The are ROI uses NaN to display both sides of the circle with a single path.
That is maybe why it fails.
