### ISSUE TITLE
Colormap: _setFromDict

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#3290]
Hi,

For convenience i am using `_setFromDict` and the reverse.

There is maybe a bug somehow.

```
2020-11-17 14:56:02,054 camera 4276 bliss.flint.widgets.image_plot ERROR : Impossible to restore colormap preference
Traceback (most recent call last):
  File "/users/blissadm/local/bliss.git/bliss/flint/widgets/image_plot.py", line 239, in setConfiguration
    self.__colormap._setFromDict(config.colormap)
  File "/users/blissadm/conda/miniconda/envs/bliss_dev/lib/python3.7/site-packages/silx/gui/colors.py", line 962, in _setFromDict
    name = dic['name'] if 'name' in dic else None
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by vallsv** [comment]
Looks like it's on my side. Input arg is None.
