### ISSUE TITLE
specfile locale tests fail on windows

### ISSUE THREAD

**Issue by woutdenolf** [silx-kit/silx#3315]
```
FAIL: test_locale_de_DE (silx.io.test.test_specfile.TestSFLocale)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\paleo\personal\envs\38\lib\site-packages\silx\io\test\test_specfile.py", line 412, in test_locale_de_DE
    self.crunch_data()
  File "c:\users\paleo\personal\envs\38\lib\site-packages\silx\io\test\test_specfile.py", line 405, in crunch_data
    self.assertAlmostEqual(self.sf3[0].data_line(1)[2],
AssertionError: 1.0 != 1.56 within 7 places (0.56 difference)
```

**Comment by pierrepaleo** [comment]
Handled by #3316
