### ISSUE TITLE
Filtered backproject on OpenCL

### ISSUE THREAD

**Issue by kif** [silx-kit/silx#3324]
Well, I am not sure we do support this platform, but it is good to know.
* Intel/CPU is OK, 
* Apple/gpu is OK
* PoCL/CPU (1.5-6, amd64) is OK
* AMD/GPU (Vega56) Fails with:
```
FAIL: test_fbp (silx.opencl.test.test_backprojection.TestFBP)
tests FBP
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jerome/workspace/silx/build/lib.linux-x86_64-3.9/silx/opencl/test/test_backprojection.py", line 155, in test_fbp
    self.assertTrue(err < self.tol, "Max error is too high")
AssertionError: False is not true : Max error is too high

Stderr:
WARNING:py.warnings:/usr/lib/python3/dist-packages/pytools/py_codegen.py:26: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp


======================================================================
FAIL: test_fbp_filters (silx.opencl.test.test_backprojection.TestFBP)
Test the different available filters of silx FBP.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jerome/workspace/silx/build/lib.linux-x86_64-3.9/silx/opencl/test/test_backprojection.py", line 198, in test_fbp_filters
    self.assertTrue(
AssertionError: False is not true : Something wrong with FBP(filter=ramlak)

======================================================================
FAIL: test_fbp_oddsize (silx.opencl.test.test_backprojection.TestFBP)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jerome/workspace/silx/build/lib.linux-x86_64-3.9/silx/opencl/test/test_backprojection.py", line 214, in test_fbp_oddsize
    self.assertLess(
AssertionError: 258.20255 not less than 0.1 : Something wrong with FBP on odd-sized sinogram
```

**Comment by jcesardasilva** [comment]
Hi everyone, 
If possible, please keep supporting the openCL packages in SILX or, if not in your plans, move all, or at least, the `Backprojection` and `Projection` to **Nabu** (or any other place to be maintained), please. **Nabu** only offers the former, but not the latter. 

In any case, there is a feature in those packages, which only work (at least for me) with `pyopencl<=2020.2`. If I upgrade `pyopencl` to the newest version, the packages get broken. 

Could anyone help me with this, please? 

Thank you very much in advance.
