### ISSUE TITLE
Test failing on debian9

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#3377]
On debian9 (Python 3.5, h5py 2.7.0, libhdf5 1.10.0), the test `silx.io.test.test_h5py_utils.TestH5pyUtils.test_modes_multi_process` fails (see log below).

What do we want to do?

- Drop debian9 support (i.e., packaging)? Announcement of dropping python3.5 was made in last release: https://github.com/silx-kit/silx/releases/tag/v0.14.0
- Fix the code/skip the test for older version of h5py?

I'd be in favor of dropping debian9 since the provided version of libhdf5 (1.10.0) should not be used anyway.

```
ERROR: test_modes_multi_process (silx.io.test.test_h5py_utils.TestH5pyUtils) (mode='w')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/silx/bob/silx/silx-0.15.0a0/build/debian9/silx-0.15.0a0/.pybuild/cpython3_3.5_silx/build/silx/io/test/test_h5py_utils.py", line 120, in wrapper
    test(self)
  File "/builds/silx/bob/silx/silx-0.15.0a0/build/debian9/silx-0.15.0a0/.pybuild/cpython3_3.5_silx/build/silx/io/test/test_h5py_utils.py", line 214, in test_modes_multi_process
    with self._open_context(filename, mode="r") as f:
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/builds/silx/bob/silx/silx-0.15.0a0/build/debian9/silx-0.15.0a0/.pybuild/cpython3_3.5_silx/build/silx/io/test/test_h5py_utils.py", line 160, in _open_context
    with _open_context(filename, **kw) as f:
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/builds/silx/bob/silx/silx-0.15.0a0/build/debian9/silx-0.15.0a0/.pybuild/cpython3_3.5_silx/build/silx/io/test/test_h5py_utils.py", line 77, in _open_context
    with h5py_utils.File(filename, **kw) as f:
  File "/builds/silx/bob/silx/silx-0.15.0a0/build/debian9/silx-0.15.0a0/.pybuild/cpython3_3.5_silx/build/silx/io/h5py_utils.py", line 231, in __init__
    super().__init__(filename, mode=mode, swmr=swmr, libver=libver, **kwargs)
  File "/usr/lib/python3/dist-packages/h5py/_hl/files.py", line 271, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/usr/lib/python3/dist-packages/h5py/_hl/files.py", line 101, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/build/h5py-b1xqNM/h5py-2.7.0/h5py/_objects.c:2842)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/build/h5py-b1xqNM/h5py-2.7.0/h5py/_objects.c:2800)
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open (/build/h5py-b1xqNM/h5py-2.7.0/h5py/h5f.c:2127)
OSError: Unable to open file (Unable to flock file, errno = 11, error message = 'resource temporarily unavailable')
```

Full log: https://gitlab.esrf.fr/silx/bob/silx/-/jobs/186579

**Comment by t20100** [comment]
If no one is against it, let's stop providing debian9 pacakges from next version onwards.

**Comment by payno** [comment]
Not against.
