### ISSUE TITLE
Issue with histogram item and stats widget

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#3392]
There is apparently an issue with histogram items and the Stats widget.

To reproduce:
```
from silx import sx                                                     
w = sx.plot()                                                           
w.addHistogram((1, 2, 3), (1, 2, 3))  
```
Then click on "Options"

```
Traceback (most recent call last):
  File "silx/gui/plot/PlotWindow.py", line 466, in _customControlButtonMenu
    controlMenu.addAction(self.getStatsAction())
  File "silx/gui/plot/PlotWindow.py", line 655, in getStatsAction
    self._statsAction.setChecked(self.getStatsWidget().parent().isVisible())
  File "silx/gui/plot/PlotWindow.py", line 585, in getStatsWidget
    statsWidget = BasicStatsWidget(parent=self, plot=self)
  File "silx/gui/plot/StatsWidget.py", line 1285, in __init__
    stats=DEFAULT_STATS)
  File "silx/gui/plot/StatsWidget.py", line 1168, in __init__
    self.setStats(stats)
  File "silx/gui/plot/StatsWidget.py", line 1211, in setStats
    return self._getStatsTable().setStats(statsHandler=statsHandler)
  File "silx/gui/plot/StatsWidget.py", line 635, in setStats
    self._updateItemObserve()
  File "silx/gui/plot/StatsWidget.py", line 666, in _updateItemObserve
    self._addItem(item)
  File "silx/gui/plot/StatsWidget.py", line 817, in _addItem
    self._updateStats(item, data_changed=True)
  File "silx/gui/plot/StatsWidget.py", line 873, in _updateStats
    data_changed=data_changed, roi_changed=roi_changed)
  File "silx/gui/plot/stats/statshandler.py", line 199, in calculate
    data_changed=data_changed, roi_changed=roi_changed)
  File "silx/gui/plot/stats/stats.py", line 104, in calculate
    roi=roi)
  File "silx/gui/plot/stats/stats.py", line 423, in clipData
    self.values = numpy.ma.array(yData, mask=mask)
  File "numpy/ma/core.py", line 6562, in array
    ndmin=ndmin, shrink=shrink, order=order)
  File "numpy/ma/core.py", line 2909, in __new__
    raise MaskError(msg % (nd, nm))
numpy.ma.core.MaskError: Mask and data not compatible: data size is 3, mask size is 6.
```

**Comment by t20100** [comment]
Once previous error is fixed, there is another one:
```
from silx import sx                                                     
w = sx.plot()                                                           
w.addHistogram((1, 2, 3, 2, 1), (1, 2, 3, 4, 5))                        
```
Then open stats widget from the "Options" menu.
Pan the histogram half out of the plot area and press on the "stats on visible area" icon:
```
Traceback (most recent call last):
  File "silx/gui/plot/StatsWidget.py", line 1205, in _optDataRangeChanged
    self._options.isVisibleDataRangeMode())
  File "silx/gui/plot/StatsWidget.py", line 487, in setStatsOnVisibleData
    self._updateAllStats()
  File "silx/gui/plot/StatsWidget.py", line 903, in _updateAllStats
    self._updateStats(item, data_changed=is_request)
  File "silx/gui/plot/StatsWidget.py", line 873, in _updateStats
    data_changed=data_changed, roi_changed=roi_changed)
  File "silx/gui/plot/stats/statshandler.py", line 199, in calculate
    data_changed=data_changed, roi_changed=roi_changed)
  File "silx/gui/plot/stats/stats.py", line 92, in calculate
    roi=roi)
  File "silx/gui/plot/stats/stats.py", line 132, in _getContext
    context = _HistogramContext(item, plot, onlimits, roi=roi)
  File "silx/gui/plot/stats/stats.py", line 379, in __init__
    onlimits=onlimits, roi=roi)
  File "silx/gui/plot/stats/stats.py", line 283, in __init__
    plot=plot, onlimits=onlimits, roi=roi)
  File "silx/gui/plot/stats/stats.py", line 194, in __init__
    self.clipData(item, plot, onlimits, roi=roi)
  File "silx/gui/plot/stats/stats.py", line 411, in clipData
    self.values = numpy.ma.array(yData, mask=mask)
  File "numpy/ma/core.py", line 6562, in array
    ndmin=ndmin, shrink=shrink, order=order)
  File "numpy/ma/core.py", line 2909, in __new__
    raise MaskError(msg % (nd, nm))
numpy.ma.core.MaskError: Mask and data not compatible: data size is 2, mask size is 5.
```
