### ISSUE TITLE
ColorBar  issue when closing IPython

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#3402]
To reproduce:

```
In [1]: from silx import sx                                                     
In [2]: w = sx.imshow()                                                         
In [3]:                                                                         
Do you really want to exit ([y]/n)? 
Traceback (most recent call last):
  File "silx/gui/plot/ColorBar.py", line 152, in hideEvent
    self._disconnectPlot()
  File "silx/gui/plot/ColorBar.py", line 118, in _disconnectPlot
    plot.sigActiveImageChanged.disconnect(
RuntimeError: wrapped C/C++ object of type Plot2D has been deleted
```

Tested with PyQt5.14.2 and PySide2 5.13.2

**Comment by vallsv** [comment]
Probably a good place to use `sys.is_finalizing`

**Comment by t20100** [comment]
Yes, or [`silx.gui.qt.inspect`](https://github.com/silx-kit/silx/blob/master/silx/gui/qt/inspect.py)
