### ISSUE TITLE
Failures in test_retry_in_subprocess

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#3420]
There is random (yet regular) errors with `test_retry_in_subprocess` in CI environment (see e.g., https://gitlab.esrf.fr/silx/bob/silx/-/jobs/193581):
```
ERROR: test_retry_in_subprocess (silx.io.test.test_h5py_utils.TestH5pyUtils) (mode='w', libver='latest')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/silx/bob/silx/silx-0.15.0rc1/build/debian11/silx-0.15.0rc1/.pybuild/cpython3_3.8_silx/build/silx/utils/retry.py", line 63, in _handle_exception
    yield
  File "/builds/silx/bob/silx/silx-0.15.0rc1/build/debian11/silx-0.15.0rc1/.pybuild/cpython3_3.8_silx/build/silx/utils/retry.py", line 242, in wrapper
    raise result
silx.utils.retry.RetryError
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/builds/silx/bob/silx/silx-0.15.0rc1/build/debian11/silx-0.15.0rc1/.pybuild/cpython3_3.8_silx/build/silx/io/test/test_h5py_utils.py", line 120, in wrapper
    test(self)
  File "/builds/silx/bob/silx/silx-0.15.0rc1/build/debian11/silx-0.15.0rc1/.pybuild/cpython3_3.8_silx/build/silx/io/test/test_h5py_utils.py", line 379, in test_retry_in_subprocess
    names = top_level_names_test(txtfilename, filename, **kw)
  File "/builds/silx/bob/silx/silx-0.15.0rc1/build/debian11/silx-0.15.0rc1/.pybuild/cpython3_3.8_silx/build/silx/utils/retry.py", line 227, in wrapper
    for options in _retry_loop(
  File "/builds/silx/bob/silx/silx-0.15.0rc1/build/debian11/silx-0.15.0rc1/.pybuild/cpython3_3.8_silx/build/silx/utils/retry.py", line 90, in _retry_loop
    raise RetryTimeoutError from options.get("exception")
silx.utils.retry.RetryTimeoutError
``

**Comment by t20100** [comment]
Also got on power9:
```
FAIL: test_retry_in_subprocess (silx.io.test.test_h5py_utils.TestH5pyUtils) (mode='w')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tvincent/silx/build/lib.linux-ppc64le-3.9/silx/io/test/test_h5py_utils.py", line 120, in wrapper
    test(self)
  File "/home/tvincent/silx/build/lib.linux-ppc64le-3.9/silx/io/test/test_h5py_utils.py", line 391, in test_retry_in_subprocess
    top_level_names_test(txtfilename, filename, **kw)
AssertionError: RetryTimeoutError not raised
```
