### ISSUE TITLE
silx view - external link (rnice8)

### ISSUE THREAD

**Issue by payno** [silx-kit/silx#3474]
On rnice(8) when using silx view with a file containing a virtual dataset we end up with this error:
``` bash
H5Node has no attribute physical_filename   File "/sware/isdd/packages/debian8/dau/miniconda3/envs/dau/lib/python3.8/site-packages/silx/gui/data/Hdf5TableView.py", line 273, in data
    value = value(self.__obj)
  File "/sware/isdd/packages/debian8/dau/miniconda3/envs/dau/lib/python3.8/site-packages/silx/gui/data/Hdf5TableView.py", line 429, in _physical_location
    return x.physical_filename + SEPARATOR + x.physical_name
  File "/sware/isdd/packages/debian8/dau/miniconda3/envs/dau/lib/python3.8/site-packages/silx/gui/hdf5/_utils.py", line 161, in __getattr__
    raise AttributeError("H5Node has no attribute %s" % name)
```

Example of a file with the error: /data/visitor/im51/id19/FL_PM_0_4p2/FL_PM_0_4p2_0001/FL_PM_0_4p2_0001_rec.hdf5

silx version is 0.15. h5py version is 2.10.  HDF5 version is 1.10.6 
I tested the same file with latest silx + latest h5py on a different virtual environment and it works perfectly (h5py version is '1.12.0' and HDF5 version is 3.2.1). The has probably been write by a recent HDF5 version. Issue is not from silx but the error is a missleading. (some code failling in a property)

**Comment by payno** [comment]
When simply trying to access the dataset:
```
import silx
import h5py

file_path = "/data/visitor/im51/id19/FL_PM_0_4p2/FL_PM_0_4p2_0001/FL_PM_0_4p2_0001_rec.hdf5"
data_path = "/entry0000/reconstruction/results/data"

from silx.gui.hdf5 import H5Node
from silx.io.utils import h5py_read_dataset

with h5py.File(file_path, mode="r") as h5f:
    assert data_path in h5f, "{} does not exists in file".format(data_path)
    item = h5f[data_path]
    # node = H5Node(item)
```

it ends up with: 
```
Traceback (most recent call last):
  File "test_silx.py", line 16, in <module>
    item = h5f[data_path][:]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/sware/isdd/packages/debian8/dau/miniconda3/envs/dau/lib/python3.8/site-packages/h5py/_hl/group.py", line 264, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: 'Unable to open object (bad version number for hyperslab selection)'
```

**Comment by t20100** [comment]
Yes, the file has probably been written with libhdf5 1.12.
I agree the error message could be improved E.g., by providing the initial error?

**Comment by payno** [comment]
Yes. But not sure which one it is originally. I did not "dig" into the "property" call dominoes (it trigger a all set of properties in fact)
