### ISSUE TITLE
BackendMatplotlibQt has been deleted

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#3589]
HI.

Here is my first tests withs Qt 5.12 / Flint / silx 1.0.0

I have notices this problem sometimes. Reproducible in a very specific context (in CI and on my local computer).
I dont think I will be able to simplify the test to reproduce it.

I think i can't to much on my side.

Here it's sounds like a common asynchronous issue.
Could it be possible to protect `__deferredReplot` on your side? Or do you have another idea.

```
_________________________________________________________________________ TestScatterPlot.test_display_nothing __________________________________________________________________________

self = <tests.qt.flint.widgets.test_scatter_plot.TestScatterPlot testMethod=test_display_nothing>

    def tearDown(self):
        self.qapp.processEvents()
    
        if len(self.__class__._exceptions) > 0:
            messages = "\n".join(self.__class__._exceptions)
>           raise AssertionError("Exception occured in Qt thread:\n" + messages)
E           AssertionError: Exception occured in Qt thread:
E           Traceback (most recent call last):
E             File "/nobackup/lvalls1/valls/Software/miniconda3/envs/blissenv2/lib/python3.7/site-packages/silx/gui/plot/backends/BackendMatplotlib.py", line 1368, in __deferredReplot
E               self.replot()
E             File "/nobackup/lvalls1/valls/Software/miniconda3/envs/blissenv2/lib/python3.7/site-packages/silx/gui/plot/backends/BackendMatplotlib.py", line 1533, in replot
E               self.draw()
E             File "/nobackup/lvalls1/valls/Software/miniconda3/envs/blissenv2/lib/python3.7/site-packages/silx/gui/plot/backends/BackendMatplotlib.py", line 1486, in draw
E               FigureCanvasQTAgg.draw(self)
E             File "/nobackup/lvalls1/valls/Software/miniconda3/envs/blissenv2/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 439, in draw
E               super().draw()
E             File "/nobackup/lvalls1/valls/Software/miniconda3/envs/blissenv2/lib/python3.7/site-packages/matplotlib/backends/backend_qt.py", line 424, in draw
E               self.update()
E           RuntimeError: wrapped C/C++ object of type BackendMatplotlibQt has been deleted

/nobackup/lvalls1/valls/Software/miniconda3/envs/blissenv2/lib/python3.7/site-packages/silx/gui/utils/testutils.py:185: AssertionError
```

**Comment by vallsv** [comment]
```
+import weakref
 
 from silx.gui.utils.testutils import TestCaseQt
 from silx.gui import qt
@@ -97,7 +98,9 @@ class TestScatterPlot(TestCaseQt):
         silxPlot = widget._silxPlot()
         scatters = [o for o in silxPlot.getItems() if isinstance(o, silx_items.Scatter)]
         assert len(scatters) == 1
-        widget.close()
+
+        w = weakref.ref(widget)
+        self.qWaitForDestroy(w)
 ```
I have patched it in my test such way.

I think it could be problem only highlighted by the test.
What do you think? In this case feel free to close the issue.

**Comment by t20100** [comment]
Yes, we can check in `__deferrerReplot` if the underlying widget still exists in Qt.
