### ISSUE TITLE
pyopengl 3.1.6 not supported

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#3630]
While trying the scatter 3D

```
$ mamba install pyopengl==3.1.6

$ python examples/plot3dUpdateScatterFromThread.py
```

Here is the result
```
Traceback (most recent call last):
  File "/nobackup/lvalls1/valls/Software/miniconda3/envs/silxenv/lib/python3.7/site-packages/silx/gui/_glutils/OpenGLWidget.py", line 223, in paintGL
    parent.paintGL()
  File "/nobackup/lvalls1/valls/Software/miniconda3/envs/silxenv/lib/python3.7/site-packages/silx/gui/plot3d/Plot3DWidget.py", line 350, in paintGL
    self._window.render(self.context(), self.getDevicePixelRatio())
  File "/nobackup/lvalls1/valls/Software/miniconda3/envs/silxenv/lib/python3.7/site-packages/silx/gui/plot3d/scene/window.py", line 364, in render
    self._renderWithOffscreenFramebuffer(context)
  File "/nobackup/lvalls1/valls/Software/miniconda3/envs/silxenv/lib/python3.7/site-packages/silx/gui/plot3d/scene/window.py", line 401, in _renderWithOffscreenFramebuffer
    wrap=gl.GL_CLAMP_TO_EDGE)
  File "/nobackup/lvalls1/valls/Software/miniconda3/envs/silxenv/lib/python3.7/site-packages/silx/gui/_glutils/FramebufferTexture.py", line 69, in __init__
    self._name = gl.glGenFramebuffers(1)
  File "/nobackup/lvalls1/valls/Software/miniconda3/envs/silxenv/lib/python3.7/site-packages/OpenGL/latebind.py", line 47, in __call__
    return self._finalCall( *args, **named )
  File "/nobackup/lvalls1/valls/Software/miniconda3/envs/silxenv/lib/python3.7/site-packages/OpenGL/wrapper.py", line 671, in wrapperCall
    result = wrappedOperation( *cArguments )
  File "/nobackup/lvalls1/valls/Software/miniconda3/envs/silxenv/lib/python3.7/site-packages/OpenGL/platform/baseplatform.py", line 425, in __call__
    self.__name__, self.__name__,
OpenGL.error.NullFunctionError: Attempt to call an undefined function glGenFramebuffers, check for bool(glGenFramebuffers) before calling

```

If i install `pyopengl 3.1.5`, everything works like a charm.

Any idea?

**Comment by t20100** [comment]
Do you still get this issue?

**Comment by t20100** [comment]
I'm closing it, please re-open if this issue still occurs.

**Comment by vallsv** [comment]
Reproducible with a fresh install on Debian 10.
I think it is still the pbm with PyOpenGL > 3.1.5.
If i install 3.1.6 it is fine.

**Comment by vallsv** [comment]
I though it was related to https://github.com/mcfletch/pyopengl/issues/88, but maybe not.
To be checked.

**Comment by t20100** [comment]
Can you share the env.yml of the environment where it occurs?

**Comment by vallsv** [comment]
```
name: silxenv
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.8=h166bdaf_0
  - attr=2.5.1=h166bdaf_1
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2023.5.7=hbcca054_0
  - cairo=1.16.0=hbbf8b49_1016
  - dbus=1.13.6=h5008d03_3
  - expat=2.5.0=hcb278e6_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=hca18f0e_1
  - gettext=0.21.1=h27087fc_0
  - glib=2.76.3=hfc55251_0
  - glib-tools=2.76.3=hfc55251_0
  - graphite2=1.3.13=h58526e2_1001
  - gst-plugins-base=1.22.3=h938bd60_1
  - gstreamer=1.22.3=h977cf35_1
  - harfbuzz=7.3.0=hdb3a94d_0
  - icu=72.1=hcb278e6_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.20.1=h81ceb04_0
  - lame=3.100=h166bdaf_1003
  - ld_impl_linux-64=2.40=h41732ed_0
  - libcap=2.67=he9d0100_0
  - libclang=15.0.7=default_h7634d5b_2
  - libclang13=15.0.7=default_h9986a30_2
  - libcups=2.3.3=h36d4200_3
  - libedit=3.1.20191231=he28a2e2_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libflac=1.4.3=h59595ed_0
  - libgcc-ng=13.1.0=he5830b7_0
  - libgcrypt=1.10.1=h166bdaf_0
  - libglib=2.76.3=hebfc3b9_0
  - libgomp=13.1.0=he5830b7_0
  - libgpg-error=1.47=h71f35ed_0
  - libiconv=1.17=h166bdaf_0
  - libjpeg-turbo=2.1.5.1=h0b41bf4_0
  - libllvm15=15.0.7=h5cf9203_2
  - libnsl=2.0.0=h7f98852_0
  - libogg=1.3.4=h7f98852_1
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.39=h753d276_0
  - libpq=15.3=hbcd7760_1
  - libsndfile=1.2.0=hb75c966_0
  - libsqlite=3.42.0=h2797004_0
  - libstdcxx-ng=13.1.0=hfd8a6a1_0
  - libsystemd0=253=h8c4010b_1
  - libuuid=2.38.1=h0b41bf4_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libxcb=1.15=h0b41bf4_0
  - libxkbcommon=1.5.0=h5d7e998_3
  - libxml2=2.11.4=h0d562d8_0
  - libzlib=1.2.13=hd590300_5
  - lz4-c=1.9.4=hcb278e6_0
  - mpg123=1.31.3=hcb278e6_0
  - mysql-common=8.0.33=hf1915f5_0
  - mysql-libs=8.0.33=hca2cd23_0
  - ncurses=6.4=hcb278e6_0
  - nspr=4.35=h27087fc_0
  - nss=3.89=he45b914_0
  - openssl=3.1.1=hd590300_1
  - packaging=23.1=pyhd8ed1ab_0
  - pcre2=10.40=hc3806b6_0
  - pip=23.1.2=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - ply=3.11=py_1
  - pthread-stubs=0.4=h36c2ea0_1001
  - pulseaudio-client=16.1=hb77b528_4
  - python=3.8.17=he550d4f_0_cpython
  - python_abi=3.8=3_cp38
  - qt-main=5.15.8=h01ceb2d_13
  - readline=8.2=h8228510_1
  - tk=8.6.12=h27826a3_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - wheel=0.40.0=pyhd8ed1ab_0
  - xcb-util=0.4.0=hd590300_1
  - xcb-util-image=0.4.0=h8ee46fc_1
  - xcb-util-keysyms=0.4.0=h8ee46fc_1
  - xcb-util-renderutil=0.3.9=hd590300_1
  - xcb-util-wm=0.4.1=h8ee46fc_1
  - xkeyboard-config=2.39=hd590300_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.6=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xf86vidmodeproto=2.3.1=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.2=h3eb15da_6
  - pip:
    - asttokens==2.2.1
    - backcall==0.2.0
    - comm==0.1.3
    - contourpy==1.1.0
    - coverage==7.2.7
    - cycler==0.11.0
    - cython==0.29.35
    - debugpy==1.6.7
    - decorator==5.1.1
    - exceptiongroup==1.1.1
    - executing==1.2.0
    - fabio==2023.6.0
    - fonttools==4.40.0
    - h5py==3.9.0
    - importlib-metadata==6.7.0
    - importlib-resources==5.12.0
    - iniconfig==2.0.0
    - ipykernel==6.23.3
    - ipython==8.12.2
    - ipython-genutils==0.2.0
    - jedi==0.18.2
    - jupyter-client==8.3.0
    - jupyter-core==5.3.1
    - kiwisolver==1.4.4
    - mako==1.2.4
    - markupsafe==2.1.3
    - matplotlib==3.7.1
    - matplotlib-inline==0.1.6
    - nest-asyncio==1.5.6
    - numexpr==2.8.4
    - numpy==1.24.4
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.5.0
    - pint==0.21.1
    - platformdirs==3.8.0
    - pluggy==1.2.0
    - prompt-toolkit==3.0.38
    - psutil==5.9.5
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyfai==2023.6.0a0
    - pygments==2.15.1
    - pyopencl==2023.1.1
    - pyopengl==3.1.7
    - pyparsing==3.1.0
    - pyqt5==5.13.0
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.12.1
    - pyside6==6.5.1.1
    - pyside6-addons==6.5.1.1
    - pyside6-essentials==6.5.1.1
    - pytest==7.4.0
    - pytest-cov==4.1.0
    - pytest-xvfb==3.0.0
    - python-dateutil==2.8.2
    - pytools==2023.1
    - pyvirtualdisplay==3.0
    - pyzmq==25.1.0
    - qtconsole==5.4.3
    - qtpy==2.3.1
    - scipy==1.10.1
    - setuptools==59.8.0
    - shiboken6==6.5.1.1
    - six==1.16.0
    - stack-data==0.6.2
    - tornado==6.3.2
    - traitlets==5.9.0
    - typing-extensions==4.6.3
    - wcwidth==0.2.6
    - zipp==3.15.0
```
