### ISSUE TITLE
TypeError in profile editor

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#3691]
```
ERROR    ewoksorange.bindings.qtapp:qtapp.py:178 Uncaught exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/silx/gui/plot/tools/profile/editors.py", line 188, in deleteWidget
    self.__setEditor(widget, None)
  File "/usr/local/lib/python3.7/site-packages/silx/gui/plot/tools/profile/editors.py", line 255, in __setEditor
    previousEditor.sigDataCommited.disconnect(self._editorDataCommited)
TypeError: 'method' object is not connected
```

**Comment by woutdenolf** [comment]
PyQt5_Qt5-5.15.2-py3-none-manylinux2014_x86_64.whl

**Comment by woutdenolf** [comment]
https://gitlab.esrf.fr/workflow/ewoksapps/ewoksxrpd/-/jobs/457103

**Comment by vallsv** [comment]
Sounds like this PyQt version also create other problems when we have to load files from silx view.
It's probably a good idea to check that.
