### ISSUE TITLE
incompatibility with python 3.11

### ISSUE THREAD

**Issue by kklmn** [silx-kit/silx#3731]
Hi!

In python 3.11 and silx 1.1.1, the following import breaks:

```
Python 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from silx.gui.plot.tools.roi import RegionOfInterestManager
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\WPy64-31101\python-3.11.0.amd64\Lib\site-packages\silx\gui\plot\__init__.py", line 63, in <module>
    from .PlotWindow import PlotWindow, Plot1D, Plot2D  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WPy64-31101\python-3.11.0.amd64\Lib\site-packages\silx\gui\plot\PlotWindow.py", line 56, in <module>
    from .CurvesROIWidget import CurvesROIDockWidget
  File "C:\WPy64-31101\python-3.11.0.amd64\Lib\site-packages\silx\gui\plot\CurvesROIWidget.py", line 41, in <module>
    from silx.io import dictdump
  File "C:\WPy64-31101\python-3.11.0.amd64\Lib\site-packages\silx\io\dictdump.py", line 35, in <module>
    from pint import Quantity as PintQuantity
  File "C:\WPy64-31101\python-3.11.0.amd64\Lib\site-packages\pint\__init__.py", line 16, in <module>
    from .context import Context
  File "C:\WPy64-31101\python-3.11.0.amd64\Lib\site-packages\pint\context.py", line 20, in <module>
    from .definitions import Definition, UnitDefinition
  File "C:\WPy64-31101\python-3.11.0.amd64\Lib\site-packages\pint\definitions.py", line 16, in <module>
    from .converters import Converter, LogarithmicConverter, OffsetConverter, ScaleConverter
  File "C:\WPy64-31101\python-3.11.0.amd64\Lib\site-packages\pint\converters.py", line 12, in <module>
    from .compat import HAS_NUMPY, exp, log  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WPy64-31101\python-3.11.0.amd64\Lib\site-packages\pint\compat.py", line 163, in <module>
    from xarray import DataArray, Dataset, Variable
  File "C:\WPy64-31101\python-3.11.0.amd64\Lib\site-packages\xarray\__init__.py", line 1, in <module>
    from . import testing, tutorial
  File "C:\WPy64-31101\python-3.11.0.amd64\Lib\site-packages\xarray\testing.py", line 9, in <module>
    from xarray.core import duck_array_ops, formatting, utils
  File "C:\WPy64-31101\python-3.11.0.amd64\Lib\site-packages\xarray\core\duck_array_ops.py", line 29, in <module>
    from .pycompat import cupy_array_type, is_duck_dask_array
  File "C:\WPy64-31101\python-3.11.0.amd64\Lib\site-packages\xarray\core\pycompat.py", line 48, in <module>
    dsk = DuckArrayModule("dask")
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WPy64-31101\python-3.11.0.amd64\Lib\site-packages\xarray\core\pycompat.py", line 27, in __init__
    duck_array_type = (import_module("dask.array").Array,)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WPy64-31101\python-3.11.0.amd64\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WPy64-31101\python-3.11.0.amd64\Lib\site-packages\dask\array\__init__.py", line 2, in <module>
    from dask.array import backends, fft, lib, linalg, ma, overlap, random
  File "C:\WPy64-31101\python-3.11.0.amd64\Lib\site-packages\dask\array\backends.py", line 18, in <module>
    from dask.array.percentile import _percentile
  File "C:\WPy64-31101\python-3.11.0.amd64\Lib\site-packages\dask\array\percentile.py", line 9, in <module>
    from dask.array.core import Array
  File "C:\WPy64-31101\python-3.11.0.amd64\Lib\site-packages\dask\array\core.py", line 32, in <module>
    from tlz.curried import pluck
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\WPy64-31101\python-3.11.0.amd64\Lib\site-packages\tlz\_build_tlz.py", line 85, in exec_module
    submodule = import_module(module_name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WPy64-31101\python-3.11.0.amd64\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
AttributeError: 'TlzSpec' object has no attribute '_uninitialized_submodules'
```

Interestingly enough, the second attempt of this import in a terminal does succeed. But it always fails inside a script.

**Comment by vasole** [comment]
If pint is an optional dependency, **any** exception should be caught and not just ImportError.

**Comment by kklmn** [comment]
>Does from pint import Quantity and from tlz.curried import pluck work in this environment?

Both no.

pint , xarray are both not importable, and in both cases, the version is buried very deeply in the code.

tlz: 0.11.2

**Comment by t20100** [comment]
Can you update `tlz`? Does it fixes the issue?

**Comment by kklmn** [comment]
Yes! Updated to toolz-0.12.0 and it works!
Thanks!
