### ISSUE TITLE
h5todict string issue

### ISSUE THREAD

**Issue by woutdenolf** [silx-kit/silx#3747]
```
Traceback (most recent call last):
  File "inspect_h5master.py", line 6, in <module>
    adict = nxtodict(master, errors="ignore", asarray=False)
  File "/users/denolf/virtualenvs/ewoks/ubuntu_20_04/py38/lib/python3.8/site-packages/silx/io/dictdump.py", line 746, in nxtodict
    nxtreedict = h5todict(h5file, include_attributes=include_attributes, **kw)
  File "/users/denolf/virtualenvs/ewoks/ubuntu_20_04/py38/lib/python3.8/site-packages/silx/io/dictdump.py", line 621, in h5todict
    for aname, avalue in attrs.items():
  File "/users/denolf/virtualenvs/ewoks/ubuntu_20_04/py38/lib/python3.8/site-packages/silx/io/utils.py", line 1170, in items
    yield k, self[k]
  File "/users/denolf/virtualenvs/ewoks/ubuntu_20_04/py38/lib/python3.8/site-packages/silx/io/utils.py", line 1159, in __getitem__
    return h5py_encode_value(value, encoding="utf-8")
  File "/users/denolf/virtualenvs/ewoks/ubuntu_20_04/py38/lib/python3.8/site-packages/silx/io/utils.py", line 1053, in h5py_encode_value
    return value.encode(encoding, errors=errors)
AttributeError: 'numpy.bytes_' object has no attribute 'encode'
```

**Comment by t20100** [comment]
Do you have a file to reproduce?
Which version of h5py do you have the problem with?

**Comment by woutdenolf** [comment]
I'm not sure I can share the file. It was not produced by `h5py`.

**Comment by t20100** [comment]
Looking at this, the problem is with "fixed-length" ASCII strings attributes which does not get decoded as "variable-length" ASCII strings.
This raises the same exception:

```python
f = h5py.File("test.h5", "w")
f.attrs["ascii_fl"] = numpy.array("text".encode("ascii"), dtype=h5py.string_dtype('ascii', 5))
# f.attrs["ascii_vl"] = numpy.array("text".encode("ascii"), dtype=h5py.string_dtype('ascii', None))
f.close()
```

See https://docs.h5py.org/en/stable/strings.html

**Comment by t20100** [comment]
The behavior of ASCII fixed/variable length string is not consistent with datasets:
ASCII string attributes:
- Fixed-length -> numpy.bytes_
- Variable-length -> str
ASCII string datasets:
- Fixed-length -> numpy.bytes_
- Variable-length -> bytes

**Comment by woutdenolf** [comment]
Thanks for the analysis. I'll add tests for all that.
