### ISSUE TITLE
Error on plot creation

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#3760]
Got that exception when i was displaying an image from a new plot in Flint.

No idea why it happens or how to reproduce it.

```
CRITICAL:bliss.flint.flint:Uncaught exception
Traceback (most recent call last):
  File "/nobackup/lvalls1/valls/Software/miniconda3/envs/blissdev/lib/python3.9/site-packages/silx/gui/plot/backends/BackendMatplotlib.py", line 1376, in __deferredReplot
    self.replot()
  File "/nobackup/lvalls1/valls/Software/miniconda3/envs/blissdev/lib/python3.9/site-packages/silx/gui/plot/backends/BackendMatplotlib.py", line 1545, in replot
    self.draw()
  File "/nobackup/lvalls1/valls/Software/miniconda3/envs/blissdev/lib/python3.9/site-packages/silx/gui/plot/backends/BackendMatplotlib.py", line 1494, in draw
    FigureCanvasQTAgg.draw(self)
  File "/nobackup/lvalls1/valls/Software/miniconda3/envs/blissdev/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 436, in draw
    self.figure.draw(self.renderer)
  File "/nobackup/lvalls1/valls/Software/miniconda3/envs/blissdev/lib/python3.9/site-packages/matplotlib/artist.py", line 74, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/nobackup/lvalls1/valls/Software/miniconda3/envs/blissdev/lib/python3.9/site-packages/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer)
  File "/nobackup/lvalls1/valls/Software/miniconda3/envs/blissdev/lib/python3.9/site-packages/matplotlib/figure.py", line 2831, in draw
    artists = self._get_draw_artists(renderer)
  File "/nobackup/lvalls1/valls/Software/miniconda3/envs/blissdev/lib/python3.9/site-packages/matplotlib/figure.py", line 235, in _get_draw_artists
    pos = locator(ax, renderer)
  File "/nobackup/lvalls1/valls/Software/miniconda3/envs/blissdev/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 119, in __call__
    self._transform - ax.figure.transSubfigure)
  File "/nobackup/lvalls1/valls/Software/miniconda3/envs/blissdev/lib/python3.9/site-packages/matplotlib/transforms.py", line 1470, in __sub__
    return self + other.inverted()
  File "/nobackup/lvalls1/valls/Software/miniconda3/envs/blissdev/lib/python3.9/site-packages/matplotlib/transforms.py", line 1890, in inverted
    self._inverted = Affine2D(inv(mtx), shorthand_name=shorthand_name)
  File "<__array_function__ internals>", line 180, in inv
  File "/nobackup/lvalls1/valls/Software/miniconda3/envs/blissdev/lib/python3.9/site-packages/numpy/linalg/linalg.py", line 552, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
  File "/nobackup/lvalls1/valls/Software/miniconda3/envs/blissdev/lib/python3.9/site-packages/numpy/linalg/linalg.py", line 89, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.LinAlgError: Singular matrix
```

**Comment by t20100** [comment]
any idea of the version of matplotlib?

**Comment by vallsv** [comment]
Here is the mpl version
```
$ conda run -n blissdev conda list matplotlib
# Name                    Version                   Build  Channel
matplotlib                3.5.3                    pypi_0    pypi
matplotlib-inline         0.1.6                    pypi_0    pypi
```

**Comment by t20100** [comment]
Closing, no idea how to reproduce
