### ISSUE TITLE
Assertion while playing with ProfileImageLineROI

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#3844]
While working on a profile for the CompareImage plot, i found that the coords/profile returned by `ProfileImageLineROI` can mismatch by 1.

This could be due to my setup and changes. But this also could be due to other stuffs.

```
Traceback (most recent call last):
  File "/nobackup/lvalls1/valls/workspace/silx.git/build/lib.linux-x86_64-3.7/silx/gui/plot/tools/profile/manager.py", line 892, in __displayResult
    window.setProfile(lastData)
  File "/nobackup/lvalls1/valls/workspace/silx.git/build/lib.linux-x86_64-3.7/silx/gui/plot/tools/profile/manager.py", line 348, in setProfile
    self._setRgbaProfile(data)
  File "/nobackup/lvalls1/valls/workspace/silx.git/build/lib.linux-x86_64-3.7/silx/gui/plot/tools/profile/manager.py", line 314, in _setRgbaProfile
    legend="green", color="green")
  File "/nobackup/lvalls1/valls/workspace/silx.git/build/lib.linux-x86_64-3.7/silx/gui/plot/PlotWidget.py", line 1209, in addCurve
    curve.setData(x, y, xerror, yerror, baseline=baseline, copy=copy)
  File "/nobackup/lvalls1/valls/workspace/silx.git/build/lib.linux-x86_64-3.7/silx/gui/plot/items/curve.py", line 292, in setData
    copy=copy)
  File "/nobackup/lvalls1/valls/workspace/silx.git/build/lib.linux-x86_64-3.7/silx/gui/plot/items/core.py", line 1629, in setData
    assert len(x) == len(y)
AssertionError
```

Printing the coords and profile shape returned me:
```
(378,) (378,)
(379,) (378,)
(379,) (378,)
```

**Comment by vallsv** [comment]
I think that's about the thread.

The processing is based on the item location, which is extracted multiple time for each composite (`_getRoiInfo`).

So the info can change in between.

That's easy to fix.
