### ISSUE TITLE
Validate Python 3.12

### ISSUE THREAD

**Issue by kif** [silx-kit/silx#3947]
While testing pyFAI for python_3.12, the build from source of silx did crash ... I am investigating.
https://github.com/silx-kit/pyFAI/issues/1961

**Comment by kif** [comment]
The `main` branch does build properly with a `pip install .`

**Comment by kif** [comment]
I can confirm that the latest release (v1.1.2) does not build with python 3.12:
```
lintaillefer:/tmp/silx-1.1.2 % python
Python 3.12.0 | packaged by conda-forge | (main, Oct  3 2023, 08:43:22) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
lintaillefer:/tmp/silx-1.1.2 % python -m build -w
* Creating venv isolated environment...
* Installing packages in isolated environment... (Cython>=0.21.1, numpy>=1.12, setuptools<60.0.0, wheel)
* Getting build dependencies for wheel...

Traceback (most recent call last):
  File "/users/kieffer/.venv/py312/lib/python3.12/site-packages/pyproject_hooks/_impl.py", line 321, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
  File "/users/kieffer/.venv/py312/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
    obj = import_module(mod_path)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/mamba/envs/python_3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1304, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/tmp/build-env-4rstc2v2/lib/python3.12/site-packages/setuptools/__init__.py", line 10, in <module>
    import distutils.core
ModuleNotFoundError: No module named 'distutils'

ERROR Backend 'setuptools.build_meta' is not available.
```

**Comment by t20100** [comment]
That's maybe due to `setuptools<60.0.0`... Next release will support python3.12

**Comment by t20100** [comment]
Thanks for the testing!

**Comment by t20100** [comment]
I'm closing this: Python 3.12 has been added to CI and some effort made to fix issues with this version of Python.
Next release will fully support it.
