### ISSUE TITLE
python-dateutil is mandatory

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#4004]
Sounds like python-dateutil is mandatory now

If that's really the case, it would be better to put it in the requirements by default.

```
Traceback (most recent call last):
  File "/nobackup/lvalls1/valls/workspace/silx.git/./bootstrap.py", line 295, in <module>
    main(sys.argv)
  File "/nobackup/lvalls1/valls/workspace/silx.git/./bootstrap.py", line 239, in main
    run_file(target, argv)
  File "/nobackup/lvalls1/valls/workspace/silx.git/./bootstrap.py", line 102, in run_file
    execfile(filename, module_globals, module_globals)
  File "/nobackup/lvalls1/valls/workspace/silx.git/./bootstrap.py", line 75, in execfile
    exec(code, globals, locals)
  File "/nobackup/lvalls1/valls/workspace/silx.git/examples/plotWidget.py", line 44, in <module>
    from silx.gui.plot import PlotWidget
  File "/nobackup/lvalls1/valls/workspace/silx.git/build/lib.linux-x86_64-3.9/silx/gui/plot/__init__.py", line 62, in <module>
    from .PlotWidget import PlotWidget  # noqa
  File "/nobackup/lvalls1/valls/workspace/silx.git/build/lib.linux-x86_64-3.9/silx/gui/plot/PlotWidget.py", line 61, in <module>
    from . import PlotInteraction
  File "/nobackup/lvalls1/valls/workspace/silx.git/build/lib.linux-x86_64-3.9/silx/gui/plot/PlotInteraction.py", line 41, in <module>
    from . import items
  File "/nobackup/lvalls1/valls/workspace/silx.git/build/lib.linux-x86_64-3.9/silx/gui/plot/items/__init__.py", line 63, in <module>
    from .image_aggregated import ImageDataAggregated  # noqa
  File "/nobackup/lvalls1/valls/workspace/silx.git/build/lib.linux-x86_64-3.9/silx/gui/plot/items/image_aggregated.py", line 40, in <module>
    from .axis import Axis
  File "/nobackup/lvalls1/valls/workspace/silx.git/build/lib.linux-x86_64-3.9/silx/gui/plot/items/axis.py", line 37, in <module>
    import dateutil.tz
ModuleNotFoundError: No module named 'dateutil'

```

**Comment by vallsv** [comment]
ah ok, everything is optional... well, lets dig into the stuff...
