### ISSUE TITLE
CI failure on colormapdialog on PySide6/py3.9

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#4032]
Sounds like it happens time to time.

https://github.com/silx-kit/silx/actions/runs/7275653478/job/19823910703?pr=4028

```
ERROR ../../../hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/silx/gui/dialog/test/test_colormapdialog.py::TestColormapDialog::testGUIEdition - AssertionError: Exception occured in Qt thread:
Traceback (most recent call last):
  File "/Users/runner/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/silx/gui/plot/backends/BackendMatplotlib.py", line 1517, in __deferredReplot
    self.replot()
  File "/Users/runner/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/silx/gui/plot/backends/BackendMatplotlib.py", line 1694, in replot
    self.draw()
  File "/Users/runner/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/silx/gui/plot/backends/BackendMatplotlib.py", line 1643, in draw
    FigureCanvasQTAgg.draw(self)
  File "/Users/runner/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 391, in draw
    super().draw()
  File "/Users/runner/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/matplotlib/backends/backend_qt.py", line 428, in draw
    self.update()
RuntimeError: Internal C++ object (BackendMatplotlibQt) already deleted.
```

**Comment by vallsv** [comment]
That's also maybe a problem on the way the test is written, because here i understand it's the backend which was already released.

**Comment by t20100** [comment]
There's already some protection in the backend right before calling `draw`:
Here: https://github.com/silx-kit/silx/blob/6a86f24f7b591457ecfad83e34e4cc77cd0711ff/src/silx/gui/plot/backends/BackendMatplotlib.py#L1683C12-L1685

And I recently added a second one here:
https://github.com/silx-kit/silx/blob/6a86f24f7b591457ecfad83e34e4cc77cd0711ff/src/silx/gui/plot/backends/BackendMatplotlib.py#L1642-L1644

But that's not enough, the backend in there when calling `draw`, but it gets cleaned during the call. Maybe a garbage collection of a cycle of reference 🤷 .
