### ISSUE TITLE
`imshow` not defined

### ISSUE THREAD

**Issue by dgtlmoon** [silx-kit/silx#471]
I'm following 

https://pythonhosted.org/silx/Tutorials/Sift/sift.html

```
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy.misc
>>> image = scipy.misc.ascent()
>>> imshow(image, cmap="gray")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'imshow' is not defined
>>> 

```

**Comment by dgtlmoon** [comment]
```
>>> scipy.misc.imshow(image, cmap="gray")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: imshow() got an unexpected keyword argument 'cmap'

```

**Comment by vasole** [comment]
The tutorial assumes you are inside a Jupiter notebook.

To replicate the behavior from inside the Python interpreter you can give a try to ``from pylab import *``

**Comment by dgtlmoon** [comment]
fantastic, thank you!
