### ISSUE TITLE
silx is unable to find device (either CPU or GPU)

### ISSUE THREAD

**Issue by dgtlmoon** [silx-kit/silx#473]
Approximately following http://www.silx.org/doc/silx/dev/Tutorials/Sift/sift.html , I get this error that I'm unable to work around

Some simple python code based on http://www.silx.org/doc/silx/dev/Tutorials/Sift/sift.html

```
import scipy.misc
import os
from silx.image import sift
from pylab import *
import numpy
from numpy import median
import pyopencl

image = scipy.misc.ascent()
imshow(image, cmap="gray")
os.environ["PYOPENCL_COMPILER_OUTPUT"] = "1" #set to 1 to see the compilation going on
sift_ocl = sift.SiftPlan(template=image, devicetype="GPU") #switch to GPU to test your graphics card
keypoints = sift_ocl(image)
# Shift new image
shifted = numpy.zeros_like(image)
shifted[5:,8:] = image[:-5, :-8]
shifted_points = sift_ocl(shifted)
# Match
mp = sift.MatchPlan()
match = mp(keypoints, shifted_points)
```

The error when `devicetype="GPU"`

```
Traceback (most recent call last):
  File "./sift.py", line 31, in <module>
    mp = sift.MatchPlan()
  File "/usr/local/lib/python2.7/dist-packages/silx/image/sift/match.py", line 107, in __init__
    self.ctx = pyopencl.Context(devices=[pyopencl.get_platforms()[self.device[0]].get_devices()[self.device[1]]])
TypeError: 'NoneType' object has no attribute '__getitem__'

```

The error when `devicetype="CPU"`

```
WARNING:sift.plan:Unable to find suitable device, selecting device: 0,0
Traceback (most recent call last):
  File "./sift.py", line 19, in <module>
    mp = sift.MatchPlan()
  File "/usr/local/lib/python2.7/dist-packages/silx/image/sift/match.py", line 107, in __init__
    self.ctx = pyopencl.Context(devices=[pyopencl.get_platforms()[self.device[0]].get_devices()[self.device[1]]])
TypeError: 'NoneType' object has no attribute '__getitem__'
```

Poking about with `pyopencl` I can see things work

```
>>> import pyopencl
>>> 
>>> pyopencl.get_platforms()
[<pyopencl.Platform 'NVIDIA CUDA' at 0x2b496b0>]
>>> 
>>> 
>>> pyopencl.get_platforms()[0].get_devices()
[<pyopencl.Device 'GeForce GTX 960M' on 'NVIDIA CUDA' at 0x2b40e90>]
```

Running `pyopencl (2016.2)` and `silx (0.3.0)`,  CPU is `Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz` on Ubuntu 16.04

`nvidia-smi` tells me all is fine also

```
$ nvidia-smi
Thu Dec 15 21:05:11 2016       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 367.57                 Driver Version: 367.57                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 960M    Off  | 0000:01:00.0     Off |                  N/A |
| N/A   51C    P0    N/A /  N/A |    807MiB /  2002MiB |     12%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      1798    G   /usr/lib/xorg/Xorg                             580MiB |
|    0      5453    G   ...gn/Enabled/GoogleBrandedContextMenu/brand   226MiB |
+-----------------------------------------------------------------------------+
```

I should add that I see the same error when i run https://github.com/silx-kit/silx/blob/master/silx/image/sift/match.py

```
WARNING:sift.plan:Unable to find suitable device, selecting device: 0,0
Traceback (most recent call last):
  File "./match.py", line 350, in <module>
    demo()
  File "./match.py", line 343, in demo
    mp = MatchPlan()
  File "./match.py", line 107, in __init__
    self.ctx = pyopencl.Context(devices=[pyopencl.get_platforms()[self.device[0]].get_devices()[self.device[1]]])
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by dgtlmoon** [comment]
i added some debug to `/usr/local/lib/python2.7/dist-packages/silx/image/sift/match.py`

`Device is None self.memory is 'None' devicetype is 'CPU' result from ocl.select_device is 'None'`

So it seems that `ocl.select_device()` is failing

```
    def __init__(self, size=16384, devicetype="CPU", profile=False, device=None, max_workgroup_size=None, roi=None, context=None):
        """Constructor of the class:

        :param size: size of the input keypoint-list alocated on the GPU.
        :param devicetype: can be CPU or GPU
        :param profile: set to true to activate profiling information collection
        :param device: 2-tuple of integer, see clinfo
        :param max_workgroup_size: CPU on MacOS, limit to 1. None by default to use default ones (max=128).
        :param roi: Region Of Interest: TODO
        :param context: Use an external context (discard devicetype and device options)
        """
        self.profile = bool(profile)
        self.events = []
        self.kpsize = size
        self.buffers = {}
        self.programs = {}
        self.memory = None
        self.octave_max = None
        self.red_size = None
        if context:
            self.ctx = context
            device_name = self.ctx.devices[0].name.strip()
            platform_name = self.ctx.devices[0].platform.name.strip()
            platform = ocl.get_platform(platform_name)
            device = platform.get_device(device_name)
            self.device = platform.id, device.id
        else:
            if device is None:
                self.device = ocl.select_device(type=devicetype, memory=self.memory, best=True)
                print ("Device is None self.memory is '%s' devicetype is '%s' result from ocl.select_device is '%s'" %(self.memory, devicetype, self.device)) 

            else:
                self.device = device

            self.ctx = pyopencl.Context(devices=[pyopencl.get_platforms()[self.device[0]].get_devices()[self.device[1]]])

```

**Comment by kif** [comment]
On Sun, 18 Dec 2016 02:58:16 -0800
dgtlmoon <notifications@github.com> wrote:

> i added some debug to `/usr/local/lib/python2.7/dist-packages/silx/image/sift/match.py`
> 
> `Device is None self.memory is 'None' devicetype is 'CPU' result from ocl.select_device is 'None'`
> 
> So it seems that `ocl.select_device()` is failing

Hi,

Is PyOpenCL installed and working ?

in python, does:
```
import pyopencl
pyopencl.create_some_context()
```
give you anything ?

This may crash if you have an nvidia GPU but it is disabled (for
example in an optimus configuration).

SIFT cannot work if the system is not properly installed/running

Cheers,

Jerome

**Comment by dgtlmoon** [comment]
Heya, thanks for the reply.

yeah so...


```
>>> import pyopencl
>>> pyopencl.create_some_context()
Choose platform:
[0] <pyopencl.Platform 'NVIDIA CUDA' at 0x2e13660>
Choice [0]:0
Set the environment variable PYOPENCL_CTX='0' to avoid being asked again.
<pyopencl.Context at 0x2c72da0 on <pyopencl.Device 'GeForce GTX 960M' on 'NVIDIA CUDA' at 0x2e0ae40>>

```

unsure, like I shown above `nvidia-smi` says everything is functioning

**Comment by dgtlmoon** [comment]
@kif What version of `pyopencl` are you running? it's not something like an API change is it?

**Comment by kif** [comment]
On Sun, 18 Dec 2016 14:19:19 -0800
dgtlmoon <notifications@github.com> wrote:

I have tested various versions from 2013 to the most recent ones and did not notice any API change.

silx provids a "flops" calculator for selecting the device. maybe it fails on your specific device.
Can you provide me with the nvidia major and minor versions of your hardware ?

https://github.com/kif/silx/blob/master/silx/opencl/__init__.py#L66

maybe your GPU is nor recognized.

Cheers,

Jerome

**Comment by dgtlmoon** [comment]
Heya Jerome,

I believe the major/minor version is `367.57`

![screenshot_2016-12-19_09-47-56](https://cloud.githubusercontent.com/assets/275001/21306237/49ffc22a-c5d0-11e6-9c7a-aa8c1f0fd6b1.png)
![screenshot_2016-12-19_09-47-23](https://cloud.githubusercontent.com/assets/275001/21306238/49fff74a-c5d0-11e6-8887-4a738f2fc1fb.png)


```
Mon Dec 19 09:46:18 2016       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 367.57                 Driver Version: 367.57                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 960M    Off  | 0000:01:00.0     Off |                  N/A |
| N/A   59C    P0    N/A /  N/A |   1089MiB /  2002MiB |      8%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      1786    G   /usr/lib/xorg/Xorg                             670MiB |
|    0      5609    G   ...gn/Enabled/GoogleBrandedContextMenu/brand   418MiB |
+-----------------------------------------------------------------------------+

```

**Comment by kif** [comment]
On Mon, 19 Dec 2016 00:49:07 -0800
dgtlmoon <notifications@github.com> wrote:

> Heya Jerome,
> 
> I believe the major/minor version is `367.57`

Actually the 960M is a compute-capability 5.0 which should be
recognized. We use plenty of "GeForce 750Ti" which are roughly the same
and work very well.

If you have only 1 OpenCL device, its ID should be "0,0"
So you can check it works with:
```
import silx.opencl
ctx = silx.opencl.ocl.create_context(platformid=0, deviceid=0)
print(ctx)
from silx.image.sift.match import MatchPlan
mp = MatchPlan(context=ctx)
```

then you can use your matchplan.

If this works, it means there is a bug in the OpenCL class.

Cheers,

Jerome

**Comment by dgtlmoon** [comment]
Hey Jerome, 

ok - drumroll..

```
$ cat >f.py
import silx.opencl
ctx = silx.opencl.ocl.create_context(platformid=0, deviceid=0)
print(ctx)
from silx.image.sift.match import MatchPlan
mp = MatchPlan(context=ctx)
```

```
$ python f.py 
<pyopencl.Context at 0x2353c70 on <pyopencl.Device 'GeForce GTX 960M' on 'NVIDIA CUDA' at 0x20c3d30>>
```

looks like a bug perhaps?

**Comment by dgtlmoon** [comment]
I just tried the code from my first comment here to verify that the situation is still the same

```
Device is None self.memory is 'None' devicetype is 'CPU' result from ocl.select_device is 'None'
Traceback (most recent call last):
  File "err.py", line 19, in <module>
    mp = sift.MatchPlan()
  File "/usr/local/lib/python2.7/dist-packages/silx/image/sift/match.py", line 110, in __init__
    self.ctx = pyopencl.Context(devices=[pyopencl.get_platforms()[self.device[0]].get_devices()[self.device[1]]])
TypeError: 'NoneType' object has no attribute '__getitem__'

```

**Comment by dgtlmoon** [comment]
@kif The other problem here is that `sift.SiftPlan` does not accept `context=ctx` like `MatchPlan(...)` does

**Comment by kif** [comment]
Hi,

There is apparently a bug in the context creation.

The MarchPlan creation was OK when you provide the context to use. Then you can use it for doing keypoint matching.

The development branch of silx has the context keyword for the SiftPlan class and it should work. Maybe you should upgrade your installation to the v0.4 (still in development)
https://github.com/silx-kit/silx/blob/master/silx/image/sift/plan.py

cheers,

**Comment by dgtlmoon** [comment]
@vallsv FWIW, retesting this issue with the same test code in first comment gives me #521
