### ISSUE TITLE
AttributeError: 'module' object has no attribute 'dtype' (h5py error after upgrading silx)

### ISSUE THREAD

**Issue by dgtlmoon** [silx-kit/silx#521]
Re-running the test code from #473 

I am on `h5py (2.6.0)` and `silx (0.4.0a0)` following install instructions from

```
git clone https://github.com/silx-kit/silx.git
cd silx
pip install . --user
```

```
# pip install h5py
Collecting h5py
  Downloading h5py-2.6.0-1-cp27-cp27mu-manylinux1_x86_64.whl (4.2MB)
    100% |████████████████████████████████| 4.2MB 285kB/s 
Requirement already satisfied: numpy>=1.6.1 in /usr/local/lib/python2.7/dist-packages (from h5py)
Requirement already satisfied: six in /usr/lib/python2.7/dist-packages (from h5py)
Installing collected packages: h5py
Successfully installed h5py-2.6.0
```

test code from first comment of #473 ..

```
import scipy.misc
import os
from silx.image import sift
from pylab import *
import numpy
from numpy import median
import pyopencl

image = scipy.misc.ascent()
imshow(image, cmap="gray")
os.environ["PYOPENCL_COMPILER_OUTPUT"] = "1" #set to 1 to see the compilation going on
sift_ocl = sift.SiftPlan(template=image, devicetype="GPU") #switch to GPU to test your graphics card
keypoints = sift_ocl(image)
# Shift new image
shifted = numpy.zeros_like(image)
shifted[5:,8:] = image[:-5, :-8]
shifted_points = sift_ocl(shifted)
# Match
mp = sift.MatchPlan()
match = mp(keypoints, shifted_points)
```

I get...

```
Traceback (most recent call last):
  File "p.py", line 1, in <module>
    import scipy.misc
  File "/usr/local/lib/python2.7/dist-packages/scipy/__init__.py", line 61, in <module>
    from numpy import show_config as show_numpy_config
  File "/usr/local/lib/python2.7/dist-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/usr/local/lib/python2.7/dist-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/__init__.py", line 58, in <module>
    from numpy.testing.nosetester import _numpy_tester
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/__init__.py", line 12, in <module>
    from . import decorators as dec
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/decorators.py", line 21, in <module>
    from .utils import SkipTest
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 15, in <module>
    from tempfile import mkdtemp, mkstemp
  File "/usr/lib/python2.7/tempfile.py", line 32, in <module>
    import io as _io
  File "/tmp/silx/silx/io/__init__.py", line 38, in <module>
    from .utils import open  # pylint:disable=redefined-builtin
  File "/tmp/silx/silx/io/utils.py", line 34, in <module>
    import h5py
  File "/usr/local/lib/python2.7/dist-packages/h5py/__init__.py", line 34, in <module>
    from ._conv import register_converters as _register_converters
  File "h5py/h5t.pxd", line 14, in init h5py._conv (/tmp/pip-4rPeHA-build/h5py/_conv.c:7359)
  File "h5py/numpy.pxd", line 66, in init h5py.h5t (/tmp/pip-4rPeHA-build/h5py/h5t.c:20346)
AttributeError: 'module' object has no attribute 'dtype'

```

**Comment by dgtlmoon** [comment]
i suspect this may be due to weird mixed python versions

**Comment by dgtlmoon** [comment]
doh, running this from within the silx/silx dir was not smart...
