### ISSUE TITLE
[console] IPythonWidget breaks the python environment

### ISSUE THREAD

**Issue by PiRK** [silx-kit/silx#538]
While working on PR #530, we found that the `silx.gui.console` tests break the python environment and cause the following unit test to stall.

To replicate the issue, in a Python terminal:

```
>>> a = 1
>>> from silx.gui import qt
>>> app = qt.QApplication([])
>>> from silx.gui import console
>>> ipythonwidget = console.IPythonWidget()
In : 
In : a
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'a' is not defined
In : app
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'app' is not defined
In : qt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'qt' is not defined
In : 
```

Once the IPythonWidget is created, we lose access to the original python console.

**Comment by PiRK** [comment]
Now that the issue is known, the immediate fix will be to disable the `console` tests in #530.

Additional investigations will be needed to assess the risks of keeping the option in PlotWindow to open a console widget. So far no issue has been raised related to this feature, the console widget does not seem to break applications including a PlotWindow (to be confirmed).
.

**Comment by vasole** [comment]
Concerning the variables, one can push variables to the widgets.

I did not have troubles attaching consoles to widgets nor making variables common to the console and to the parent widget.

**Comment by PiRK** [comment]
Pushing variables to the widget works, when done in a python source file. For instance, the following script works as expected (if saved as a `.py` file and executed with `python consoletest.py`) :
```
from silx.gui import qt
from silx.gui import console

a = 1
app = qt.QApplication([])

ipythonwidget = console.IPythonWidget()
ipythonwidget.pushVariables(
    {"app": app, "a": a})
ipythonwidget.show()

app.exec_()
```

**Comment by PiRK** [comment]
So far it seems to cause a problem only in a python interactive console and on some CI platforms.

**Comment by payno** [comment]
On my side with PySide6 and PyQt5 with python 3.12 I cannot reproduce...
