### ISSUE TITLE
[io] Test fails on Debian 8 with python3

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#548]
```
======================================================================
FAIL: test_metadata_list_looks_like_list (silx.io.test.test_fabioh5.TestFabioH----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tvincent/silx/build/lib.linux-x86_64-3.4/silx/io/test/test_fabioh5.py", line 146, in test_metadata_list_looks_like_list
    self.assertEquals(dataset[()], "2000 hi!")
AssertionError: array([b'2000 hi!'], 
      dtype='|S8') != '2000 hi!'

======================================================================
FAIL: test_metadata_string (silx.io.test.test_fabioh5.TestFabioH5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tvincent/silx/build/lib.linux-x86_64-3.4/silx/io/test/test_fabioh5.py", line 123, in test_metadata_string
    self.assertEquals(dataset[()], "hi!")
AssertionError: array([b'hi!'], 
      dtype='|S3') != 'hi!'
```

Using `b'hi!'` fixes the problem.

I guess those tests are not run by continuous integration because fabio is not installed there...

**Comment by vasole** [comment]
For the purpose of testing, I would test in ['hi!", b"hi"] instead of the equality unless we want to get exposed to changes in h5py returning one day bytes other day unicode.

**Comment by vallsv** [comment]
That's a fabio wrapping anyway. It do no use h5py at all.
I will check that now. Thanks for the feed back.
