### ISSUE TITLE
[plot] Color consistance

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#640]
`addMarker` do not support numpy array as color, while `addCurve` support it. It would be good to have the same API.

```
Traceback (most recent call last):
  File "/home/valls/.local/lib/python2.7/site-packages/silx/gui/plot/Plot.py", line 1210, in addMarker
    symbol=symbol, constraint=constraint)
  File "/home/valls/.local/lib/python2.7/site-packages/silx/gui/plot/Plot.py", line 1229, in _addMarker
    elif color in self.colorDict:
TypeError: unhashable type: 'numpy.ndarray'
```

**Comment by t20100** [comment]
Closing as this was fixed by PR #621
