### ISSUE TITLE
[plot] Exception when displaying an image containing only infinit values (Silx 0.4)

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#666]
It should be tested on the dev branch

```
Traceback (most recent call last):
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/data/DataViewer.py", line 888, in __setDataInView
    self.__currentView.setData(self.__displayedData)
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/data/DataViewer.py", line 408, in setData
    resetzoom=self.__resetZoomNextTime)
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/plot/Plot.py", line 978, in addImage
    colormap=params['colormap'])
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/plot/BackendMatplotlib.py", line 264, in addImage
    scalarMappable = Colors.getMPLScalarMappable(colormap, data)
  File "/home/valls/.local/lib/python3.5/site-packages/silx/gui/plot/Colors.py", line 284, in getMPLScalarMappable
    vmin = finiteData.min()
  File "/home/valls/.local/lib/python3.5/site-packages/numpy/core/_methods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation minimum which has no identity
Aborted
```

**Comment by t20100** [comment]
Seems the colormap is trying to compute its bounds and nothing checks it fails to do so.

**Comment by t20100** [comment]
Closing as it's working with tip of silx.
