### ISSUE TITLE
[install] It is not possible to install silx with pip

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#673]
From a blank install, dependencies are not installed automatically.
```
(toto)valls@rnice8-0208:~/virtual_env/toto$ pip install pip --upgrade
Requirement already up-to-date: pip in ./lib/python2.7/site-packages
(toto)valls@rnice8-0208:~/virtual_env/toto$ pip install silx
Collecting silx
  Using cached silx-0.4.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-pTD0mc/silx/setup.py", line 45, in <module>
        "To install this package, you must install numpy first\n"
    ImportError: To install this package, you must install numpy first
    (See https://pypi.python.org/pypi/numpy)
```
We should check scikit-learn `setup.py` to improve our `setup.py` (https://github.com/scikit-learn/scikit-learn/blob/master/setup.py)

**Comment by vallsv** [comment]
Closed by https://github.com/silx-kit/silx/pull/675
