### ISSUE TITLE
[build] Fail to build master Debian8 package on scisoft13

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#699]
Hi, i try 2 times to build debian package on scisoft13, from a fresh git clone.
```
git clone http://github.com/silx-kit/silx .
./build-deb8.sh
```
It fails 2 times with different exceptions (the first one was with CUDA something...). Here is a tail of the trace.
I would like here, cause i dont really know what does it means.
Is there something interesting here?
```
copying static files... done
copying extra files... done
dumping search index... done
dumping object inventory... done
build succeeded, 20 warnings.
creating /mntdirect/_bliss/users/valls/workspace/test_build_silx/package/silx-0.5.0a0/build/sphinx/latex
Running Sphinx v1.2.3
loading pickled environment... done
building [latex]: all documents
updating environment: 0 added, 5 changed, 0 removed
reading sources... [ 20%] description/sift
reading sources... [ 40%] modules/gui/plot/dev
reading sources... [ 60%] modules/gui/plot3d/_font
reading sources... [ 80%] modules/gui/plot3d/glutils
reading sources... [100%] modules/gui/plot3d/utils

/mntdirect/_bliss/users/valls/workspace/test_build_silx/package/silx-0.5.0a0/doc/source/description/sift.rst:None: WARNING: image file not readable: description/img/sift_match2.jpg
/mntdirect/_bliss/users/valls/workspace/test_build_silx/package/silx-0.5.0a0/doc/source/description/sift.rst:None: WARNING: image file not readable: description/img/sift_frame_ROI.jpg
/mntdirect/_bliss/users/valls/workspace/test_build_silx/package/silx-0.5.0a0/doc/source/modules/gui/plot/dev.rst:74: WARNING: autodoc: failed to import module u'silx.gui.plot.BackendBase'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 335, in import_object
    __import__(self.modname)
ImportError: No module named BackendBase
/mntdirect/_bliss/users/valls/workspace/test_build_silx/package/silx-0.5.0a0/doc/source/modules/gui/plot/dev.rst:82: WARNING: autodoc: failed to import module u'silx.gui.plot.BackendMatplotlib'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 335, in import_object
    __import__(self.modname)
ImportError: No module named BackendMatplotlib
/mntdirect/_bliss/users/valls/workspace/test_build_silx/package/silx-0.5.0a0/doc/source/modules/gui/plot/dev.rst:138: WARNING: autodoc: failed to import module u'silx.gui.plot.ModestImage'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 335, in import_object
    __import__(self.modname)
ImportError: No module named ModestImage
/mntdirect/_bliss/users/valls/workspace/test_build_silx/package/silx-0.5.0a0/doc/source/modules/gui/plot3d/_font.rst:6: WARNING: autodoc: failed to import module u'silx.gui.plot3d._font'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 335, in import_object
    __import__(self.modname)
ImportError: No module named _font
/mntdirect/_bliss/users/valls/workspace/test_build_silx/package/silx-0.5.0a0/doc/source/modules/gui/plot3d/glutils.rst:4: WARNING: autodoc: failed to import module u'silx.gui.plot3d.glutils'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 335, in import_object
    __import__(self.modname)
ImportError: No module named glutils
/mntdirect/_bliss/users/valls/workspace/test_build_silx/package/silx-0.5.0a0/doc/source/modules/gui/plot3d/glutils.rst:10: WARNING: autodoc: failed to import module u'silx.gui.plot3d.glutils.gl'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 335, in import_object
    __import__(self.modname)
ImportError: No module named glutils.gl
/mntdirect/_bliss/users/valls/workspace/test_build_silx/package/silx-0.5.0a0/doc/source/modules/gui/plot3d/glutils.rst:20: WARNING: autodoc: failed to import function u'getGLContext' from module u'silx.gui.plot3d.glutils'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 335, in import_object
    __import__(self.modname)
ImportError: No module named glutils
/mntdirect/_bliss/users/valls/workspace/test_build_silx/package/silx-0.5.0a0/doc/source/modules/gui/plot3d/glutils.rst:22: WARNING: autodoc: failed to import function u'setGLContextGetter' from module u'silx.gui.plot3d.glutils'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 335, in import_object
    __import__(self.modname)
ImportError: No module named glutils
/mntdirect/_bliss/users/valls/workspace/test_build_silx/package/silx-0.5.0a0/doc/source/modules/gui/plot3d/glutils.rst:26: WARNING: autodoc: failed to import function u'sizeofGLType' from module u'silx.gui.plot3d.glutils'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 335, in import_object
    __import__(self.modname)
ImportError: No module named glutils
/mntdirect/_bliss/users/valls/workspace/test_build_silx/package/silx-0.5.0a0/doc/source/modules/gui/plot3d/glutils.rst:28: WARNING: autodoc: failed to import function u'isSupportedGLType' from module u'silx.gui.plot3d.glutils'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 335, in import_object
    __import__(self.modname)
ImportError: No module named glutils
/mntdirect/_bliss/users/valls/workspace/test_build_silx/package/silx-0.5.0a0/doc/source/modules/gui/plot3d/glutils.rst:30: WARNING: autodoc: failed to import function u'numpyToGLType' from module u'silx.gui.plot3d.glutils'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 335, in import_object
    __import__(self.modname)
ImportError: No module named glutils
/mntdirect/_bliss/users/valls/workspace/test_build_silx/package/silx-0.5.0a0/doc/source/modules/gui/plot3d/glutils.rst:35: WARNING: autodoc: failed to import class u'Program' from module u'silx.gui.plot3d.glutils'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 335, in import_object
    __import__(self.modname)
ImportError: No module named glutils
/mntdirect/_bliss/users/valls/workspace/test_build_silx/package/silx-0.5.0a0/doc/source/modules/gui/plot3d/glutils.rst:41: WARNING: autodoc: failed to import class u'Texture' from module u'silx.gui.plot3d.glutils'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 335, in import_object
    __import__(self.modname)
ImportError: No module named glutils
/mntdirect/_bliss/users/valls/workspace/test_build_silx/package/silx-0.5.0a0/doc/source/modules/gui/plot3d/glutils.rst:47: WARNING: autodoc: failed to import class u'FramebufferTexture' from module u'silx.gui.plot3d.glutils'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 335, in import_object
    __import__(self.modname)
ImportError: No module named glutils
/mntdirect/_bliss/users/valls/workspace/test_build_silx/package/silx-0.5.0a0/doc/source/modules/gui/plot3d/glutils.rst:53: WARNING: autodoc: failed to import class u'VertexBuffer' from module u'silx.gui.plot3d.glutils'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 335, in import_object
    __import__(self.modname)
ImportError: No module named glutils
/mntdirect/_bliss/users/valls/workspace/test_build_silx/package/silx-0.5.0a0/doc/source/modules/gui/plot3d/glutils.rst:56: WARNING: autodoc: failed to import class u'VertexBufferAttrib' from module u'silx.gui.plot3d.glutils'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 335, in import_object
    __import__(self.modname)
ImportError: No module named glutils
/mntdirect/_bliss/users/valls/workspace/test_build_silx/package/silx-0.5.0a0/doc/source/modules/gui/plot3d/glutils.rst:59: WARNING: autodoc: failed to import function u'vertexBuffer' from module u'silx.gui.plot3d.glutils'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 335, in import_object
    __import__(self.modname)
ImportError: No module named glutils
/mntdirect/_bliss/users/valls/workspace/test_build_silx/package/silx-0.5.0a0/doc/source/modules/gui/plot3d/utils.rst:17: WARNING: autodoc: failed to import module u'silx.gui.plot3d.utils.ticklayout'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 335, in import_object
    __import__(self.modname)
ImportError: No module named ticklayout
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
processing silx.tex... index overview install description/index description/sift tutorials modules/gui/plot/getting_started modules/gui/plot/plotactions_examples modules/gui/designer Tutorials/Sift/sift Tutorials/specfile_to_hdf5 modules/gui/hdf5/getting_started modules/gui/hdf5/examples_hdf5widget Tutorials/fit Tutorials/fitconfig Tutorials/array_widget modules/index modules/gui/index modules/gui/console modules/gui/data/index modules/gui/data/arraytable modules/gui/data/dataviewerframe modules/gui/data/dataviewer modules/gui/data/numpyaxesselector modules/gui/data/textformatter modules/gui/fit/index modules/gui/fit/fitwidget modules/gui/fit/backgroundwidget modules/gui/hdf5/index modules/gui/hdf5/getting_started modules/gui/hdf5/examples_hdf5widget modules/gui/hdf5/hdf5treeview modules/gui/hdf5/hdf5treemodel modules/gui/hdf5/hdf5contextmenuevent modules/gui/hdf5/h5node modules/gui/hdf5/nexussortfilterproxymodel modules/gui/icons modules/gui/plot/index modules/gui/plot/getting_started modules/gui/plot/plotwidget modules/gui/plot/plotwindow modules/gui/plot/imageview modules/gui/plot/stackview modules/gui/plot/plot modules/gui/plot/items modules/gui/plot/plotactions modules/gui/plot/plottools modules/gui/plot/profile modules/gui/plot/roi modules/gui/plot/dev modules/gui/plot3d/index modules/gui/plot3d/plot3dwidget modules/gui/plot3d/plot3dwindow modules/gui/plot3d/scalarfieldview modules/gui/plot3d/sfviewparamtree modules/gui/plot3d/toolbars modules/gui/plot3d/actions modules/gui/plot3d/dev modules/gui/plot3d/glutils modules/gui/plot3d/scene modules/gui/plot3d/utils modules/gui/plot3d/_font modules/gui/plot3d/viewer3dvolume_example modules/gui/qt modules/gui/widgets/index modules/gui/widgets/framebrowser modules/gui/widgets/periodictable modules/gui/widgets/tablewidget modules/gui/widgets/threadpoolpushbutton modules/gui/widgets/waitingpushbutton modules/io/index modules/io/configdict modules/io/dictdump modules/io/octaveh5 modules/io/specfile modules/io/specfilewrapper modules/io/spech5 modules/io/spectoh5 modules/io/utils modules/image/index modules/image/bilinear modules/image/shapes modules/image/sift modules/math/index modules/math/fit/index modules/math/fit/leastsq modules/math/fit/peaksearch modules/math/fit/functions modules/math/fit/filters modules/math/fit/fitmanager modules/math/fit/fittheory modules/math/fit/fittheories modules/math/fit/bgtheories modules/math/histogram modules/math/medianfilter modules/resources modules/utils/index modules/utils/array_like modules/utils/decorators modules/utils/html modules/utils/weakref modules/test/index changelog license virtualenv 
resolving references...
writing... done
copying images... modules/gui/plot/img/PlotWindow.png modules/gui/plot3d/img/SFViewParamTree.png modules/gui/../../../../silx/resources/gui/icons/shape-rectangle.png modules/gui/../../../../silx/resources/gui/icons/draw-pencil.png modules/gui/plot/img/StackView.png modules/gui/../../../../silx/resources/gui/icons/shape-circle.png modules/gui/../../../../silx/resources/gui/icons/view-text.png modules/gui/../../../../silx/resources/gui/icons/colormap.png modules/gui/../../../../silx/resources/gui/icons/draw-brush.png modules/gui/../../../../silx/resources/gui/icons/pixel-intensities.png modules/gui/../../../../silx/resources/gui/icons/item-3dim.png modules/gui/../../../../silx/resources/gui/icons/image-select-erase.png modules/gui/fit/./img/bgwidget.png modules/gui/plot/img/Plot1D.png Tutorials/img/fitwidget1.png modules/gui/../../../../silx/resources/gui/icons/crop.png modules/gui/../../../../silx/resources/gui/icons/cube.png modules/gui/../../../../silx/resources/gui/icons/zoom-original.png modules/gui/../../../../silx/resources/gui/icons/plot-ydown.png modules/gui/../../../../silx/resources/gui/icons/document-save.png modules/gui/../../../../silx/resources/gui/icons/cube-left.png modules/gui/../../../../silx/resources/gui/icons/profile2D.png modules/gui/../../../../silx/resources/gui/icons/cube-right.png Tutorials/Sift/output_11_2.png Tutorials/img/arraywidget3D_0.png modules/gui/../../../../silx/resources/gui/icons/3d-plane-normal-z.png modules/gui/../../../../silx/resources/gui/icons/plot-ylog.png Tutorials/img/fitwidget3.png modules/gui/plot3d/img/Plot3DWidget.png modules/gui/../../../../silx/resources/gui/icons/math-average.png modules/gui/../../../../silx/resources/gui/icons/math-swap-sign.png modules/gui/../../../../silx/resources/gui/icons/remove.png description/img/sift_orientation.png modules/gui/../../../../silx/resources/gui/icons/plot-grid.png Tutorials/img/custom_config_scale1.0.png modules/gui/fit/../../../Tutorials/img/fitwidget4.png modules/gui/../../../../silx/resources/gui/icons/cube-front.png modules/gui/../../../../silx/resources/gui/icons/image-select-brush.png Tutorials/img/stripbg_plot1.png modules/gui/../../../../silx/resources/gui/icons/shape-vertical.png Tutorials/img/arraywidget3D_1.png modules/gui/../../../../silx/resources/gui/icons/zoom-in.png modules/gui/../../../../silx/resources/gui/icons/clipboard.png modules/gui/plot/img/fftAction0.png modules/gui/../../../../silx/resources/gui/icons/view-2d-stack.png Tutorials/Sift/output_5_1.png modules/gui/../../../../silx/resources/gui/icons/close.png modules/gui/../../../../silx/resources/gui/icons/zoom-out.png modules/gui/../../../../silx/resources/gui/icons/view-fullscreen.png modules/gui/hdf5/img/Hdf5Example.png modules/gui/../../../../silx/resources/gui/icons/image-select-erase-rubber.png modules/gui/../../../../silx/resources/gui/icons/math-peak-reset.png modules/gui/../../../../silx/resources/gui/icons/image-select-box.png Tutorials/img/fitwidget2.png Tutorials/img/arraywidget5D_0.png Tutorials/img/custom_config_scale0.5.png modules/gui/plot3d/img/Plot3DWindow.png modules/gui/../../../../silx/resources/gui/icons/document-open.png modules/gui/../../../../silx/resources/gui/icons/plot-yup.png modules/gui/../../../../silx/resources/gui/icons/edit-copy.png Tutorials/Sift/output_7_1.png modules/gui/../../../../silx/resources/gui/icons/item-2dim.png modules/gui/../../../../silx/resources/gui/icons/math-sigma.png modules/gui/../../../../silx/resources/gui/icons/plot-xauto.png modules/gui/plot/img/plot_and_backend.png modules/gui/../../../../silx/resources/gui/icons/shape-ellipse.png modules/gui/data/img/NumpyAxesSelector.png modules/gui/../../../../silx/resources/gui/icons/plot-roi-below.png modules/gui/../../../../silx/resources/gui/icons/plot-roi.png modules/gui/../../../../silx/resources/gui/icons/profile1D.png modules/gui/../../../../silx/resources/gui/icons/normal.png modules/gui/../../../../silx/resources/gui/icons/plot-roi-reset.png modules/gui/../../../../silx/resources/gui/icons/shape-polygon.png modules/gui/../../../../silx/resources/gui/icons/image-mask.png Tutorials/Sift/output_6_1.png modules/gui/../../../../silx/resources/gui/icons/math-fit.png description/img/sift_bench_cpu0.png modules/gui/../../../../silx/resources/gui/icons/window-new.png modules/gui/../../../../silx/resources/gui/icons/math-peak.png modules/gui/plot/img/LimitsToolBar.png modules/gui/../../../../silx/resources/gui/icons/rudder.png modules/gui/../../../../silx/resources/gui/icons/plot-window-image.png modules/gui/../../../../silx/resources/gui/icons/image-select-add.png description/img/sift_dog1.png modules/gui/../../../../silx/resources/gui/icons/zoom.png modules/gui/data/img/DataViewerFrame.png modules/gui/../../../../silx/resources/gui/icons/math-substract.png Tutorials/img/custom_config_scale2.1.png modules/gui/data/img/DataViewer.png modules/gui/plot/img/netCounts.png modules/gui/../../../../silx/resources/gui/icons/shape-square.png Tutorials/img/stripbg_plot2.png modules/gui/../../../../silx/resources/gui/icons/plot-roi-above.png Tutorials/Sift/output_2_1.png description/img/sift_match1.png modules/gui/../../../../silx/resources/gui/icons/next.png Tutorials/img/fitwidget5.png modules/gui/../../../../silx/resources/gui/icons/math-energy.png modules/gui/../../../../silx/resources/gui/icons/plot-xlog.png modules/gui/hdf5/img/Hdf5TreeView.png modules/gui/../../../../silx/resources/gui/icons/first.png modules/gui/../../../../silx/resources/gui/icons/camera.png modules/gui/../../../../silx/resources/gui/icons/view-nofullscreen.png modules/gui/plot/img/Plot2D.png modules/gui/../../../../silx/resources/gui/icons/math-ymin-to-zero.png modules/gui/plot/img/PlotWidget.png modules/gui/plot/img/PositionInfo.png modules/gui/../../../../silx/resources/gui/icons/arrow-keys.png modules/gui/../../../../silx/resources/gui/icons/cube-bottom.png modules/gui/plot/img/fftAction1.png modules/gui/../../../../silx/resources/gui/icons/cube-back.png modules/gui/../../../../silx/resources/gui/icons/item-0dim.png modules/gui/../../../../silx/resources/gui/icons/image.png description/img/sift_bench_gpu0.png modules/gui/../../../../silx/resources/gui/icons/folder.png modules/gui/../../../../silx/resources/gui/icons/selected.png modules/gui/../../../../silx/resources/gui/icons/item-1dim.png modules/gui/../../../../silx/resources/gui/icons/crosshair.png modules/gui/../../../../silx/resources/gui/icons/shape-horizontal.png modules/gui/../../../../silx/resources/gui/icons/view-raw.png modules/gui/../../../../silx/resources/gui/icons/sliders-off.png modules/gui/../../../../silx/resources/gui/icons/plot-widget.png modules/gui/../../../../silx/resources/gui/icons/view-1d.png modules/gui/../../../../silx/resources/gui/icons/math-smooth.png modules/gui/../../../../silx/resources/gui/icons/draw-rubber.png modules/gui/../../../../silx/resources/gui/icons/document-print.png modules/gui/../../../../silx/resources/gui/icons/silx.png modules/gui/../../../../silx/resources/gui/icons/plot-roi-between.png modules/gui/plot/img/roiwidget.png modules/gui/../../../../silx/resources/gui/icons/math-peak-search.png modules/gui/plot/img/ImageView.png Tutorials/img/arraywidget5D_1.png modules/gui/../../../../silx/resources/gui/icons/shape-diagonal.png Tutorials/img/fitwidget4.png modules/gui/../../../../silx/resources/gui/icons/shape-ellipse-solid.png modules/gui/../../../../silx/resources/gui/icons/plot-toggle-points.png modules/gui/../../../../silx/resources/gui/icons/previous.png modules/gui/../../../../silx/resources/gui/icons/plot-window.png modules/gui/plot3d/img/ScalarFieldView.png modules/gui/../../../../silx/resources/gui/icons/view-refresh.png modules/gui/../../../../silx/resources/gui/icons/math-normalize.png modules/gui/../../../../silx/resources/gui/icons/view-3d.png modules/gui/plot/img/rawCounts.png modules/gui/../../../../silx/resources/gui/icons/cube-top.png modules/gui/plot/img/shiftAction0.png modules/gui/../../../../silx/resources/gui/icons/item-object.png modules/gui/../../../../silx/resources/gui/icons/3d-plane.png modules/gui/../../../../silx/resources/gui/icons/view-2d.png modules/gui/../../../../silx/resources/gui/icons/plot-yauto.png modules/gui/../../../../silx/resources/gui/icons/3d-plane-normal-x.png modules/gui/../../../../silx/resources/gui/icons/3d-plane-normal-y.png modules/gui/../../../../silx/resources/gui/icons/shape-circle-solid.png modules/gui/../../../../silx/resources/gui/icons/item-ndim.png modules/gui/../../../../silx/resources/gui/icons/last.png modules/gui/plot/img/shiftAction3.png modules/gui/../../../../silx/resources/gui/icons/spec.png modules/gui/../../../../silx/resources/gui/icons/test-png.png modules/gui/../../../../silx/resources/gui/icons/sliders-on.png modules/gui/../../../../silx/resources/gui/icons/math-derive.png
copying TeX support files...
done
build succeeded, 20 warnings.
make[1]: Leaving directory '/mntdirect/_bliss/users/valls/workspace/test_build_silx/package/silx-0.5.0a0'
   debian/rules override_dh_auto_test
make[1]: Entering directory '/mntdirect/_bliss/users/valls/workspace/test_build_silx/package/silx-0.5.0a0'
dh_auto_test -- -s custom --test-args="env PYTHONPATH={build_dir} WITH_QT_TEST=False {interpreter} run_tests.py"
I: pybuild base:170: env PYTHONPATH=/mntdirect/_bliss/users/valls/workspace/test_build_silx/package/silx-0.5.0a0/.pybuild/pythonX.Y_2.7/build WITH_QT_TEST=False python2.7 run_tests.py
INFO:silx.setup:Use setuptools
INFO:silx.setup:Use setuptools.setup
WARNING:run_tests:Test silx 0.5.0-dev0 from /mntdirect/_bliss/users/valls/workspace/test_build_silx/package/silx-0.5.0a0/.pybuild/pythonX.Y_2.7/build/silx
WARNING:silx.test.test_sx:silx.sx tests disabled (env. variable WITH_QT_TEST=False)
WARNING:silx.image.sift.test.test_matching:feature module is not available to compare results with C++ implementation. Matching cannot be tested.
WARNING:silx.gui.test:silx.gui tests disabled (env. variable WITH_QT_TEST=False)
ss................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................WARNING:silx.math.fit.leastsq:Supplied function does not return a 1D array of floats.
Function should be rewritten.
Trying to reshape output.
WARNING:silx.math.fit.leastsq:Supplied function does not return a 1D array of floats.
Function should be rewritten.
Trying to reshape output.
../mntdirect/_bliss/users/valls/workspace/test_build_silx/package/silx-0.5.0a0/.pybuild/pythonX.Y_2.7/build/silx/math/fit/test/test_fit.py:51: RuntimeWarning: invalid value encountered in multiply
  return numpy.exp(x*numpy.less(abs(x), 250)) - \
WARNING:silx.math.fit.leastsq:Supplied function does not return a proper array of floats.
Function should be rewritten to return a 1D array of floats.
Trying to reshape output.
WARNING:silx.math.fit.leastsq:Supplied function unable to handle non-finite x data
Attempting to filter out those x data values.
WARNING:silx.math.fit.leastsq:Need to reshape input xdata.
................................................................................................................WARNING:/mntdirect/_bliss/users/valls/workspace/test_build_silx/package/silx-0.5.0a0/.pybuild/pythonX.Y_2.7/build/silx/image/sift/test/test_gaussian.py:preprocess Limiting workgroup size to 1024
WARNING:/mntdirect/_bliss/users/valls/workspace/test_build_silx/package/silx-0.5.0a0/.pybuild/pythonX.Y_2.7/build/silx/image/sift/test/test_gaussian.py:gaussian Limiting workgroup size to 1024
................................/usr/lib/python2.7/dist-packages/pyopencl/__init__.py:61: CompilerWarning: Non-empty compiler output encountered. Set the environment variable PYOPENCL_COMPILER_OUTPUT=1 to see more.
  "to see more.", CompilerWarning)
.Maximum valid workgroup size 1024 on device <pyopencl.Device 'GeForce GTX TITAN X' on 'NVIDIA CUDA' at 0x24329a0>

----------------------------------------------------------------------
Ran 645 tests in 25.824s

OK (skipped=2)
WARNING:run_tests:Skipped silx.test.test_sx.SkipSXTest.runTest (): silx.sx tests disabled (env. variable WITH_QT_TEST=False)
WARNING:run_tests:Skipped silx.gui.test.SkipGUITest.runTest (): silx.gui tests disabled (env. variable WITH_QT_TEST=False)
I: pybuild base:170: env PYTHONPATH=/mntdirect/_bliss/users/valls/workspace/test_build_silx/package/silx-0.5.0a0/.pybuild/pythonX.Y-dbg_2.7/build WITH_QT_TEST=False python2.7-dbg run_tests.py
INFO:silx.setup:Use setuptools
INFO:silx.setup:Use setuptools.setup
[161192 refs]
WARNING:run_tests:Test silx 0.5.0-dev0 from /mntdirect/_bliss/users/valls/workspace/test_build_silx/package/silx-0.5.0a0/.pybuild/pythonX.Y-dbg_2.7/build/silx
WARNING:silx.test.test_sx:silx.sx tests disabled (env. variable WITH_QT_TEST=False)
WARNING:silx.opencl:Unable to import pyOpenCl. Please install it from: http://pypi.python.org/pypi/pyopencl
WARNING:sift.match:No PyOpenCL, no sift
WARNING:sift.alignment:No PyOpenCL, no sift
WARNING:silx.image.sift.test.test_matching:feature module is not available to compare results with C++ implementation. Matching cannot be tested.
WARNING:silx.gui.test:silx.gui tests disabled (env. variable WITH_QT_TEST=False)
ss..........................................................................................................................................................ss...ERROR:silx.io.fabioh5:Module silx.io.fabioh5 requires fabio
.ERROR:silx.io.fabioh5:Module silx.io.fabioh5 requires fabio
........sssssssssssss...........................................................................................................................................................................................................................................................................................................................WARNING:silx.math.fit.leastsq:Supplied function does not return a 1D array of floats.
Function should be rewritten.
Trying to reshape output.
WARNING:silx.math.fit.leastsq:Supplied function does not return a 1D array of floats.
Function should be rewritten.
Trying to reshape output.
../mntdirect/_bliss/users/valls/workspace/test_build_silx/package/silx-0.5.0a0/.pybuild/pythonX.Y-dbg_2.7/build/silx/math/fit/test/test_fit.py:51: RuntimeWarning: invalid value encountered in multiply
  return numpy.exp(x*numpy.less(abs(x), 250)) - \
WARNING:silx.math.fit.leastsq:Supplied function does not return a proper array of floats.
Function should be rewritten to return a 1D array of floats.
Trying to reshape output.
WARNING:silx.math.fit.leastsq:Supplied function unable to handle non-finite x data
Attempting to filter out those x data values.
WARNING:silx.math.fit.leastsq:Need to reshape input xdata.
..........................................................................................python2.7-dbg: silx/math/medianfilter/include/median_filter.hpp:93: void median_filter(const T*, T*, int*, int*, int, int, int, int, bool) [with T = short int]: Assertion `x_pixel_range_min <= x_pixel_range_max' failed.
Aborted
E: pybuild pybuild:256: test: plugin custom failed with: exit code=134: env PYTHONPATH=/mntdirect/_bliss/users/valls/workspace/test_build_silx/package/silx-0.5.0a0/.pybuild/pythonX.Y-dbg_2.7/build WITH_QT_TEST=False python2.7-dbg run_tests.py
dh_auto_test: pybuild --test -i python{version}-dbg -p 2.7 -s custom --test-args=env PYTHONPATH={build_dir} WITH_QT_TEST=False {interpreter} run_tests.py --dir . returned exit code 13
debian/rules:39: recipe for target 'override_dh_auto_test' failed
make[1]: *** [override_dh_auto_test] Error 13
make[1]: Leaving directory '/mntdirect/_bliss/users/valls/workspace/test_build_silx/package/silx-0.5.0a0'
debian/rules:13: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
Build failed, please investigate ...
```

**Comment by vallsv** [comment]
This is the interesting thing
```
python2.7-dbg: silx/math/medianfilter/include/median_filter.hpp:93: void median_filter(const T*, T*, int*, int*, int, int, int, int, bool) [with T = short int]: Assertion `x_pixel_range_min <= x_pixel_range_max' failed.
```
