### ISSUE TITLE
SpecFile: Detector labels with / not supported

### ISSUE THREAD

**Issue by PiRK** [silx-kit/silx#759]
Having a / in a detector name causes errors at multiple levels.

Data example:

```
#F /data/id09/archive/logspecfiles/laue/2016/scan_231_laue_16-11-29.dat
#D Sat Dec 10 22:20:59 2016

#S 1 laue_16-11-29.log 231.1 PD3/A
#D Sat Dec 10 22:20:59 2016
#N 2
#L GONY/mm  PD3/A
-2.015  5.250424e-05
-2.01  5.30798e-05
-2.005  5.281903e-05
-2  5.220436e-05
```

Error in `DataViewer`:

```
ERROR:silx.gui.qt._qt:<type 'exceptions.AttributeError'> 'NoneType' object has no attribute 'name'   File "/users/knobel/.local/lib/python2.7/site-packages/silx/gui/hdf5/NexusSortFilterProxyModel.py", line 75, in lessThan
    if self.__isNXentry(left) and self.__isNXentry(right):
  File "/users/knobel/.local/lib/python2.7/site-packages/silx/gui/hdf5/NexusSortFilterProxyModel.py", line 89, in __isNXentry
    if not issubclass(node.h5pyClass, h5py.Group):
  File "/users/knobel/.local/lib/python2.7/site-packages/silx/gui/hdf5/Hdf5Item.py", line 92, in h5pyClass
    self.__h5pyClass = silx.io.utils.get_h5py_class(self.obj)
  File "/users/knobel/.local/lib/python2.7/site-packages/silx/gui/hdf5/Hdf5Item.py", line 74, in obj
    self.__initH5pyObject()
  File "/users/knobel/.local/lib/python2.7/site-packages/silx/gui/hdf5/Hdf5Item.py", line 145, in __initH5pyObject
    self.__obj.name = parent_name + "/" + self.__key
```

Error in `spech5`:
```
In [1]: from silx.io.spech5 import SpecH5

In [2]: sh = SpecH5("step_down.dat")

In [3]: sh.keys()
Out[3]: [u'1.1']

In [4]: sh["1.1"].keys()
Out[4]: [u'title', u'start_time', u'instrument', u'measurement']

In [6]: sh["1.1/measurement"].keys()
Out[6]: [u'GONY/mm', u'PD3/A']

In [7]: sh["1.1/measurement/PD3/A"].keys()
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-7-730729c25cde> in <module>()
----> 1 sh["1.1/measurement/PD3/A"].keys()

/users/knobel/.local/lib/python2.7/site-packages/silx/io/spech5.pyc in __getitem__(self, key)
   1362             return _link_to_dataset_builder(full_key, self.file, self)
   1363         else:
-> 1364             raise KeyError("unrecognized group or dataset: " + full_key)
   1365 
   1366     def __iter__(self):

KeyError: 'unrecognized group or dataset: /1.1/measurement/PD3/A'
```

i suspect that this can break in even more ways, if we fix these 2 issues.
Should we support "/" in names ?

**Comment by vasole** [comment]
The "/" has to be replaced by something else that does not confuse h5py.

I propose thinks like:

- An underscore "_"
- A single space " "
- A vertical bar "|"

I would vote the vertical bar. It seems the closest to the original thing.

**Comment by PiRK** [comment]
We decided to use `%` sign, as it's meaning is closer to `/` in most situations.
