### ISSUE TITLE
[packaging] seg fault during nightly build

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#813]
Reproduced by importing twice pyopencl with python2.7-dbg:
```
$ python2.7-dbg
>>> import pyopencl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/pyopencl/__init__.py", line 28, in <module>
    import pyopencl._cl as _cl
ImportError: /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.55.0: undefined symbol: Py_InitModule4_64
[44627 refs]
>>> import pyopencl
Segmentation fault
```

The `silx.opencl.common` module seems to import twice pyopencl leading to seg fault in nightly build.
This can be cleaned up, but the issue will remain when importing twice pyopencl... This needs more investigation.

**Comment by t20100** [comment]
I'm closing this issue, nightly build now OK.
