### ISSUE TITLE
[manylinux] dlopen: cannot load any more object with static TLS

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#844]
Hi,

I am afraid the manylinux silx package is not working. Or maybe i have a problem on my env. I am using a Debian 8.

```
$ pip install silx==0.5 --user
Collecting silx==0.5
  Downloading silx-0.5.0-cp27-cp27mu-manylinux1_x86_64.whl (5.8MB)
    100% |████████████████████████████████| 5.8MB 233kB/s
Successfully installed silx-0.5.0
```
Then
```
$ ./bootstrap.py pyFAI-calib2
WARNING:root:Failed to bind rconsole to socket port, port=54321.
WARNING:silx.gui.plot.backends._matplotlib:matplotlib already loaded, setting its backend may not work
Traceback (most recent call last):
  File "./bootstrap.py", line 200, in <module>
    run_entry_point(target, argv)
  File "./bootstrap.py", line 125, in run_entry_point
    func()
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-2.7/pyFAI/app/calib2.py", line 385, in main
    widget = CalibrationWindow()
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-2.7/pyFAI/gui/calibration/CalibrationWindow.py", line 44, in __init__
    self.__tasks = self.createTasks()
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-2.7/pyFAI/gui/calibration/CalibrationWindow.py", line 54, in createTasks
    from pyFAI.gui.calibration.ExperimentTask import ExperimentTask
  File "/workspace/valls/pyfai.git/build/lib.linux-x86_64-2.7/pyFAI/gui/calibration/ExperimentTask.py", line 37, in <module>
    import silx.gui.plot
  File "/home/valls/.local/lib/python2.7/site-packages/silx/gui/plot/__init__.py", line 66, in <module>
    from .PlotWindow import PlotWindow, Plot1D, Plot2D  # noqa
  File "/home/valls/.local/lib/python2.7/site-packages/silx/gui/plot/PlotWindow.py", line 41, in <module>
    from . import PlotActions
  File "/home/valls/.local/lib/python2.7/site-packages/silx/gui/plot/PlotActions.py", line 79, in <module>
    from silx.math.histogram import Histogramnd
  File "/home/valls/.local/lib/python2.7/site-packages/silx/math/__init__.py", line 31, in <module>
    from .medianfilter import medfilt, medfilt1d, medfilt2d
  File "/home/valls/.local/lib/python2.7/site-packages/silx/math/medianfilter/__init__.py", line 30, in <module>
    from .medianfilter import *
ImportError: dlopen: cannot load any more object with static TLS
```

**Comment by vallsv** [comment]
If i use
```
pip install silx==0.5 --user --upgrade --no-binary :all:
```
it is fine.

**Comment by t20100** [comment]
Sounds old, @vallsv can this be closed?

**Comment by vallsv** [comment]
I guess. I dont really remember the env or what.
