### ISSUE TITLE
[plot] Random test failure

### ISSUE THREAD

**Issue by t20100** [silx-kit/silx#974]
There is random failure of tests on Appveyor here with python2/PyQt4:
```
======================================================================
ERROR: testFailingConverters (silx.gui.plot.test.testPlotTools.TestPositionInfo)
Test PositionInfo with failing custom converters
----------------------------------------------------------------------
Traceback (most recent call last):
File "C:\projects\silx\venv_test\lib\site-packages\silx\gui\plot\test\testPlotTools.py", line 136, in testFailingConverters
self._test(positionWidget, ['Exception'], error=2)
File "C:\projects\silx\venv_test\lib\site-packages\silx\gui\plot\test\testPlotTools.py", line 110, in _test
self.qWait(100)
File "C:\projects\silx\venv_test\lib\site-packages\silx\test\utils.py", line 171, in __exit__
expected_count, logging.getLevelName(level), count))
RuntimeError: Expected 2 ERROR logging messages, got 0
======================================================================
FAIL: testSigMaskChangedEmitted (silx.gui.plot.test.testMaskToolsWidget.TestMaskToolsWidget)
----------------------------------------------------------------------
Traceback (most recent call last):
File "C:\projects\silx\venv_test\lib\site-packages\silx\gui\plot\test\testMaskToolsWidget.py", line 282, in testSigMaskChangedEmitted
self.assertGreater(len(l), 0)
AssertionError: 0 not greater than 0
======================================================================
FAIL: testWithAnImage (silx.gui.plot.test.testMaskToolsWidget.TestMaskToolsWidget)
Plot with an image: test MaskToolsWidget interactions [] (origin=(0, 0), scale=(1, 1))
----------------------------------------------------------------------
Traceback (most recent call last):
File "C:\projects\silx\venv_test\lib\site-packages\silx\gui\plot\test\testMaskToolsWidget.py", line 169, in testWithAnImage
numpy.all(numpy.equal(self.maskWidget.getSelectionMask(), 0)))
AssertionError: True is not false
======================================================================
FAIL: testLoadSaveCsv (silx.gui.plot.test.testScatterMaskToolsWidget.TestScatterMaskToolsWidget)
----------------------------------------------------------------------
Traceback (most recent call last):
File "C:\projects\silx\venv_test\lib\site-packages\silx\gui\plot\test\testScatterMaskToolsWidget.py", line 263, in testLoadSaveCsv
self.__loadSave("csv")
File "C:\projects\silx\venv_test\lib\site-packages\silx\gui\plot\test\testScatterMaskToolsWidget.py", line 245, in __loadSave
self.assertFalse(numpy.all(numpy.equal(ref_mask, 0)))
AssertionError: True is not false
======================================================================
FAIL: testLoadSaveNpy (silx.gui.plot.test.testScatterMaskToolsWidget.TestScatterMaskToolsWidget)
----------------------------------------------------------------------
Traceback (most recent call last):
File "C:\projects\silx\venv_test\lib\site-packages\silx\gui\plot\test\testScatterMaskToolsWidget.py", line 260, in testLoadSaveNpy
self.__loadSave("npy")
File "C:\projects\silx\venv_test\lib\site-packages\silx\gui\plot\test\testScatterMaskToolsWidget.py", line 245, in __loadSave
self.assertFalse(numpy.all(numpy.equal(ref_mask, 0)))
AssertionError: True is not false
======================================================================
FAIL: testSigMaskChangedEmitted (silx.gui.plot.test.testScatterMaskToolsWidget.TestScatterMaskToolsWidget)
----------------------------------------------------------------------
Traceback (most recent call last):
File "C:\projects\silx\venv_test\lib\site-packages\silx\gui\plot\test\testScatterMaskToolsWidget.py", line 300, in testSigMaskChangedEmitted
self.assertGreater(len(l), 0)
AssertionError: 0 not greater than 0
======================================================================
FAIL: testWithAScatter (silx.gui.plot.test.testScatterMaskToolsWidget.TestScatterMaskToolsWidget)
Plot with a Scatter: test MaskToolsWidget interactions
----------------------------------------------------------------------
Traceback (most recent call last):
File "C:\projects\silx\venv_test\lib\site-packages\silx\gui\plot\test\testScatterMaskToolsWidget.py", line 171, in testWithAScatter
numpy.all(numpy.equal(self.maskWidget.getSelectionMask(), 0)))
AssertionError: True is not false
======================================================================
FAIL: test (silx.gui.plot.test.testPlotInteraction.TestSelectPolygon)
Test draw polygons + events
----------------------------------------------------------------------
Traceback (most recent call last):
File "C:\projects\silx\venv_test\lib\site-packages\silx\gui\plot\test\testPlotInteraction.py", line 140, in test
self.assertEqual(len(drawEvents[-1]['points']), 3)
AssertionError: 4 != 3
----------------------------------------------------------------------
Ran 988 tests in 113.338s
FAILED (failures=7, errors=1, skipped=41)
```

**Comment by t20100** [comment]
Got this on Travis with python3/pyQt5:

```
FAIL: testWithAnImage (silx.gui.plot.test.testMaskToolsWidget.TestMaskToolsWidget) (origin=(1000, 1000), scale=(-1, -1))

Plot with an image: test MaskToolsWidget interactions

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/silx/gui/plot/test/testMaskToolsWidget.py", line 195, in testWithAnImage

    numpy.all(numpy.equal(self.maskWidget.getSelectionMask(), 0)))

AssertionError: False is not true

----------------------------------------------------------------------
```

**Comment by t20100** [comment]
I think this is no more an issue.
Shall we close it?

**Comment by t20100** [comment]
Closing as no more occuring
